### ISSUE TITLE
Provide a way to install via brew cask

### ISSUE THREAD

**Issue by domoritz** [rxhanson/Rectangle#1]
First off, I want to say how excited I am to see a new spectacle implementation. I would love to use this when it has gained feature parity. Could you provide a way to install this app via brew cask with the next release?

**Comment by rxhanson** [comment]
Thanks! I actually already tried to add it to brew cask, and it was denied because the project needs at least 50 stars on github to get approved. So... hopefully it's just a matter of time!

**Comment by domoritz** [comment]
I guess the project still young. I installed the app normally and starred your project. Looking forward to future developments.

**Comment by Crocmagnon** [comment]
Pretty excited too, I starred to give more visibility 😊

**Comment by MarcelBlockchain** [comment]
read this thread and gave the repo a star :)

**Comment by reidcooper** [comment]
Gave it a star, 50!

**Comment by rxhanson** [comment]
Thanks everyone!!! Here's the brew cask PR: https://github.com/Homebrew/homebrew-cask/pull/67349

**Comment by rxhanson** [comment]
brew cask PR merged!
