### ISSUE TITLE
Firefox maximizing issue

### ISSUE THREAD

**Issue by jadchaar** [rxhanson/Rectangle#101]
macOS version: 10.15.3
Rectangle version: 0.22

For some reason, Firefox does not seem to be maximizing correctly. It appears to extend beyond the dock:
<img width="1280" alt="Screen Shot 2020-03-05 at 2 01 58 PM" src="https://user-images.githubusercontent.com/7388203/76015925-f8a25300-5ee9-11ea-86f0-390b4007ab5d.png">

I am using Firefox 74 beta.

**Comment by rxhanson** [comment]
Thanks for reporting! Unfortunately, I don't plan on rolling in a change that will fix this. It's basically a macOS bug that probably all window manager apps expose - I saw this bug reported multiple times in Spectacle's issues. Special-casing certain apps to have 1 or 2 pixels less isn't a good workaround - there's a ton of edge cases around it (is the dock exposed, where is the dock, etc).
