### ISSUE TITLE
Updates to v0.64 is failing

### ISSUE THREAD

**Issue by sirjangoon** [rxhanson/Rectangle#1022]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.6.1
Rectangle version: v0.63 (69)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

Updating from within the app to v0.64 is failing. I suspect this is because there's a typo in the released version where it's missing the usual 'v' prefix seen in other versions.

https://github.com/rxhanson/Rectangle/releases/download/v0.64/Rectangle0.64.dmg - What I think the app is trying to download updates from

https://github.com/rxhanson/Rectangle/releases/download/0.64/Rectangle0.64.dmg - The actual location of the latest release.

**Comment by rxhanson** [comment]
Thanks! Should be all set now.

**Comment by MGough** [comment]
I'm still seeing this, is there any way I can help debug?
<img width="632" alt="Screenshot 2022-12-09 at 12 26 13" src="https://user-images.githubusercontent.com/6558104/206702274-6f6d1970-ab2d-496a-90e7-0bff573b55d9.png">
<img width="271" alt="Screenshot 2022-12-09 at 12 26 17" src="https://user-images.githubusercontent.com/6558104/206702278-51db342f-855a-4020-80e7-f18a2feba832.png">

**Comment by rxhanson** [comment]
Thanks for letting me know. I think it's finally all set now.
