### ISSUE TITLE
Screenshot on the landing page

### ISSUE THREAD

**Issue by noclat** [rxhanson/Rectangle#103]
Just adding a screenshot of the controls + a grid layout on the landing page would help making it more attractive :).

**Comment by rxhanson** [comment]
Absolutely. Any chance you'd be up for making a nice looking grid layout image?

**Comment by HansNewbie** [comment]
<img width="1792" alt="Rectangle Screenshot" src="https://user-images.githubusercontent.com/3381536/77216738-ab63e980-6b57-11ea-8af4-ba2587375c91.png">

Something like this?

**Comment by yochem** [comment]
Here are some images that show the new gaps feature, LMK if they are useful or when one needs some tweaking.

![image](https://user-images.githubusercontent.com/23235841/79700685-e9a81200-8297-11ea-9aa4-aec80c09d283.png)

![image](https://user-images.githubusercontent.com/23235841/79700806-cb8ee180-8298-11ea-9344-2fc82f5495ed.png)

![image](https://user-images.githubusercontent.com/23235841/79700834-f9742600-8298-11ea-8bd5-b1c1301ecf3e.png)

**Comment by rxhanson** [comment]
Thanks, guys for the screenshots! As you might have guessed from the barebones landing page, website building/modification is something that I typically don't prioritize, but rest assured I will add in a screenshots section next time I get a block of time to devote to it.

**Comment by rxhanson** [comment]
Well... Sorry about this never making it in. I definitely appreciate the screenshots, but I kinda feel like nowadays a screenshot is actually not necessary for the homepage with how common window managers are. Doing some housekeeping and closing out old issues. Thanks all!
