### ISSUE TITLE
Next/Previous Display doesn't work on MacOS 13.1 Beta (22C5033e)

### ISSUE THREAD

**Issue by beautiful-boyyy** [rxhanson/Rectangle#1034]
- [✅] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: MacOS 13.1 Beta (22C5033e)
Rectangle version: 0.64(70)

Nothing happened after I press the relevant keys
my keybinding

<img width="758" alt="Screenshot 2022-12-16 at 23 47 12" src="https://user-images.githubusercontent.com/66351806/208136159-6b1ed1ba-1101-4d31-8966-381d73882533.png">

**Comment by qayyumayaan** [comment]
I have the same issue and here is my log. It appears Rectangle cannot obtain the window ID of a window.  
[rectangleLogs.txt](https://github.com/rxhanson/Rectangle/files/10272566/rectangleLogs.txt)

**Comment by rxhanson** [comment]
@qayyumayaan thanks for the log. Does this happen for all apps? Do other keyboard shortcuts work? 

If it's just one app, try restarting that app.
