### ISSUE TITLE
Rectangle Doesn't Resize Windows

### ISSUE THREAD

**Issue by Whishoryi** [rxhanson/Rectangle#1035]
macOS Version: 12.6.2
Rectangle Version: 0.64

I've given Rectangle the requested permissions, and to no avail does it resize my windows. I'm on the recommended settings and Command-Shift-Left Arrow doesn't work, as well as the other keybinds.

**Comment by jmd-rd** [comment]
Yup, I was using Spectacle prior to this, then was recommended Rectangle, and both, despite changing Option/Control/Command shortcuts, do not move nor resize windows. 

Stopped working upon updating to macOS Monterey 12.5.

**Comment by Whishoryi** [comment]
Thank you so much! I thought it was my Mac. Much love!
