### ISSUE TITLE
missing "ignore app" option

### ISSUE THREAD

**Issue by ggojedap** [rxhanson/Rectangle#105]
macOS version: Mojave
Rectangle version: 0.23

dear Rectangle team,

Sorry if this is not a bug but I can't find the option "Ignore app". Could you please tell me where or how I can use that feature?

Thank you.
![Captura de Pantalla 2020-03-16 a la(s) 8 09 36 p  m](https://user-images.githubusercontent.com/43002737/76812286-6855ef00-67c2-11ea-8487-cc79072b3586.png)

**Comment by rxhanson** [comment]
This is actually a bug. 

The menu item is missing because Rectangle cannot obtain the frontmost window via the accessibility API at the moment the menu is displayed.

**Comment by rxhanson** [comment]
As a workaround until something more permanent goes in, you can try restarting the app as noted in https://github.com/rxhanson/Rectangle/issues/47.

Apparently what's happening is that sometimes macOS doesn't send Rectangle a notification that the frontmost app has changed, even though Rectangle has properly subscribed to the notification.

**Comment by ggojedap** [comment]
thank you. I will test this workaround

**Comment by rxhanson** [comment]
Just a quick update. The bug is Rectangle side and I have a fix checked in for it but just don't have a release out yet.

**Comment by ggojedap** [comment]
thanks! I will be attentive to any progress. by the way, awesome app!

**Comment by rxhanson** [comment]
Release 0.24 has this in it: https://github.com/rxhanson/Rectangle/releases/tag/v0.24

Closing this one out, but feel free to reopen if there's any issues with it.

**Comment by ggojedap** [comment]
0.24 Tested in Mojave and Catalina. Works perfectly fine. Thank you!
