### ISSUE TITLE
XQuartz windows can't be manipulated.

### ISSUE THREAD

**Issue by yeroc** [rxhanson/Rectangle#107]
macOS version: 10.12
Rectangle version: 0.23

Similar to an issue reported against [Spectacle](https://github.com/eczarny/spectacle/issues/801).

To reproduce:

1. Launch Rectangle
1. Open XQuartz
1. Choose Applications -> Terminal to open `xterm`
1. Use ⌥ ⌘ <- or any one of the other Rectangle shortcuts

Result:

Window is not moved.

I've also tried manipulating the windows via the `snap windows by dragging` option and that doesn't work either.

**Comment by rxhanson** [comment]
I have no plans to implement support for XQuartz at this time, so I'm going to close this one out (sorry!). I would consider a pull request for it, though.

**Comment by yeroc** [comment]
Do you have any insight into what the issue(s) is and how it might be worked around?

**Comment by rxhanson** [comment]
I'm not an XQuartz user, so I don't have too much insight. Rectangle, and all other macOS window manager apps I'm aware of work by telling the Accessibility API to move and position windows. If XQuartz doesn't respond to the Accessibility API, then I'm pretty sure that means that you will have to figure out how to get XQuartz windows to set their size and position. All of Rectangle's window sizing/positioning is passed around by CGRect instances, so theoretically you could plug into Rectangle's code where you just take the CGRect calculated by Rectangle and provide that to XQuartz (translated as needed) and get XQuartz to set the desired window's size and position. In Rectangle, that would happen in the WindowManager class. I'm sure there's more to it, like determining frontmost window and all, depending on how friendly XQuartz is to work with. 

I could be wrong about it this, but from the outside this looks like a decent sized problem.

**Comment by yeroc** [comment]
The alternative I guess is to open a ticket against XQuartz to have them report the correct Accessibility information so they can be manipulated in the standard way?

**Comment by rxhanson** [comment]
Definitely worth it to at least inquire and see if it's possible from XQuartz first.

**Comment by jrejaud** [comment]
Any update on this by chance? 

I've submitted an Issue on the XQuartz repo:

https://github.com/XQuartz/XQuartz/issues/18

**Comment by yeroc** [comment]
@jrodden1 Thanks for sharing this information as I do still use XQuartz now and again.  I'm currently on a Macbook M1 Air without a notch and I don't see the option you mention (I'm running Sonoma).  On the plus side I don't (yet) have the issue with the windows being stuck at the top like that!
