### ISSUE TITLE
True optional login item (as background task)

### ISSUE THREAD

**Issue by thistlillo** [rxhanson/Rectangle#1070]
My Rectangle.app is set to NOT launch at login.

However, every once in a while it installs itself among the apps to be launched at login. In these cases, indeed, I find the Rectangle option "Launch on login" set. May be this is related to the app update?

Please correct this behaviour.

**Comment by rxhanson** [comment]
Thanks for reporting. I'll be digging into this in the next release, looking into the updated way to do this in Ventura.

**Comment by rxhanson** [comment]
This should have been fixed by the migration to the Ventura launch on login behavior long ago. :)
