### ISSUE TITLE
Framework not found Pods_RectangleLauncher when building with Xcode 14.2 (on macOS 13.1 Ventura)

### ISSUE THREAD

**Issue by nulcow** [rxhanson/Rectangle#1072]
- [✓] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 13.1 Ventura (Xcode 14.2)
Rectangle version: 0.65 (Build 71) according to Xcode project data
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):
`Framework not found Pods_RectangleLauncher` (From Xcode, not rectangle)

I get the error `Framework not found Pods_RectangleLauncher` when attempting to build it using Xcode. I followed the CocoaPods instructions in the README file, but I do not know how to fix this error. I would like to contribute to the project, but I cannot build the Xcode project to test it.

**Comment by rxhanson** [comment]
I’m currently away from my mac but will revisit the instructions I have. In an upcoming release, my plan is to migrate away from Cocoapods to Swift Package Manager.

**Comment by albadam000** [comment]
I'm having the same issue on Ventura 13.2.1 (22D68).

**Comment by sdurham** [comment]
@rxhanson how close are you on switching from pods? I see you have a branch you are working on.
Or can we get the current one fixed so that it at least builds?

**Comment by rxhanson** [comment]
@sdurham I went ahead and rolled in the switch to pods

**Comment by sdurham** [comment]
Sweet! thanks!
