### ISSUE TITLE
Rectangle 0.65 doesn't start in Ventura 13.2 (ARM, M2)

### ISSUE THREAD

**Issue by maaboo** [rxhanson/Rectangle#1074]
- [] This is a new bug that hasn't been documented in a closed issue or in the Readme.

_macOS version:_ Ventura 13.2 22D49
_Rectangle version:_ 0.65
_Logs if applicable (In Rectangle menu, hold option, "View Logging..."):_ N/A
_macOS hardware and environment:_ Macbook Pro 13 2022, Apple M2
_Reproducibility:_ Always (100%)
_Steps to reproduce:_ Launch the app
_Additional info:_
Applications starts without visible marks, it stays in Activity Monitor with 0% CPU for some time and then marked as non-responding

<img width="1440" alt="Screenshot 2023-02-13 at 10 30 13" src="https://user-images.githubusercontent.com/912261/218392636-851cbf45-c6d2-48bf-a73e-916b37976a38.png">

[rectangle-spindump.zip](https://github.com/rxhanson/Rectangle/files/10719513/rectangle-spindump.zip)

**Comment by maaboo** [comment]
Reproduction lost after reboot. I'm waiting it to appear again

**Comment by rxhanson** [comment]
Was that the first time you rebooted since installing Ventura 13.2? With the past few macOS releases, the Accessibility permissions have been a little flaky until a reboot, and that could be the issue.

**Comment by maaboo** [comment]
Likely. Later I noticed that some other apps behaved the same. Let's wait for a while and then close as Cannot Reproduce
