### ISSUE TITLE
Gap at the end of the screen when maximising some apps like Emacs and Terminal.

### ISSUE THREAD

**Issue by simurgh9** [rxhanson/Rectangle#1079]
Some apps (maybe ones that measure height in lines) like Emacs and Terminal leave a little gap at the end of the screen when resized as "Center Half" and other sizes that span the height. This does not happen if I double click on the window decoration top (where the minimise button is).

![out](https://user-images.githubusercontent.com/43047754/219902828-33dc6153-4f9f-4c42-8a85-f02489f2bec7.png)

Left was done by using a Rectangle keybinding and right was done by doubly clicking the window decoration.

This does not quite happen on the laptop's internal display. It happens on a Dell 24-inch (1920 × 1080) monitor. If this could somehow be handled I'll be grateful.

```
macOS version: 13.1 22C65 arm64 
Rectangle version: v0.65 (71)
```

**Comment by rxhanson** [comment]
Unfortunately, I think there is no way to do this using the Accessibility API (the only way to move/resize windows as a 3rd party). Your best bet is finding a configuration in those apps that will turn off window sizing by line height. iTerm2 has a terminal command for it that's in the Rectangle readme, but I don't know about emacs & Terminal.

**Comment by simurgh9** [comment]
Okay I found that putting `(setq frame-resize-pixelwise t)` in the config file fixes the issue.
