### ISSUE TITLE
Cannot control some apps (e.g. Slack)

### ISSUE THREAD

**Issue by peabnuts123** [rxhanson/Rectangle#108]
macOS version: 10.15.3 (19D76)
Rectangle version: Version 0.23 (27)

Perhaps this is well-known. This is a "bug" but it is likely a technical restriction that is hard to solve on Rectangle's end. Some apps don't seem to be controllable through Rectangle (or Spectacle, actually). An example of this is the Slack Desktop client. I would assume there is something "funny" about the way these apps have been built that prevents the way in which Rectangle resizes/moves windows from affecting them.

When trying to move one of these applications the logs print:
```
2020-03-26T08:58:34+13:00: Unable to obtain accessibility element
```
Also, I've just noticed the dropdown menu from the Rectangle icon is grayed out when Slack has focus.

Is there a known cause for this? Just thought I should raise it.

**Comment by rxhanson** [comment]
I just downloaded the slack desktop app from the mac app store and Rectangle works fine with it for me. 

Rectangle and all other window manager apps that I'm aware of use the accessibility API to control windows. If it's unable to grab the accessibility element of the window, then it's really hard to pinpoint what the cause of what you're seeing could be as this is outside the scope of what Rectangle could know or gather information on. This is the first time this has been reported, and I would guess there's probably a decent amount of Rectangle users that use the Slack client, so perhaps there could be something different about your machine. 

Other apps that have the setting enabled in System Prefs:Security&Privacy:Accessibility:Privacy have been known to cause strange behavior to Rectangle, so it may be worth it to go through that list and uncheck anything you really don't need to give the privilege to. 

The dropdown menu will appear disabled when Rectangle can't get the accessibility element.

What are the other apps you're having this issue with?

**Comment by ilyam8** [comment]
i have slack and i have never had problems with controlling it, works for me with latest slack/rectangle

**Comment by peabnuts123** [comment]
Okay. Weird! Feel free to mark this as closed if you like. I will try more things to resolve it.

**Comment by janschill** [comment]
I don't have problems with Slack, but I do have problems with **VS Code** all of a sudden.
Running:
* Rectangle: Version 0.23 (27)
* VS Code: Version: 1.43.1

**Comment by rxhanson** [comment]
@janschill a lot of times, VS Code seems to cause issues based on global keyboard shortcut conflicts. However, if it's printing that output then it would appear the shortcut is properly executed and perhaps there is a glitch in VS Code that prevents it from exposing its window to accessibility properly. The common thread with the Slack client is that they are both built using Electron (as far as I know). So... it could be an issue with Electron.

**Comment by janschill** [comment]
@rxhanson thanks for the insight. As with almost all, I just restarted my computer and it resolved the issue. 🤷‍♂

**Comment by readfm** [comment]
chromeBrowser80.0.3987.149 on macHighSierra10.13.6 not snapping command+option+l/r

firefox, everything else works great, thank you!

**Comment by rxhanson** [comment]
If Chrome causes issues, and Electron based apps cause issues, then there could be a bug in Chromium. 

I'm going to close this one out since either way, it's outside the scope of what I can do from within Rectangle. I'm not going to file a bug with Electron or Chromium since I cannot reproduce this. For anyone that can reproduce it, my suggestion is to go ahead and file a bug with the respective app while you can reproduce it.

**Comment by leonelgalan** [comment]
@peabnuts123, restarting Slack did it for me too. Is it sporadic for you?

@readfm did you try restarting chrome (actually quitting and launching the app)? How about restarting, like @janschill did?

**Comment by readfm** [comment]
@rxhanson many restarts no fix, but drag window to side solves prob
(want fast side by side windows) thank you :)

if priority for you, i'll try everything you ask (keyboard window snap
is my favorite thing, but maybe this nudges me to firefox, where
windows snap flawlessly)

**Comment by rxhanson** [comment]
@readfm if dragging windows works and keyboard shortcuts don't work, then that means you're probably experiencing a different problem than the slack and vscode users on this thread. What do you see in the logs? If you change the shortcut to a different shortcut, do you still have the same problem?

**Comment by readfm** [comment]
@rxhanson changed shortcut, no result. re "logs" where do i check? i'm
mac osx, thx

**Comment by rxhanson** [comment]
https://github.com/rxhanson/Rectangle#view-debug-logging

**Comment by readfm** [comment]
issue resolved (unchecked 'ignore google chrome') thank you!

**Comment by raananraz** [comment]
Hi, getting the same now on slack
2022-12-29T09:13:51+02:00: Window under cursor fallback matched: Notification Center WindowInfo(id: 8, frame: (0.0, 0.0, 3440.0, 1440.0), pid: 600)

**Comment by eltuza** [comment]
> issue resolved (unchecked 'ignore google chrome') thank you!
> […](#)
> On 4/1/20, Ryan Hanson ***@***.***> wrote: https://github.com/rxhanson/Rectangle#view-debug-logging -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#108 (comment)](https://github.com/rxhanson/Rectangle/issues/108#issuecomment-607509858)

same issue here with Slack, it was being silently ignored. 
It would have been nice if the debug logs would show something about the shortcuts being ignored as per the configuration. I only found it due to this comment

**Comment by rxhanson** [comment]
Good point, I'll add that to the logs.

**Comment by SebastianoF** [comment]
> restarting Slack did it for me too

Same. Could not figure out why.

**Comment by mattstabeler** [comment]
Restarting slack fixed this for me too 👍

**Comment by bluskool** [comment]
Restarting Slack also worked for me. The error in the Rectangle logs was something like "unable to find focus window."
