### ISSUE TITLE
Rectangle seems to ignore stage manager recent apps area

### ISSUE THREAD

**Issue by Rydkey** [rxhanson/Rectangle#1087]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 13.2.1
Rectangle version: 66 (72)

Hello, 
it seems that for some reason rectangle ignore stage manager recent apps area size. When I try to put one windows on the first half of the screen and a second one on the other half, they take all the space and do not leave enough space for stage manager. Oddly enough, it works for my other user on the mac.

logs : 

> 2023-02-27T19:26:50+01:00: AX sizing proposed: (832.5, 1015.0), result: (833.0, 1015.0)
> 2023-02-27T19:26:50+01:00: AX position proposed: (842.5, 30.0), result: (842.0, 30.0)
> 2023-02-27T19:26:50+01:00: AX sizing proposed: (832.5, 1015.0), result: (833.0, 1015.0)
> 2023-02-27T19:26:50+01:00: rightHalf | display: (0.0, 0.0, 1680.0, 1025.0), calculatedRect: (842.5, 30.0, 832.5, 1015.0), resultRect: (842.0, 30.0, 833.0, 1015.0), srcScreen: Écran Retina intégré, destScreen: Écran Retina intégré, resultScreen: Écran Retina intégré

What I've tried so far : 

1. restart my computer ; 
2. uninstall / reinstall rectangle via brew and dmg file ;
3. run `defaults delete com.knollsoft.Rectangle` ;

**Comment by rxhanson** [comment]
Thanks for reporting. If you don't mind, can you attach your config?

**Comment by Rydkey** [comment]
![image](https://user-images.githubusercontent.com/19168038/221656981-1cbbad32-d274-475e-afbb-725168e06871.png)


I try to export from the export button but the file doesn't seem to export to the folder that I designate

**Comment by rxhanson** [comment]
We can also get it straight from here:

~/Library/Preferences/com.knollsoft.Rectangle.plist

**Comment by Rydkey** [comment]
[config.zip](https://github.com/rxhanson/Rectangle/files/10843300/config.zip)
This config comes from the Library of the first user from my mac, there is no `com.knollsoft.Rectangle.plist` for my second user.

**Comment by ostojan** [comment]
I have the same problem. App seems to work when there is at least 1 other app _hidden_ in Stage Manager, but... Not every time. Sometimes maximizing (Ctrl+Opt+Enter) circles between _normal_ maximize mode and one that respects Stage Manager area.

**Comment by ozhanozen** [comment]
I have the same problem with 13.2.1. I am using two external monitors with DisplayLink, but the issue is on all screens.

**Comment by Rydkey** [comment]
The last update seems to have resolve my issue. Thanks for the hard work !

**Comment by ozhanozen** [comment]
v0.67 still did not solve my issue.

**Comment by ostojan** [comment]
Same here, app still struggles with stage manage.

**Comment by ozhanozen** [comment]
@Rydkey Could you re-open the issue, please?

**Comment by rxhanson** [comment]
@ozhanozen @ostojan, Please open a new issue, and include any details about your specific setup, like your config or any applicable logs. You can add a link to this issue in the new issue. Thanks!
