### ISSUE TITLE
"Todo Mode" disappears when windows are double clicked to maximize

### ISSUE THREAD

**Issue by derreck503** [rxhanson/Rectangle#1091]
- [X] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Ventura 13.2.1
Rectangle version: 0.66
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): Logging is blank when double clicking the window to maximize. Rectangles is being bypassed.

**Comment by Aaron-Rumpler** [comment]
Double clicking a window's title bar to 'zoom' is native macOS behaviour, and I believe isn't something that Rectangle could override.

**Comment by rxhanson** [comment]
Thanks @Aaron-Rumpler, this is indeed the case. Closing this one out since there's nothing that can be done in Rectangle for it.
