### ISSUE TITLE
Footprint preview is drawn incorrectly when Stage Manager is enabled

### ISSUE THREAD

**Issue by patrickrushton** [rxhanson/Rectangle#1099]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 13.2.1 (22D68
Rectangle version: v0.66 (72)

I have Stage Manager enabled, but the slider "Stage Manager recent apps area" set to 0px.

I would expect the footprint animations to use the entire screen area, however when I drag a window to a snap area, the footprint leaves a gap where the recent apps would appear - the width and height appear correct while the x, y origin is offset. 

After completing the drag, the window is resized as expected (i.e. it doesn't leave a gap for stage manager recent apps) - it's just the footprint that seems to be drawn incorrectly.

**Comment by rxhanson** [comment]
Thanks for reporting. This looks like a macOS bug to me. 

@decodism what do you think? Kind of odd that the footprint window will go to the right place if the cursor is moved to a different snap area on that edge though.
