### ISSUE TITLE
Quick way to swap two halves of a screen

### ISSUE THREAD

**Issue by thangduo** [rxhanson/Rectangle#110]

**Comment by rxhanson** [comment]
Closing this one out since I have no plans to implement it.

**Comment by thangduo** [comment]
Any guidance on how to implement it (on a high level)? So that I can do it myself in a fork.

**Comment by rxhanson** [comment]
Rectangle uses the Accessibility API to manipulate the frontmost window, but you can also use it to grab the top window at a specified location, using `AXUIElementCopyElementAtPosition`. 

First, obtain the accessibility element under the center point of each half of the window. (I wrap the API calls in `AccessibilityElement.swift`), then you can call the `WindowManager`'s execute function for each accessibility element. Rectangle is set up to only call execute once per performed action, so might have to figure out the best way to call it multiple times for one action. One option is to special case it in `ShortcutManager.swift` at `windowActionTriggered`.

**Comment by thangduo** [comment]
Thanks for the info.

**Comment by kamkudla** [comment]
@thangduo Did you end up implementing the swap feature? Thinking of doing it myself as well.

**Comment by thangduo** [comment]
Sorry, no, I haven't got time to implement it. Please do and let the world share the awesome feature!

Thanks,
Thang
