### ISSUE TITLE
Corner Shortcuts Should Be Consistent

### ISSUE THREAD

**Issue by tekemperor** [rxhanson/Rectangle#111]
Repeated use of the corner shortcuts (e.g. top-left) resize the window instead of keeping the window in the corner.

I use math graph quadrant numbers for corners (cmd + opt + 2 => top-left), sometimes I get 1 & 2 confused. Instead of the window not being where I expect it to go, it becomes a different size.

This is an issue primarily because corner positioning and 1/3 or 2/3 resizing are orthogonal concepts.  Instead of the obvious realization that I chose the wrong quadrant, I am left wondering if I used a completely different keyboard shortcut by accident.

If other users are expecting the current functionality, a toggle of this behavior like the toggle for moving screens on left/right positioning instead of resizing would be a reasonable compromise. Another reasonable option is following the Windows window positioning shortcuts (left or right, then up or down => corner).

macOS version: 10.15.3
Rectangle version: 0.24 (28)

**Comment by tekemperor** [comment]
For anyone annoyed by the 1/3, 2/3 resize on repeated position commands, there is a workaround from the README.md.

In Terminal:
`defaults write com.knollsoft.Rectangle subsequentExecutionMode -int 2`

**Comment by rxhanson** [comment]
I'm planning on making the 1/3 2/3 behavior an option, not the default, in a future release. It's there because I wanted Rectangle to be a drop-in replacement for Spectacle originally, but I've never liked that behavior.
