### ISSUE TITLE
Export Shortcuts not working

### ISSUE THREAD

**Issue by ashmidgley** [rxhanson/Rectangle#1113]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

On click of "Export" in settings a "Save As" prompt appears. On Save, no file is created. Downloaded app via site.

macOS version: Ventura 13.2.1
Rectangle version: v0.67 (73)

**Comment by Aaron-Rumpler** [comment]
This looks like it might be a duplicate of #566?

**Comment by rxhanson** [comment]
v0.68 is live, let me know when you get a chance to try it out. Thanks!

**Comment by ashmidgley** [comment]
All sorted! Cheers @rxhanson + @decodism 🎉
