### ISSUE TITLE
Rectangle ignores stage manager recent apps area randomly

### ISSUE THREAD

**Issue by ozhanozen** [rxhanson/Rectangle#1114]
- [] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 13.2.1
Rectangle version: v0.67 and v0.66

The issue is a copy of #1087. Rectangle ignores stage manager recent apps area size, e.g., when you maximize the windows or fit a partials-size window to the left side of the screen. 
- This happens randomly, i.e., repeating the shortcut switches between the correct window size (respecting the recent apps area) and the wrong window size (occluding the recent apps area). 
- This happens less when there is at least one other app hidden in Stage Manager, but still happens.
- Problem occurs on external displays as well as on built-in screen.
- This problem did not exist for me before v0.66.

**Comment by rxhanson** [comment]
I was never able to reproduce this. Do you still have this issue?

**Comment by ozhanozen** [comment]
Yes, I have. With v0.68, it is less frequent, though.

**Comment by selimsandal** [comment]
Same here, randomly ignores stage manager, Ventura latest

**Comment by ozhanozen** [comment]
The same issue persists with v0.69. Do you have any updates on the topic? @rxhanson

**Comment by rxhanson** [comment]
No updates yet. This one would likely take some targeted debug logging. When I get a chance, I'll add it into a beta and post back here.

**Comment by rxhanson** [comment]
@ozhanozen Do you still have this issue in v0.70?

**Comment by ozhanozen** [comment]
> @ozhanozen Do you still have this issue in v0.70?

No, it seems like the issue is now solved. Thanks!
