### ISSUE TITLE
Dragging windows between screens makes them resize

### ISSUE THREAD

**Issue by Syrephis** [rxhanson/Rectangle#1132]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 13.3.1 (22E261)
Rectangle version: v0.67 (73)

**Issue**

When a window gets resized with a mouse, moved to another screen, resized using rectangle shortcuts and moved back to the first screen, the window gets resized back to the original size. I think it only started happening with the newest macOS version.

**Steps to reproduce**
1. Have 2 screens.
2. The "Restore window size when unsnapped" option is unchecked.
3. Resize a window using the mouse on screen A.
4. Move the window to screen B.
5. Resize the window using Rectangle shortcuts (left half, right half, almost maximize, ...).
6. Move the windows back to screen A.
7. The window gets resized back to the size set in Step 3.

**Expected behaviour**

I expect the window size to be consistent across screens. The size stays the same when using Rectangle shortcuts for moving windows to another screen.

**Comment by rxhanson** [comment]
Thanks for reporting. Since nothing has changed Rectangle side for this, my guess is that this is Ventura behavior? I will test things out to confirm, but if that's the case then it's likely that this is something that Rectangle won't be able to properly adjust.

**Comment by argumemnon** [comment]
I came to report this issue too, as described. Here is a video of the issue. 


![issue1132](https://github.com/rxhanson/Rectangle/assets/22359397/a2e3a727-090f-4e04-8ee5-0e811f3e9276)

**Comment by rxhanson** [comment]
As a quick sanity check, does this happen when Rectangle is not running?

**Comment by argumemnon** [comment]
So, if you resize the window using Rectangle shortcuts, quit Rectangle, and move the window back and forth, yes, it still resizes itself on the other monitor, until you manually resize the window itself.

**Comment by rxhanson** [comment]
Thanks for the follow up. Unfortunately, this is outside of Rectangle and I don't have plans to build a workaround in Rectangle at this time. If the problem is more widespread and anyone is interested in creating a good workaround, then I would consider a good pull request.
