### ISSUE TITLE
Microsoft Defender classifies Rectangle as VLC Media Player for Mac

### ISSUE THREAD

**Issue by ClikeX** [rxhanson/Rectangle#1136]
macOS version: 13.3.1
Rectangle version: v.0.86 (74)

Not sure if this is an issue in the app, but Defender lists Rectangle as VLC Media Player for Mac. And is complaining that VLC is out of date because of it. 

I've also reported this to Microsoft, but I figured I also report it here.

**Comment by rxhanson** [comment]
Thanks for reporting. There's definitely nothing associating Rectangle with VLC, so that's something going on Microsoft side.

**Comment by ClikeX** [comment]
Thanks for checking. I obviously haven't received any feedback from Microsoft's end. I'll close this ticket as I'm sure it's a false flag at their end.
