### ISSUE TITLE
Any (Top Sixth) leave a 1px gap from the menu

### ISSUE THREAD

**Issue by popshuvitdude** [rxhanson/Rectangle#1138]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 13.3.1
Rectangle version: 0.68 (74)
Monitor resolution: 3440 x 1440
Gaps between windows are set to 0px

Any top Sixth leaves a 1px gap between window and menu only on my ultrawide 3440 x 1440 screen but does not happen on my built in 14" macbook pro screen.

![Screenshot 2023-04-24 at 10 12 35](https://user-images.githubusercontent.com/5197471/233960493-0f4ad0c4-41f4-4906-be0d-7196d15911d9.png)

**Comment by rxhanson** [comment]
Apologies for the much delayed response. I'm planning on addressing this in the next release.

**Comment by luizkowalski** [comment]
hello 👋🏻 
any update on this?

I'm still seeing the exact same issue

<img width="461" alt="image" src="https://github.com/rxhanson/Rectangle/assets/112706/2edff486-235f-49a5-8d19-c51843a17705">


I'm using Rectangle v0.75 on MacOS Sonoma 14.2.1

**Comment by rxhanson** [comment]
Hmm, I thought that I had put in a fix for it but perhaps it regressed. I'll take another look.

**Comment by rxhanson** [comment]
This is working properly for me. @hsvfan-jan Do you mind adding logs? Hold the option key in the menu bar menu and select "View Logging"

**Comment by hsvfan-jan** [comment]
@rxhanson I just now realize that this thread is about the "sixth" option, only.
The problem I encounter is that there's always a 1px gap. Usually, I only use maximize or right/left half the windows but the 1px gap persists even when I move around a window manually. Should I make a new issue for this or should we continue in this thread?

Here's the log
```
2024-11-23T14:34:43+01:00: AX sizing proposed: (1512.0, 944.0), result: (1410.0, 944.0)
2024-11-23T14:34:43+01:00: AX position proposed: (0.0, 38.0), result: (0.0, 38.0)
2024-11-23T14:34:43+01:00: AX sizing proposed: (1512.0, 944.0), result: (1512.0, 944.0)
2024-11-23T14:34:43+01:00: maximize | display: (0.0, 0.0, 1512.0, 944.0), calculatedRect: (0.0, 38.0, 1512.0, 944.0), resultRect: (-0.0, 38.0, 1512.0, 944.0), srcScreen: Built-in Retina Display, destScreen: Built-in Retina Display, resultScreen: Built-in Retina Display
2024-11-23T14:34:45+01:00: Unable to obtain the accessibility element with the specified attribute at mouse location
```

and here's a screenshot
<img width="419" alt="Screenshot 2024-11-23 at 14 37 50" src="https://github.com/user-attachments/assets/08e824eb-af33-4154-8343-58f96aafc025">

**Comment by rxhanson** [comment]
Let's make a new issue. I'm going to close out this sixths one, and if anyone still has the issue specifically with sixths then that can be continued here and reopened if necessary.

For the new issue, as a sanity check, do you see the 1px gap when you make a window full size by dragging the edges (not using Rectangle)?

**Comment by hsvfan-jan** [comment]
@rxhanson Never mind, it appears even when Rectangle is quit and seems to be a longstanding bug or nuisance https://www.reddit.com/r/MacOS/comments/wd47q6/why_is_there_like_a_pixel_of_separation_between/
