### ISSUE TITLE
Rectangle doesn't work with Chrome Version 80.0.3987.149 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by ataki** [rxhanson/Rectangle#115]
macOS version: 10.15.4 (Catalina)
Rectangle version: Version 0.24 (28)
Chrome version: Version 80.0.3987.149 (Official Build) (64-bit)

First, thanks for making Rectangle. I'm a Spectacle user that upgraded to Catalina and just moved over, and thought I'd make a contribution.

The issue I'm seeing is:
* Rectangle works on apps like Spotify, iTerm2, Safari, and other Mac Apps
* Rectangle does not work (not a single command works) for the cited version of Chrome. When I focus on my Chrome window and execute any resizing command via Rectangle, my Mac emits the "error noise" and nothing happens. No resizing.

Happy to dig into the code myself if you can point me in the right direction. Thanks!

**Comment by rxhanson** [comment]
Have you tried quitting Chrome entirely and restarting it? This worked for some people on this issue: https://github.com/rxhanson/Rectangle/issues/108

**Comment by ataki** [comment]
Ah ok, after restarting computer + Chrome twice, this finally started working. Thanks!

**Comment by rxhanson** [comment]
@ataki That's quite annoying, sorry you had to go through that. Thanks for reporting back! Let me know if it happens again.
