### ISSUE TITLE
Settings About Todo Mode not saved

### ISSUE THREAD

**Issue by LeonardoGentile** [rxhanson/Rectangle#1155]
Hello, 
I've set many times the setting "show todo mode in menu" and set the todo app as well several times.
Between restart of the app/mac/update these settings are not saved and I have to set them again. 
Also the ignored app seems not to be saved

**Comment by rxhanson** [comment]
Thanks for reporting. I can't reproduce this, but it might help if you can attach your prefs plist (you might have to zip it to paste it into the comment box here). Are you using any kind of syncing mechanism for the plist, like mackup?

`~/Library/Preferences/com.knollsoft.Rectangle.plist`

**Comment by LeonardoGentile** [comment]
Actually, it's more global. 
None of the settings and shortcuts are saved, anytime I quit the app or restart the mac then when App is restarted all my previous settings are reset to default ones. 

I suspect it has to do with [Mackup](https://github.com/lra/mackup), I use it to manage the settings of all my apps

**Comment by rxhanson** [comment]
Rectangle doesn't do anything unusual with the defaults. My recommendation is to isolate the issue by trying with/without mackup. I suspect this would be an issue on the mackup side, and by narrowing it down you can report it there.

**Comment by LeonardoGentile** [comment]
Thanks for your answer 👍

If other users don't have this problems then it's very likely it's a problem on Mackup side.
I suspect it's a mix of [this](https://github.com/lra/mackup/issues/1858) and [this](https://github.com/lra/mackup/issues/1890) issue.

I will investigate and update this issue with the results
