### ISSUE TITLE
unable to uninstall

### ISSUE THREAD

**Issue by anatolytkach** [rxhanson/Rectangle#1158]
macOS version: 13.3.1
Rectangle version: 68

I am trying to uninstall Rectangle because it doesn't work with my Firefox and Chrome.
After uninstalling, the Rectangle's functionality still remains in the system: any idea?
Is there any dedicated uninstaller tool to completely remove the app?

**Comment by rxhanson** [comment]
To uninstall Rectangle, drag it to the trash.

If it appears that it's still running after this, that typically means that you have another app running that does window management (there's no way for Rectangle to be running if you have deleted it).

**Comment by anatolytkach** [comment]
Got it, Rayn; thanks for your help.
I recently used to install Magnet but have deleted it, too: probably this one is giving me leftovers now.
BTW, do you have an idea why Rectangle may not work properly with my Firefox and Chrome?

**Comment by rxhanson** [comment]
Could be due to having two window managers running at the same time?

It’s pretty unusual to have issues with those, but you can show rectangle logging by holding the option key in the menu bar menu and selecting “View Logging “

**Comment by anatolytkach** [comment]
Strange: I don't currently have any of the window managers installed, but the behavior is as follows, and it looks totally like a Rectangle's behavior:
https://monosnap.com/file/bG5Hd91MoBNYZNuf0EV7UvaWbHbWTw
Any other ideas?

**Comment by rxhanson** [comment]
Looks like BetterTouchTool or BetterSnapTool. Rectangle's window footprint is gray.

**Comment by anatolytkach** [comment]
Oh, I see, I have checked all my apps, and the only one starting with "better" is the BetterMouse, which doesn't seem to have window management capabilities. As you know your market much better than I do, what other apps can cause this?

**Comment by rxhanson** [comment]
Window manager apps need accessibility privileges on macOS, so you can go through the list of apps you've given said privileges to in System Settings > Privacy & Security > Accessibility. Closing this one out since we're in the clear on it not being Rectangle.
