### ISSUE TITLE
Chrome window snapping stopped working after Chrome update to 114.0.5735.133

### ISSUE THREAD

**Issue by anjabeth** [rxhanson/Rectangle#1172]
macOS version: Ventura 13.4
Rectangle version: 0.69

Window snapping stopped working, but only for Chrome, after my Chrome updated yesterday. Snapping other windows (Finder, Terminal) still works, but Chrome doesn't work - it makes the Mac "boop, you clicked on something that doesn't do anything" noise. Chrome version 114.0.5735.133.

**Comment by rxhanson** [comment]
Thanks for reporting. Did you try restarting Chrome? Unfortunately, this isn’t something that would be fixed on the Rectangle side.

**Comment by anjabeth** [comment]
No luck with Chrome restart :/ I'll file a bug with Chrome.

**Comment by saadq** [comment]
I don't know if this is a Chrome issue because I'm facing a similar issue with every app. Whenever I try to use any of the commands for any app, I get the sound that you mentioned.

macOS version: Ventura 13.3 (Apple M2)
Rectangle version: v0.69 (75)

**Comment by anjabeth** [comment]
I noticed that when it made the "boop" sound it also highlighted the "tab" menu (between "profiles" and "window"). I tried adding a custom shortcut for Chrome "next tab", since it seemed like they might be conflicting. No luck there, but then I opened my Rectangle settings and recreated the shortcuts. Even though they're the exact same, it works now! IDK what went wrong but at least it's fixed.

**Comment by jbat** [comment]
This frustrated me for a quite a while ... until I found that the menu option for 
`Ignore Google Chrome` was checked :(

Unchecking it fixed the issue.
I have no recollection of checking it either.  So not sure what happed  there.

Also note that the menu item name may change depending on the current active Window I believe. 
It also appears as:
`Ignore Rectangle`

![Screenshot 2023-07-18 at 10 45 26 am](https://github.com/rxhanson/Rectangle/assets/5241772/73db7087-5bdc-4762-b487-b87ecce2230b)

**Comment by neelnanda-io** [comment]
I've started having the same issue on Chrome too, anyone find a fix for this?

**Comment by neelnanda-io** [comment]
Update: Closing and reopening Rectangle seems to have fixed it.
