### ISSUE TITLE
Is the path given for the preferences in README.md still correct? 

### ISSUE THREAD

**Issue by akoliyot** [rxhanson/Rectangle#119]
I found my preferences here: 
/Users/me/Library/Containers/com.knollsoft.RectangleLauncher/Container.plist

macOS version: 10.15.3 (19D76)
Rectangle version: 0.24

**Comment by akoliyot** [comment]
My bad, not sure why it's shown there for me, but I found original preference file in the old location. Closing this.

**Comment by rxhanson** [comment]
Right, the other plist that you found is the launcher plist for the launch on login capability. The launcher is essentially another application that is bundled inside the main application, and its sole responsibility is launching the app. My assumption is that secondary apps like this just have their plists organized in the Containers directory.
