### ISSUE TITLE
MacOS Admin - Enabling Rectangle on Start Up via command line?

### ISSUE THREAD

**Issue by havedill** [rxhanson/Rectangle#1215]
We install Rectangle using an MDM solution. I noticed by default it is set to not start on login. Is there an easy way to enable this remotely via bash or some other method?

**Comment by rxhanson** [comment]
Here is the terminal command to enable it:

```
defaults write com.knollsoft.Rectangle launchOnLogin -bool true
```

The setting will take effect the next time the app is launched (relaunch it if it's running).
