### ISSUE TITLE
Can't change sound output/input with rectangle running

### ISSUE THREAD

**Issue by corythorpe** [rxhanson/Rectangle#1228]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Ventura 13.5 (this issue began after I upgraded to 13.5, didn't exist in 13.4(?) or whichever version I was on before). This is using 16 inch 2019 macbook pro with intel silicon
Rectangle version: 0.70
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): No log output

Description: With rectangle open I am unable to change my sound output/input from the Sound options menu. If I select another sound source, the previous source automatically re-selects itself. Using the sound tray icon to change the sound source does work. Closing rectangle fixes this and allows me to select a different sound output/input source without the previously selected source automatically re-selecting itself.

**Comment by rxhanson** [comment]
Thanks for reporting. If you disable "Snap windows by dragging" in the snap areas tab, do you still experience this issue?

**Comment by decaplanet** [comment]
@rxhanson Yes, it works normally withou the option "Snap windows by dragging" enabled.

**Comment by decaplanet** [comment]
@rxhanson Yes, it works normally without the option "Snap windows by dragging" enabled.

**Comment by rxhanson** [comment]
@decaplanet Thanks, I'll see what I can do in the next release.

**Comment by rxhanson** [comment]
@patrezp sorry to hear that. I think something changed in macOS 13.5 that has led to this for some users. This issue is at the top of my priority list.

**Comment by decaplanet** [comment]
@patrezp Just found a workaround. It works okay for now, if you check "Ignore System Settings" in the Rectangle icon menu located in your menu bar. (Don't forget to have the setting app opened.) You could try this until it's updated.

**Comment by patrezp** [comment]
@decaplanet Thanks that works as a workaround! Just had to learn the key shortcuts cause I was using that drag and snap feature 😀

**Comment by oieduardorabelo** [comment]
Hey folks, I am sharing here as I'm affected by it too:

Macbook Air M2
Ventura 13.5.2 (22G91)

I can confirm both workarounds described above solved my problem:

1) Disable "Snap windows by dragging" = I can change sound output/input

2) Enable "Ignore System Settings" (with "Snap windows by dragging" enabled) = I can change sound output/input

thanks!

**Comment by rxhanson** [comment]
I think this was fixed by a subsequent version of macOS. Feel free to reopen if that's not the case.
