### ISSUE TITLE
Latest version breaks SwiftUI table selection

### ISSUE THREAD

**Issue by praveenperera** [rxhanson/Rectangle#1233]
Super weird issue but the latest version of Rectangle breaks selecting items in a table created by SwiftUI. See video below.

https://github.com/rxhanson/Rectangle/assets/1775346/1105ba34-bcc3-41c1-9288-953652400f76

See code: https://github.com/praveenperera/TableTest

**Comment by rxhanson** [comment]
Thanks for providing that sample project. This pre-existed the current version (0.70). The current version has an adjustment that disables snap windows by dragging for apps that are ignored, which was added for this scenario. 

I can't actually reproduce this issue, even with your sample project. What's likely happening here is that you have another app that's also listening to clicks, and there's a quirk in macOS that leads to this issue when there's too much processing of click events. Maybe try with no other apps running than Rectangle and see if it still persists? If that's not the case, then perhaps there is another macOS setting that's causing this?

**Comment by praveenperera** [comment]
Interesting yes I just tried on the older version and I see the same problem. I did recently upgrade to macOS 13.5, maybe that has something to do with it?

I tried quitting all other apps and running just Rectangle and I'm seeing the same issue. So weird, wonder what is interacting with Rectangle to cause this.

**Comment by rxhanson** [comment]
I'm guessing you're right that it is something to do with macOS 13.5, although I'm not sure why I can't reproduce it.

**Comment by byaruhaf** [comment]
Have the same issue, I can replicate it with your sample project

https://github.com/rxhanson/Rectangle/assets/4116539/df2c5a52-62b6-45b6-b9c9-109db84fbaa2

**Comment by rxhanson** [comment]
Do you still see this issue with the latest release?

**Comment by praveenperera** [comment]
@rxhanson yup still seeing it in the settings app and in my test app

**Comment by rxhanson** [comment]
@praveenperera I was on a different mac where I could reproduce the issue with v0.70, but it appears fixed for me in v0.71. Are you sure you could reproduce it in v0.71?

**Comment by byaruhaf** [comment]
v0.71 fixed it for me
