### ISSUE TITLE
Make minimum resizable width / height value to be configurable

### ISSUE THREAD

**Issue by kenvunz** [rxhanson/Rectangle#124]
It can be a simple `defaults write...` configuration type as I don't see it's a widely common need...

I can try doing it myself if you think it's a good addition and it's as straight forward as what you have done in [AlmostMaximizeCalculation.swift](https://github.com/rxhanson/Rectangle/blob/master/Rectangle/WindowCalculation/AlmostMaximizeCalculation.swift#L33)

Cheers,
👍

**Comment by rxhanson** [comment]
Absolutely. Looking forward to the pull request.
