### ISSUE TITLE
Config is not synced from ~/Library/Application Support/Rectangle/RectangleConfig.json

### ISSUE THREAD

**Issue by joeyorlando** [rxhanson/Rectangle#1246]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 14.0
Rectangle version: 0.70 (76)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

The documentation states:

> Upon launch, Rectangle will load a config file at `~/Library/Application Support/Rectangle/RectangleConfig.json` if it is present and will rename that file with a time/date stamp so that it isn't read on subsequent launches.

However, I've made some changes to the shortcuts, exported the `.json` config from Rectangle, symlinked it to `~/Library/Application Support/Rectangle/RectangleConfig.json` and then reloaded Rectangle. It appears that everytime I restart Rectangle it loses all of my config/preferences.

**Comment by rxhanson** [comment]
Thanks for reporting. Does it work if you copy the file instead of symlinking it?

**Comment by joeyorlando** [comment]
So I changed a few settings in the Preferences UI, exported the config file then tried the following:
```bash
cp RectangleConfig.json ~/Library/Application\\\ Support/Rectangle/RectangleConfig.json
```
but still no luck

**Comment by mr-narender** [comment]
+1 

I can confirm this behavior, config file is being renamed with datetime stamp. its very annoying to reload all config all the time.

BTW, I tried RectanglePro and that seems to be working fine.

**Comment by rxhanson** [comment]
The logic in Pro for this is identical. If it works there but not in Rectangle, do you have any other differences that might affect this?

**Comment by mr-narender** [comment]
@rxhanson not on top of my head, No. I just installed Pro, followed by set my config as I wanted then to be and restarted couple of time and it was still working.

Also, I just happen to uninstall (and delete any leftover configuration and settings along with) and then reinstalled Rectangle, and it seems to remember my setting.

@joeyorlando can you try this (if you haven't already).

anyways, I will keep a tap in case this changes, I will post an update.

**Comment by joeyorlando** [comment]
Still no luck after the following.
```bash
brew uninstall rectangle
brew install --cask rectangle
# open Rectangle, make a change to one of the keyboard shortcuts, confirm it works, close the application, reopen it and the keyboard shortcuts are reset
```

This is running Version 0.73 (79)

**Comment by joeyorlando** [comment]
interesting, it seems that uninstalling w/ the `--zap` flag and reinstalling fixes it 🤔 thanks for the tip @mr-narender

**Comment by mr-narender** [comment]
no problem :) , glad I could help @joeyorlando

**Comment by a0s** [comment]
@mr-narender very helpful hint about `--zap`, this should be in README.md !

**Comment by mr-narender** [comment]
Sure no problem @a0s :)
