### ISSUE TITLE
The application window cannot be restored after restarting the application

### ISSUE THREAD

**Issue by perst20** [rxhanson/Rectangle#1257]
- [X] This is a new bug that hasn't been documented in a closed issue or in the Readme.

Steps to reproduce: 
1. Open an application
2. Double-clicking on the title or snapping to the top edge maximizes and restores the window
3. When the window is in maximized state, close application (cmd+q), then reopen it
4. The window is in maximized state and can not be restored

macOS version: 13.5
Rectangle version: 0.70
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):

**Comment by rxhanson** [comment]
Thanks for reporting. I don't have immediate plans to address this issue, but see no reason to turn down a good pull request that does.
