### ISSUE TITLE
Conflict in result of similarly key bindings

### ISSUE THREAD

**Issue by kud** [rxhanson/Rectangle#126]
macOS version: macOS 10.15.4 (19E287)
Rectangle version: Version 0.25 (29)

Imagine you set like this:

![image](https://user-images.githubusercontent.com/655838/79749393-6de9ac00-830f-11ea-85bc-297df5d413fe.png)

Well, there `Left Half` and `Previous Display` will be in conflict. It makes hazardous the result.

**Comment by rxhanson** [comment]
Sorry, I don't understand. 

Are you saying that if you execute your shortcut for left half, then previous display is the result?

**Comment by kud** [comment]
As you can see in the screenshot Left Half and Previous Screen have the same binding, except that Previous Screen also got "ctrl".

So it works well when you do Left Half, but when you do Previous Screen, rectangle.app doesn't know what to do exactly and excecute left half and previous screen in the same time.

**Comment by rxhanson** [comment]
Are you sure that you don't have any other window manager applications running in addition to Rectangle?

**Comment by kud** [comment]
Like for instance Spectacle.app because I read it was unmaintained anymore, that's why I switched to rectangle.app, start rectangle.app and forgot to quit/remove Spectacle.app? Yep, exactly. 😬

Hahaha, I'm so sorry for this useless issue.

**Comment by rxhanson** [comment]
No worries, it's on my TODO to add a small bit of code that alerts a user if Spectacle or other window managers are running (you're not the first).
