### ISSUE TITLE
Add link to Rectangle website in 'About' window

### ISSUE THREAD

**Issue by alexandreleroux** [rxhanson/Rectangle#128]
Thanks for this wonderful tool.

There is currently no link to the [Rectangle website](https://rectangleapp.com) either in the `About` window or the `Preferences` window. What about adding such a link in the `About` window? Thanks!

**Comment by rxhanson** [comment]
Hey, thanks for the feedback. I typically do the laziest thing possible when it comes to about windows - I use the default Apple provided one. I haven't looked into if it's possible to customize it or not. Regardless, this is kinda low on my priority list and I don't think I'll get around to it, so I'm going to close it out. If anyone else wants to take a stab at it, I don't see why I would reject a PR for it.
