### ISSUE TITLE
0.74 does not load in macOS 10.13.6

### ISSUE THREAD

**Issue by yihaolee85** [rxhanson/Rectangle#1284]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 10.13.6
Rectangle version: 0.74
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

After updating from 0.73 to 0.74, the app does not start up. Reverting to 0.73 the app is able to load successfully. Unable to share log as 0.74 is not loading, happy to follow up with a log if someone can share with me where to grab them.

**Comment by rxhanson** [comment]
Thanks for reporting. Unfortunately, this likely will mean that 0.73 is the last version that will support macOS < 10.15.

Nearly all of the more recent updates to Rectangle have been adjustments around more modern macOS functionality, and probably the past 10 releases would be nearly identical in terms of functionality if you're still on macOS 10.13. On top of that, a distinct benefit of targeting macOS 10.15 is a much smaller file size for the app.

**Comment by yihaolee85** [comment]
> Same here FWIW.

I reverted to using 0.73 without allowing it to update.

**Comment by AlisterH** [comment]
Yes, thanks.  I just wanted to confirm that 0.74 doesn't work and 0.73 does - it isn't something special about your machine.

**Comment by rxhanson** [comment]
The result here was that macOS 10.13.6 (and 10.14) support was capped at v0.73.
https://github.com/rxhanson/Rectangle/releases/tag/v0.73.
