### ISSUE TITLE
When zooming out to the current program's minimum window size, continue using shortcut keys to zoom out. The foreground program window will be offset.

### ISSUE THREAD

**Issue by DevLiuSir** [rxhanson/Rectangle#1292]
When zooming out to the current program's minimum window size, continue using shortcut keys to zoom out. The foreground program window will be offset. It can be considered that after shrinking to the original size of the foreground program, further shrinking is prohibited.

**Comment by rxhanson** [comment]
Thanks for reporting. I can't reproduce this so I suspect it might be on specific applications? Which applications are you experiencing this with? If you don't mind, can you attach logs and/or a screen recording for when this happens?

Hold the option key in the menu bar menu and select View Logging...

**Comment by DevLiuSir** [comment]
0.75 will not appear anymore. great!
