### ISSUE TITLE
Rectangle doesnt work on Macos Sonoma

### ISSUE THREAD

**Issue by XComputerDavidX** [rxhanson/Rectangle#1294]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Sonoma

I downloaded rectangle just today, I was all smooth until I restarted my Macbook because the RAM was running high and I want to clear it in this way. But after the restart, the application will still launch but I can not use the "Snap windows by dragging" feature, it still won't work after a few dozen of restarts.
What is interesting is that it will work for a few times just after restart, but after a min, it stops working.
Is someone experiencing the same issue like me?

**Comment by rxhanson** [comment]
Thanks for reporting. As a sanity check, do you have another window manager that might have launched on login upon restart?

Are there any logs? Hold the option key in the menu bar menu and select View Logging...

**Comment by XComputerDavidX** [comment]
> Thanks for reporting. As a sanity check, do you have another window manager that might have launched on login upon restart?
> 
> Are there any logs? Hold the option key in the menu bar menu and select View Logging...

No there aren't any windows manager that I installed
Here is the logging result
2023-11-29T09:04:50Z: Unable to obtain the accessibility element with the specified attribute at mouse location

**Comment by XComputerDavidX** [comment]
I have tried to uninstall and reinstall with accessability on and off, even restarted a few times but still doesn't work

**Comment by martinpilch** [comment]
I'm wondering, is it broken for all apps (e.g. Finder) or only some of them (e.g. Adobe Acrobat Reader)?

**Comment by XComputerDavidX** [comment]
> I'm wondering, is it broken for all apps (e.g. Finder) or only some of them (e.g. Adobe Acrobat Reader)?

It is all not working for some reason, and I am pretty sure I gave all the accessibility power to rectangle

**Comment by rxhanson** [comment]
At the root of this is the Accessibility API that Rectangle relies on for obtaining and setting window sizes/positions. This is typically seen only with specific apps (typically Chrome/Electron based), and is often resolved by restarting the app that it's not working on. You can try quitting Rectangle then resetting the accessibility permissions for Rectangle using this command:
`tccutil reset All com.knollsoft.Rectangle`

Unfortunately, this type of scenario tends to be an issue on the macOS side, and there isn't anything else I can do in Rectangle to work around it.

**Comment by XComputerDavidX** [comment]
Thank you so much, I tried your method and it worked again, hope every developer is just like you who is always there for help

**Comment by rxhanson** [comment]
@raiden-e Sometimes after a macOS update, you have to restart your Mac one more time for the accessibility API to work properly with 3rd party apps. 

Which of these still don't work for you? keyboard shortcuts, menu bar menu items, or drag to screen edge snapping

**Comment by raiden-e** [comment]
@rxhanson Done. For some reason, the snapping doesn't work for any of my windows. Keyboard shortcuts and the rest are fine. Snapping is enabled in the settings.

**Comment by rxhanson** [comment]
@raiden-e, you can try this terminal command to adjust how Rectangle obtains clicks:

defaults write com.knollsoft.Rectangle systemWideMouseDown -int 1

Then restart the app.

If that doesn't change anything, then we're looking at something external to Rectangle potentially causing issues.

**Comment by raiden-e** [comment]
Well, I just did the 0.75 update, and now it magically works. Was that maybe the problem?

**Comment by raiden-e** [comment]
That seemed to work. But it seems to be abnormal. Does this indicate anything about my computer? (Im new to mac)

**Comment by rxhanson** [comment]
@raiden-e, I don't know what would cause this for you. There are different ways to figure out which window is under the cursor, and that Terminal command enables the way that Rectangle used to do it, which was fine for many years. The problem with that way is that it can cause issues with clicks not registering properly in certain apps in macOS Sonoma, but odds are that you won't have that happen.

**Comment by DarwinJS** [comment]
I'm having a problem on after upgrading to Sonoma as well. Seems to only affect custom window sizes. Whether I try to use the menu or a hotkey, it just makes an error sound when I try to use a custom resize. Accessibility and screen recording are enabled. Rectangle Pro was installed before I upgraded to Sonoma

**Comment by raiden-e** [comment]
If I wanted to revert this, can I just set
`defaults write com.knollsoft.Rectangle systemWideMouseDown -int 0`?

**Comment by rxhanson** [comment]
Yes, or `defaults delete com.knollsoft.Rectangle systemWideMouseDown`

**Comment by otaciliolacerda** [comment]
> @raiden-e Sometimes after a macOS update, you have to restart your Mac one more time for the accessibility API to work properly with 3rd party apps.
> 
> Which of these still don't work for you? keyboard shortcuts, menu bar menu items, or drag to screen edge snapping

Thank you. Nothing was working but after a restart it solved for me.

**Comment by DarwinJS** [comment]
> I'm having a problem on after upgrading to Sonoma as well. Seems to only affect custom window sizes. Whether I try to use the menu or a hotkey, it just makes an error sound when I try to use a custom resize. Accessibility and screen recording are enabled. Rectangle Pro was installed before I upgraded to Sonoma

Ok I was wrong. I also had changed monitors to a slightly smaller resolution and when an older rectangle custom size & position settings asks for an "impossible" setting on the current monitors, it just appears to do nothing.

It would be very helpful if it put up a message that the settings are not possible on the monitor.

**Comment by eolaris** [comment]
`defaults write com.knollsoft.Hookshot systemWideMouseDown -int 1`

https://github.com/rxhanson/RectanglePro-Community/issues/393#issuecomment-1944258761

This solved it for me, no other combination of commands, resets and reinstalls.

**Comment by guycalledseven** [comment]
> `defaults write com.knollsoft.Hookshot systemWideMouseDown -int 1`
> 
> [rxhanson/RectanglePro-Community#393 (comment)](https://github.com/rxhanson/RectanglePro-Community/issues/393#issuecomment-1944258761)
> 
> This solved it for me, no other combination of commands, resets and reinstalls.

This solved it for me once, but now it it started not responding again and this does not help. 
I can however move Rectangle's own window with defined shortcut keys. 
Running macOS 14.4.1 (23E224).

**Comment by rxhanson** [comment]
@guycalledseven Try the following

1. Quit Rectangle
2. Execute this Terminal command: 
tccutil reset All com.knollsoft.Rectangle
3. Restart your Mac.
4. Launch Rectangle and give it accessibility permissions again.

**Comment by guycalledseven** [comment]
@rxhanson thanks, restart fixed it.  👌

**Comment by spidey** [comment]
I usually keep the menu bar icon hidden, but I've restored it so I could quit the application and then I noticed that for the apps that it wasn't working all the window position/size shortcuts were disabled. For me it was for the Terminal, Firefox and Mattermost apps. On the Calendar app it worked fine and the shortcut buttons were available.

I then simply chose Quit on the dropdown and restarted the app from Spotlight and these 3 apps started working with Rectangle back again.

So before trying the tips about resetting settings, simply try restarting the app (the app, not Mac OS, as it keeps/reopens apps restoring their memory for you and skips initialization code, I guess) first.

**Comment by MrKovar** [comment]
For debugging purposes, I noticed a very specific set of circumstances that causes this for me. If I'm using it either attached to my thunderbolt dock or not and then swap to the other case and then try to run a non-default binding everything will break.

I will them open rectangle from the menu bar to check the config which says it is working as intended, but on restart it shows that the config has reset. You can also verify this by exporting the config before restarting showing that the config is broken but the UI has not updated to reflect it has reset all of your bindings.

This is reproducible on my machine 100% of the time - Sonoma 14.5

**Comment by rxhanson** [comment]
Closing this one out to make sure new issues are created where needed.

@MrKovar can you create a new issue for what you're experiencing? I'm not entirely sure I understand where things are going wrong - would you mind providing a screen recording?

**Comment by georgms** [comment]
> @guycalledseven Did you try the following?
> 
> 1. Quit Rectangle
> 2. Execute this Terminal command:
>    `tccutil reset All com.knollsoft.Rectangle`
> 3. Restart your Mac.
> 4. Launch Rectangle and give it accessibility permissions again.

Step 3., Restart your Mac was crucial for me and fixed Rectangle.

**Comment by JesseObrien** [comment]
> Might seem like a stupid fix, but the only thing that worked for me (macOS Sonoma 14.7.2) was to manually delete and rebind all commands to the same key binds they had by default. Hopefully that works for some of you as well!

This was my fix as well. I needed to re-bind everything to make any of them work.

Running `Version 0.86 (92)`. I tried the `tccutil` resets, tried restarting, tried the accessibility changes, tried everything else. Re-binding the keys worked.

**Comment by Alaricus** [comment]
> [@guycalledseven](https://github.com/guycalledseven) Did you try the following?
> 
> 1. Quit Rectangle
> 2. Execute this Terminal command:
>    `tccutil reset All com.knollsoft.Rectangle`
> 3. Restart your Mac.
> 4. Launch Rectangle and give it accessibility permissions again.

Years after the original post this happened to me, and the above solution worked! Thanks!
