### ISSUE TITLE
Cursor Moves Itself to Center of Screen

### ISSUE THREAD

**Issue by RickyBubbles** [rxhanson/Rectangle#1295]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 10.14.1.1
Rectangle version: 0.74

Every so often my cursor moves in a "jerky"  or "step-like" fashion to the center of the screen and stays there.
Rectangle is my only app with accessibility privileges that could potentially do this.

**Comment by rxhanson** [comment]
Thanks for reporting. This is the first I've heard of this one. If you don't mind, can you export your config and attach it here? I don't have a Mac on 10.14 anymore, but maybe your config can help narrow it down.
