### ISSUE TITLE
Support for "next third"

### ISSUE THREAD

**Issue by daxmc99** [rxhanson/Rectangle#13]
Hello! 
Thanks for working on this project!
One feature that I miss from Spectacle is the "Next Third" option. 
I would love to see that in the next release. 

I'm new to swift but I will see if I can't figure out how to port this over.

**Comment by rxhanson** [comment]
@daxmc99 @drpebcak , this functionality is now included in https://github.com/rxhanson/Rectangle/releases/tag/v0.9. 

It's actually just built in to the first third and last third actions. So, if you repeatedly execute first third, it will cycle through thirds (first, center, last). If you repeatedly execute last third, it will cycle through thirds in reverse order (last, center, first).

**Comment by goldcaddy77** [comment]
Finding this years later... nice compromise, works great!
