### ISSUE TITLE
hope to be able to continue using the drag-and-snap

### ISSUE THREAD

**Issue by hnynf** [rxhanson/Rectangle#1304]
When I ignore a certain software, I still hope to be able to continue using the drag-and-snap window functionality. After installing the latest version, I lost this feature.

tks~

**Comment by rxhanson** [comment]
You can get back to how it was done prior to v0.70 with the following Terminal command:

`defaults write com.knollsoft.Rectangle ignoreDragSnapToo -int 2`

Then restart the app.
