### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by iSkore** [rxhanson/Rectangle#131]
If you enabled sponsorship on this repo, I would contribute. I purchased an exact version of this application on the Mac App store (Magnet) years ago for $1. This app performs equally well if not better **and** is open source. Thank you!

**Comment by rxhanson** [comment]
Thanks! This was the reminder I needed to finally finish filling out my profile and tiers. Looks like it's up to 2 weeks until GitHub completes their review of it.

**Comment by iSkore** [comment]
Glad I could be the reminder! I'll check back in 2-3 weeks!
Thank you for making and maintaining this!
