### ISSUE TITLE
When setting up a shortcut, why can't you use option + 1 letter key? You can use option plus multiple key combinations.

### ISSUE THREAD

**Issue by DevLiuSir** [rxhanson/Rectangle#1315]
When setting up a shortcut, why can't you use option + 1 letter key? You can use option plus multiple key combinations.

**Comment by rxhanson** [comment]
In the gear tab of the prefs window, you'll want to check the box for "Allow any shortcut". This boils down to a convention with the shortcut recorder used in Rectangle, and I need to change it so this is enabled by default and/or there's explanation in the app for this.

**Comment by DevLiuSir** [comment]
> In the gear tab of the prefs window, you'll want to check the box for "Allow any shortcut". This boils down to a convention with the shortcut recorder used in Rectangle, and I need to change it so this is enabled by default and/or there's explanation in the app for this.

It worked. Thank you
