### ISSUE TITLE
maximise default controls

### ISSUE THREAD

**Issue by yujietan** [rxhanson/Rectangle#1320]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: macos ventura
Rectangle version: 0.75
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

Hi i have two devices with rectangle installed on them. One of their controls to maximise is
opt-shift-f but my other controls on the other device is opt-shift-enter. Im more familiar with the former sO how do i get the former set of control on both devices?

**Comment by rxhanson** [comment]
If you go to the gear tab in the settings, there's a button for Restoring Default Shortcuts & Snap Areas, and you can select the Spectacle shortcuts if you want the shortcut set that uses cmd+alt+f for maximize. Or you could just edit that one keyboard shortcut if that's the only one you want changed.

**Comment by yujietan** [comment]
this works thank you
