### ISSUE TITLE
Sonoma causing mouse cursor issues

### ISSUE THREAD

**Issue by le0n** [rxhanson/Rectangle#1322]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 14.2.1 (23C71)
Rectangle version: Version 0.75 (81)

Only start noticing this after upgrading to Sonoma. Intermittently, the cursor will be stuck on whatever it was previously (pointer, text cursor or hand for hyperlink), and stop changing when for example hovering over text or hyperlink. It's almost like the current window loses focus, and the only way to regain focus and cursor change is to click on another window / desktop and then reclick the window.

This may be a native bug with Sonoma, but I've noticed the bug disappears after quitting rectangle. See this reddit post for a video of the issue:
https://www.reddit.com/r/MacOS/comments/17p415c/macos_sonoma_mouse_hover_bug_most_annoying_update/

**Comment by rxhanson** [comment]
Thanks for reporting. From my perspective, this is unrelated to Rectangle, and it's coincidental that this would be affected by quitting Rectangle. There is nothing within Rectangle that operates on cursor movement, and nothing that affects cursor icons.
