### ISSUE TITLE
Overlapping of the thirds 

### ISSUE THREAD

**Issue by RedFish87** [rxhanson/Rectangle#1339]
Hi, when I resize windows into thirds, there is always a slight (∼2 mm) overlap of the neighbouring windows. 

I am aware this may be caused by the minimal size of windows on my MacBook Air. 

Is there a way to fix this, though?

Thank you,

Lukas

- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Sonoma 14.3.1 (23D60)
Rectangle version: Version 0.76 (82)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):

**Comment by RedFish87** [comment]
I think it’s resolved itself after a restart.

**Comment by rxhanson** [comment]
Rectangle has no way to resize a window smaller than its minimum width, unfortunately. I've considered adding some visual feedback to communicate this, but found it rather annoying. With that in mind, I'm open to other ideas on how this could be improved.
