### ISSUE TITLE
"A" keeps being appended to keyboard shortcuts with the click of a modifier key

### ISSUE THREAD

**Issue by Keysz** [rxhanson/Rectangle#1342]
Whenever I try to add a shortcut with any modifier key to Rectangle, it keeps automatically appending "A". 

For instance, to record shortcut for first fourth = I tap ctrl (^) and it records ctrl+A. It does the same thing with option (opt+A) and command (cmd+A). The rest of the keys are fine, just the modifier keys. I looked into system settings and confirmed the modifier keys were not being altered in any way. I confirmed the same conclusion when I used keycastr. I am pressing ctrl and no other key is being appended.

macOS version: 14.2.1 Sonoma
Rectangle version: 3.0.19

**Comment by rxhanson** [comment]
Thanks for reporting. Since this is the first time this has been reported, I'm thinking that something is unique with your setup. Do you have anything unusual about your keyboard or any software that might make any keyboard adjustments? Maybe a silly question, but do you have a second keyboard somewhere that might have the A key pressed, like in a backpack?

**Comment by Keysz** [comment]
It's a reasonable question. I double-checked everything but nothing can explain it. I have a Nuphy keyboard working on a PC and attached to Synergy via Mac, but there are no modifications to the keys. I double-checked on both systems. I'm at a loss as to why the modifier key is automatically appending an A.

**Comment by rxhanson** [comment]
Sorry for the delayed response. As another sanity check, did you try recording a shortcut in macOS, in System Settings -> Keyboard Shortcuts? That way we can narrow down if it's something specific to Rectangle or not. (Or you could try other apps with shortcut recorders and see what happens).

**Comment by rxhanson** [comment]
Housekeeping, closing this one out, but feel free to comment or reopen if there are any updates.
