### ISSUE TITLE
Rectangle's snap to make full screen feature doesn't make the window truly full screen (a bit of the window behind it is still visible)

### ISSUE THREAD

**Issue by ComfortableMilk4454** [rxhanson/Rectangle#1350]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 14.4.1 (23E224)
Rectangle version: 0.76 (82)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): nothing in the log window

Hi! I have been having this issue since I started using rectangle in July 2023, where when using rectangle’s snap to make an app full-screen its not true full screen as you can see a little sliver of the window behind it, unlike when you use macOS's built in way of making a window full screen (by holding down option + clicking green skittle). See the screenshots below so you can see what I'm talking about. I'm assuming this is just a bug and I hope it can be fixed! Thanks so much in advance for any and all responses! 

using rectangle’s snap:
<img width="1512" alt="Pasted Graphic" src="https://github.com/rxhanson/Rectangle/assets/43555540/5fbf9252-eb68-45c8-90e0-261357844de6">
as you can see, there's a bit of the window behind it showing here

option + clicking green skittle (macOS snap):
<img width="1512" alt="Pasted Graphic 1" src="https://github.com/rxhanson/Rectangle/assets/43555540/9f38445e-1faa-497d-b5a7-a3c422dd2cb2">
as you can see, there is none of the window behind it showing here

**Comment by rxhanson** [comment]
Thanks for reporting. This is a discrepancy on the macOS side, unfortunately. Rectangle uses the Accessibility API to understand the proper size to make the window, and to apply that size. It might be possible to workaround this by adjusting the value here by a pixel. I don't quite have the bandwidth to test that out at the moment, but will add it to my backlog. I see no reason to turn down a good pull request if someone gets to it before me.

**Comment by Aaron-Rumpler** [comment]
You get the same issue if you try to manually resize the window as well. macOS won't let you resize the window all the way down to the top of the dock (the size that macOS allows you do to manually is the same as what Rectangle gets you), but using macOS "zoom" does. Also, if you position the window below the dock and then resize up from the top of the window, that also positions the bottom of the window directly above the dock (without the gap).

**Comment by ComfortableMilk4454** [comment]
does this issue persist with the Automatically hide and show the dock function turned on?

**Comment by Aaron-Rumpler** [comment]
Nope. With dock hiding enabled, Rectangle maximise, macOS Zoom, and manual resizing all resize the window all the way to the bottom of the screen.

**Comment by rxhanson** [comment]
Good point on the resizing, @Aaron-Rumpler. Unfortunately, I don't think it would be possible to fix this via Rectangle then.
