### ISSUE TITLE
Rectangle doesn't start (crashes?) on Sonoma 14.4.1

### ISSUE THREAD

**Issue by dimaslivin-ct** [rxhanson/Rectangle#1355]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Sonoma 14.4.1
Rectangle version: 0.79
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

After launching the app the Rectangle icon shows up for a fraction of a second in the menu bar and then goes away. Stopped working right after applying the Sonoma 14.4.1 update. Before that there were no issues launching and running Rectangle.

**Comment by rxhanson** [comment]
There should be a crash report in the Console app for Rectangle. Please attach that here.

**Comment by dimaslivin-ct** [comment]
There are no crash reports unfortunately. Nothing related to Rectangle anywhere.

**Comment by rxhanson** [comment]
Thanks for the update. This is an unusual scenario. Next, try deleting the preferences with this Terminal command.

```
defaults delete com.knollsoft.Rectangle
```

Then try launching the app again.

**Comment by dimaslivin-ct** [comment]
Still the same behavior after deleting the preferences. No crash report either.

**Comment by rxhanson** [comment]
I think this might be an Accessibility permissions bug. Try these steps to reset the Accessibility permissions.

1. Quit Rectangle
2. execute this command
tccutil reset All com.knollsoft.Rectangle
3. Restart your Mac
4. Launch Rectangle again and give it Accessibility permissions again.

The restart step could be unnecessary, but sometimes there can be some macOS quirks with Accessibility permissions right after an update, and its best to restart your Mac one more time after the update.

**Comment by dimaslivin-ct** [comment]
This was indeed an accessibility permission issue. After reassigning the permissions it all works again. You have my huge thanks.

P.S. That 14.4.1 update broke a lot of things here. Logitech options + for example.

**Comment by cagostino** [comment]
@rxhanson your suggestion fixed my issue here too. thanks for sharing.
