### ISSUE TITLE
padding for stage area should be in right side of the screen instead of left side for devices with RTL language(for example: Arabic)

### ISSUE THREAD

**Issue by asaah18** [rxhanson/Rectangle#1358]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 14.4.1
Rectangle version: 0.76

**Comment by rxhanson** [comment]
Thanks for reporting. I wasn't aware of this and will aim for a fix in the next release.

**Comment by rxhanson** [comment]
This should now be fixed in v0.77. 

https://github.com/rxhanson/Rectangle/releases/tag/v0.77
