### ISSUE TITLE
macOS calendar app height overlapping other applications.

### ISSUE THREAD

**Issue by rosscondie** [rxhanson/Rectangle#1360]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme. 

macOS version: Sonoma 14.4.1
Rectangle version: 0.76 (82)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):  No logs available.

I hope this is the right place for this apologies if it is not I couldn't find a previous issue and i've tried the troubleshooting section in the README. I've attached a screenshot here, currently using a MacBook Pro 13" 2020. 

![Screenshot 2024-04-09 at 11 23 03](https://github.com/rxhanson/Rectangle/assets/121060540/6d54c5d2-92a1-4552-9bb9-ca139ab17c29)

I use rectangle on my work laptop and don't have the same issue which is a 16" Macbook Pro. 

Currently experiencing that the height of the calendar app when snapped to the corners overlaps the other applications. This is also the case with the Discord app. 

Is it just the case that some apps can't be resized on certain displays?

**Comment by Aaron-Rumpler** [comment]
Are you able to manually resize the window to be shorter? If not, then it's just that Calendar can't be resized to be any shorter (i.e. it has a minimum height).
