### ISSUE TITLE
Move windows to different (work)spaces

### ISSUE THREAD

**Issue by giallu** [rxhanson/Rectangle#137]
I am coming from the Linux world and Rectangle helped me adding back most of my windows positioning shortcuts.
Using multiple desktops was my primary mean for keeping related work windows open and apparently OSX implements what they call Spaces[1]. However, moving windows to other spaces is sorely missing from the list of available actions; is there any chance you could add it? For the record, I found another app that does this [2] so I guess there is some OS support for adding a shortcut even though Apple didn't create one.

[1] https://support.apple.com/en-in/guide/mac-help/mh14112/mac
[2] http://www.irradiatedsoftware.com/sizeup/

**Comment by rxhanson** [comment]
https://github.com/rxhanson/Rectangle/issues/85
https://github.com/rxhanson/Rectangle/issues/16
https://github.com/rxhanson/Rectangle/issues/55#issuecomment-569494511

In short, Apple doesn't provide public APIs for spaces. If at some point they do, I'll be glad to to revisit this.

Did you try out SizeUp? Moving to different spaces with SizeUp didn't work last time I tried it.

Feel free to fork Rectangle and give it a go :)

**Comment by giallu** [comment]
Thanks for your time Ryan. I didn't try SizeUp but I got the idea it works from their homepage:
<img width="406" alt="Screen Shot 2020-04-27 at 15 37 45" src="https://user-images.githubusercontent.com/6527/80378643-3f367d00-889d-11ea-9909-bb4167272b08.png">
I am not sure if they are using an undocumented API though.
