### ISSUE TITLE
restore keyboard shortcut not working

### ISSUE THREAD

**Issue by kamranarshad** [rxhanson/Rectangle#1372]
When I try to restore the window for any application. There is a flickering of the application and sometimes not, but it would not restore to the last point. This only happens when using the keyboard shortcut but not when using from rectangle menu.

I have copied my rectangle pro config from my work MacBook and it still does the same, but works correct on my work MacBook.

macOS version: 14.4.1 (23E224)
Rectangle version: 3.0.24 (165)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

2024-04-27T02:11:57+01:00: AX sizing proposed: (1447.0, 993.0), result: (1447.0, 993.0)
2024-04-27T02:11:57+01:00: AX position proposed: (1200.0, 568.0), result: (1200.0, 568.0)
2024-04-27T02:11:57+01:00: AX sizing proposed: (1447.0, 993.0), result: (1447.0, 993.0)
2024-04-27T02:11:57+01:00: AX sizing proposed: (1447.0, 993.0), result: (1447.0, 993.0)
2024-04-27T02:11:57+01:00: AX position proposed: (1200.0, 568.0), result: (1200.0, 568.0)
2024-04-27T02:11:57+01:00: AX sizing proposed: (1447.0, 993.0), result: (1447.0, 993.0)

**Comment by rxhanson** [comment]
Thanks for reporting. I can't reproduce this. Perhaps there is a misunderstanding of which point Rectangle is restoring to? This might be something I won't understand from logs alone - would you mind creating a screen recording of it working properly using the menu but not working using keyboard shortcuts?

**Comment by kamranarshad** [comment]
@rxhanson Here is the screen recording you had asked and in the bottom left corner you can see the keystroke I am pressing. 

https://github.com/rxhanson/Rectangle/assets/4786013/2834b5ad-5986-4a0e-afbf-e1a8e01b2d96

**Comment by rxhanson** [comment]
Thanks! Can you confirm that you have no other window managers running in the background? With it narrowed down to the keyboard shortcut being the issue, this is the most likely cause of the issue.

**Comment by kamranarshad** [comment]
I don't have another windows manager installed, but I have just checked Raycast and it did have a shortcut for that keybinding. 

I have removed they keybinding in Raycast and seem to working now correct now.
