### ISSUE TITLE
Version 77 does not resize/move web browsers safari, firefox, or chrome

### ISSUE THREAD

**Issue by cruzmanny** [rxhanson/Rectangle#1374]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 14.4.1 (23E224)
Rectangle version: 77
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):  I currently do not have the logs for version 77 because I am submitting this bug report after downgrading to version 76. After downgrading I am able to move and resize web browsers.

**Comment by rxhanson** [comment]
Thanks for reporting. There were no changes that would affect browsers in v0.77. I'm thinking that maybe just restarting Rectangle after the update would get things back on track.

**Comment by cruzmanny** [comment]
After all the troubleshooting and 15 years in tech support the only thing I did not try was turning it off and turning it on again. Thank you.
