### ISSUE TITLE
2/3rd sizing is off

### ISSUE THREAD

**Issue by angus-lau** [rxhanson/Rectangle#1377]
macOS version:  Sonoma 14.2.1
Rectangle version: 0.77

2/3rds screen size on one application and using 1/3 on a different application causes an overlap between the two programs

**Comment by Aaron-Rumpler** [comment]
This will be because one of the applications you're snapping won't allow you to resize it any smaller (i.e. the 1/3 or 2/3 size is smaller than the minimum window size). You can confirm this by trying to manually resize it smaller.
