### ISSUE TITLE
Unable to map Command-Option-Control-Shift-Q

### ISSUE THREAD

**Issue by mdbraber** [rxhanson/Rectangle#138]
macOS version: 10.15.4
Rectangle version: 0.26 (31)

I'm trying to map Command-Option-Control-Shift-Q to one of the actions, but it's not allowing it. I've switched on "Allow any keyboard shortcut", but no dice. Most other shortcuts work, but e.g. Command-Option-Control-Shift-. also doesn't seem to be allowed. I am able to map it e.g. in Keyboard Maestro. There are no other programs that define Command-Option-Control-Shift-Q as far as I know (tried checking with Shortcut Detective).

Any idea what could be causing this?

**Comment by rxhanson** [comment]
I cannot map `Command-Option-Control-Shift-Q` either, but I can map `Command-Option-Control-Shift-.`

I've had some other users report certain shortcuts not being recorded on my other window manager (Hookshot), which uses the same recorder. In all these cases, there are some discrepancies between what they can record and what I can record - which probably means that it is something device specific. By checking the allow any shortcut box, it means that MASShortcut won't search through the application's menu items, and the globally defined ones in System Prefs before allowing it to be recorded. I'm guessing that there might be a bug where MASShortcut is checking against shortcuts that it thinks have already been recorded by another MASShortcut in the app, as that's the main case where you'll see a shortcut not get recorded and no warning messages displayed.

So, in terms of a path forward on this - it would be of the most help to try out MASShortcut's sample app and see if you can reproduce it there. If so, then it would at least be hopefully more straightforward to solve in MASShortcut. If it works in MASShortcut's sample app, then I think my hunch might be true about there being a bug in having multiple MASShortcut instances and it thinks one is conflicting even when it's not. Maybe it's something worth filing an issue on MASShortcut either way?

**Comment by mdbraber** [comment]
Thanks for the pointers, I'll look into it and close this for now.

**Comment by martzell** [comment]
Cannot map ⌃⌥⇧⌘Q as shortcut. Does also not work with [MASShortcutDemo](https://github.com/shpakovski/MASShortcutDemo). MacBook Pro 15" 2015.
