### ISSUE TITLE
1/6th size calculation for window is one pixel off for the right hand edge

### ISSUE THREAD

**Issue by web3d0** [rxhanson/Rectangle#1382]
- [*] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.7.4
Rectangle version: 0.77 (83)

When selecting 1/4th on the right hand side, the scroll bar is positioned so I can just go to the right edge.

When selecting 1/6th on the right hand side, the window is one pixel to the left and scroll does not work at the edge.

**Comment by web3d0** [comment]
I just tested it, the window is able to resize smaller, and in fact needs to be one pixel larger. I suspect the problem is that my screen resolution is 2560 across, and the calculation is 2560 / 3 = 853 pixels, whereas for the scroll bar to be at the right hand edge, it needs to be 854 pixels.

**Comment by rxhanson** [comment]
That makes sense, thanks for the follow up. I'll slate this one for the next release, then.

**Comment by rxhanson** [comment]
This one should have been fixed in v0.80, let me know if that's not the case.

**Comment by web3d0** [comment]
Yep, fixed.
