### ISSUE TITLE
"Make smaller" sets window as full height when gaps are on

### ISSUE THREAD

**Issue by metalelf0** [rxhanson/Rectangle#139]
macOS version: 10.15.3
Rectangle version: 0.26

Hi, since version 0.26 I'm seeing an unexpected behavior for the "make smaller" command (ctrl-alt-minus). When gaps are enabled, every time I try to make a window smaller, it is automatically made full-height. On version 0.25 both height and width of the window were correctly reduced.

I'm using Rectangle on an external hi-dpi monitor, set as 3008x1692. Let me know if I can provide any further info.

Thanks and keep up the great work!

**Comment by rxhanson** [comment]
Thanks for reporting! This was a side effect of aligning some of the gaps behavior with how the app behaves without gaps, and I just put in a fix for it that will ship in the next release.

Note that in the next release, you will have to change a terminal command to get the behavior that was in v0.25. In v0.27, the default behavior will be what I call the "curtain" behavior that came from Spectacle, which you see in v0.26, but your configured gaps will remain.

When v0.27 ships, here's the terminal command you would execute to get the "non-curtain" style of smaller/larger:

defaults write com.knollsoft.Rectangle curtainChangeSize -int 2

The readme will be updated when v0.27 ships with this info as well. I'll keep this issue open until v0.27 is out the door.

**Comment by macintacos** [comment]
I was just about to come here to report this, nice to see it's going to be addressed!

Just so that we're clear, if we have gaps enabled, we would need to run that command in order to get the gaps to remain? Or when the update comes out there's no need to do anything (and make smaller/bigger will keep the gaps when resizing)?

**Comment by rxhanson** [comment]
@macintacos Gap configuration won't change - it's just that the default behavior of v0.27 will be the "curtain" style of make smaller/larger. So, if you want gaps and the curtain style, then you don't have to do anything.

**Comment by rxhanson** [comment]
Ok v0.27 is out https://github.com/rxhanson/Rectangle/releases/tag/v0.27

Closing this one out, but feel free to comment or reopen if there's any issues.
