### ISSUE TITLE
keyboard shortcuts changed

### ISSUE THREAD

**Issue by alexkubica** [rxhanson/Rectangle#1392]
Hi I just installed latest rectangle on mac mini and keyboard shortcuts seem to be different 

For instance maximize command is mapped to cmd+option+f instead of ctrl+option+enter

I couldn't find a way to switch to the old layout

**Comment by gothic-bum** [comment]
https://github.com/rxhanson/Rectangle/blob/main/TerminalCommands.md#keyboard-shortcuts

**Comment by rxhanson** [comment]
Aside from the terminal commands (thanks @gothic-bum), you can change the between the recommended and Spectacle default shortcuts by pressing the restore default shortcuts button in the gear tab of the settings window.
