### ISSUE TITLE
Google Chrome double-click window

### ISSUE THREAD

**Issue by cale23** [rxhanson/Rectangle#1395]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 14.5
Rectangle version: 0.79
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

Clicking the window title bar to maximize only works when clicking around close/minimize/maximize buttons. The rest of the bar does nothing when clicking on it. Disabled the default double-click to Zoom feature in macOS settings.

**Comment by cale23** [comment]
Kudos! @rxhanson Works!

**Comment by rxhanson** [comment]
Great! That's the work of @decodism.
