### ISSUE TITLE
Last third app shifts to the right after waking Mac from sleep on dual monitor setup 

### ISSUE THREAD

**Issue by gabriel-cloud** [rxhanson/Rectangle#1398]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 14.5 (23F79)
Rectangle version: 0.79 (85)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

1. Have a dual monitor setup (Left monitor connected via HDMI, right monitor connected via USB-C
2. On the left monitor, have one app take **first 2 thirds** 
3. Have another app take **last third**
4. Apple logo > Sleep
5. Wait a few seconds so that the monitors go back to standby
6. Wake the Mac up
7. (x) Observe the window that was taking the last third has now shifted right. The amount it shifts is consistent all the time you put the Mac to sleep and wake it (328px, or 164pt). Both screens are 4k, set to look like 2560 x 1440 
<img width="474" alt="image" src="https://github.com/rxhanson/Rectangle/assets/54978752/722a2334-cd07-40e4-8c96-cc8233186911">

**Comment by rxhanson** [comment]
Unfortunately, this issue is on the macOS side (or maybe Slack?). A workaround within Rectangle is rather undesirable compared to a real fix, since it would involve polling and delays.
