### ISSUE TITLE
Center position does not resize a window

### ISSUE THREAD

**Issue by TribuneX** [rxhanson/Rectangle#140]
macOS version: 10.15.4
Rectangle version: 0.26 (31)

The option center seems to only center the window with its current size. However, I would prefer to have the option to switch to a smaller window, which is centered. Did I miss this option or is it not available?

**Comment by rxhanson** [comment]
You can modify the "Almost Maximize" setting to be whichever width and height you want, see the Readme here: https://github.com/rxhanson/Rectangle#almost-maximize

**Comment by xgdgsc** [comment]
Thanks for the tip, for anyone might wondering how it' s done it' s something like:
```
defaults write com.knollsoft.Rectangle almostMaximizeWidth -float 0.6 
defaults write com.knollsoft.Rectangle almostMaximizeWidth -float 0.65
```
Hope something more intuitive like the fancyzones plugin inside powertoys could be added, also for different layout preferences for different monitors.
