### ISSUE TITLE
The disk image couldn't be opened.  Failed to mount filesystems.

### ISSUE THREAD

**Issue by abarker-gravity** [rxhanson/Rectangle#1407]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

This bug reopens issue #1385 

macOS version: 14.5
Rectangle version: 0.79
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

```
$ hdiutil attach ./Rectangle0.80.dmg
expected   CRC32 $98E0774C
hdiutil: attach failed - no mountable file systems
MB-ABARKER:Desktop abarker$ hdiutil attach ./Rectangle0.80.dmg
Checksumming Protective Master Boot Record (MBR : 0)…
Protective Master Boot Record (MBR :: verified   CRC32 $B6B25D30
Checksumming GPT Header (Primary GPT Header : 1)…
 GPT Header (Primary GPT Header : 1): verified   CRC32 $F45A3621
Checksumming GPT Partition Data (Primary GPT Table : 2)…
GPT Partition Data (Primary GPT Tabl: verified   CRC32 $95686850
Checksumming  (Apple_Free : 3)…
                    (Apple_Free : 3): verified   CRC32 $00000000
Checksumming disk image (Apple_HFS : 4)…
................................................................................................................................................................................
          disk image (Apple_HFS : 4): verified   CRC32 $3AD9A6C9
Checksumming  (Apple_Free : 5)…
                    (Apple_Free : 5): verified   CRC32 $00000000
Checksumming GPT Partition Data (Backup GPT Table : 6)…
GPT Partition Data (Backup GPT Table: verified   CRC32 $95686850
Checksumming GPT Header (Backup GPT Header : 7)…
  GPT Header (Backup GPT Header : 7): verified   CRC32 $9D0E415F
verified   CRC32 $98E0774C
hdiutil: attach failed - no mountable file systems
```

Tried downloading several sources of 0.8, rebooted several times and the issue persists. 

<img width="256" alt="image" src="https://github.com/rxhanson/Rectangle/assets/164929931/5ac2f3e7-c101-46e3-982a-722db112a18d">

I suspect this is due to some kind of anti-virus crapware on this system like Vanta or CyberArk but I have no idea how I can confirm that.  Nothing else I have installed uses a dmg at the moment.

**Comment by rxhanson** [comment]
I think you're correct that it is something on your system causing this. It's probably unlikely that you can do this, but if you can install brew you could install it with `brew install --cask rectangle`. Beyond that, you could try downloading the .dmg on a different machine, then copy over the .app.

**Comment by abarker-gravity** [comment]
```
==> Installing Cask rectangle
hdiutil: attach failed - no mountable file systems
==> Purging files for version 0.80 of Cask rectangle
Error: Failure while executing; `/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/homebrew-dmg20240620-21126-weltpp /private/tmp/homebrew-dmg20240620-21126-weltpp/c9538423eae9ce36d40b8c7827499195108dd34ae0eebe422f66c8f585b3aeb7--Rectangle0.80.cdr` exited with 1. Here's the output:
hdiutil: attach failed - no mountable file systems
```

**Comment by rxhanson** [comment]
At least that narrows it down to being something specific to your Mac. Perhaps this is something you can resolve with an admin that manages software on your Mac?

**Comment by abarker-gravity** [comment]
As suspected, this was a result of some restrictive policies that were being tested out and have now been resolved. We can close this issue.
