### ISSUE TITLE
Spectacle shortcuts inaccessible after first launch

### ISSUE THREAD

**Issue by adunning** [rxhanson/Rectangle#141]
macOS version: 10.15.4
Rectangle version: 0.26

If one does not select Spectacle shortcuts on first launch but subsequently wants to try them, there is no way to get back to this screen. I might suggest having the option display again when the user restores default shortcuts in preferences.

**Comment by rxhanson** [comment]
So they are available, you, but you have to execute this terminal command and restart the app:

`defaults write com.knollsoft.Rectangle alternateDefaultShortcuts -bool true`

(as noted in the Readme here: https://github.com/rxhanson/Rectangle#keyboard-shortcuts)

That's a good recommendation to display that window again when the user restored default shortcuts - I'll add it to my todo.

**Comment by rxhanson** [comment]
As recommended, in v0.32, the default shortcuts can be switched when the button is pressed to reset the defaults.

**Comment by adunning** [comment]
Thank you!
