### ISSUE TITLE
Snap feature aligns Terminal apps incorrectly. 

### ISSUE THREAD

**Issue by Phanquan** [rxhanson/Rectangle#1410]
- [ x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 13.6.7
Rectangle version: 0.80 (86)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

Well, snapping terminal app with incorrect alignment, although I use iterm all the time, it kinda bugs the ocd out of me.

<img width="1747" alt="Screenshot 2024-06-19 at 15 46 51" src="https://github.com/rxhanson/Rectangle/assets/25840139/5363d359-75c9-4203-aae9-806ee7456ba0">

**Comment by rxhanson** [comment]
If you use iTerm2, you can disable window size fitting to the character grid (using pixels instead) with the following Terminal command: 

```
defaults write com.googlecode.iterm2 DisableWindowSizeSnap -integer 1
```

If you're using Terminal, I'm not aware of a setting that can adjust this. Let me know if you find one!

**Comment by rxhanson** [comment]
Closing this one out since there isn't a valid fix to implement from within Rectangle.
