### ISSUE TITLE
Microsoft Office products not able to be pinned with app (specifically Excel)

### ISSUE THREAD

**Issue by JLeitstein** [rxhanson/Rectangle#1412]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.
- [ ] cannot pin microsoft excel windows with rectangle app 
<img width="837" alt="image" src="https://github.com/rxhanson/Rectangle/assets/173493371/5577a052-9f55-4f23-ad99-645fd82bc2ee">

macOS version: Sonoma 14.5
Rectangle version: 0.80 (86)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): N/A

**Comment by rxhanson** [comment]
Thanks for reporting. This means that Excel (& other Microsoft apps) are not working with the macOS accessibility API. You can try restarting Excel and that might fix the issue, but unfortunately this is an issue that is best resolved by Microsoft.
