### ISSUE TITLE
New desktop + look

### ISSUE THREAD

**Issue by whisper74541** [rxhanson/Rectangle#1414]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: macOS 14.5
Rectangle version:
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):

Hello, after deleting the rectangle, when I move the screen to a new desktop, the + shape still appears.
I tried using the terminal command
defaults delete com.knollsoft.Rectangle
and it still does. There are no files in the path ~/Library/Preferences/com.knollsoft.Rectangle.plist either. Any idea why this is really happening? It's so frustrating.
Also, I don't know what the difference is between having the drag-and-drop window placement setting on and off, they both seem to work.
Maybe it's just the translator that's a bit awkward. Thank you for your understanding.

https://github.com/rxhanson/Rectangle/assets/122680621/bc065828-ee11-494f-a241-63839366c9db

**Comment by rxhanson** [comment]
I’m not sure I understand exactly what functionality you don’t want here, but it doesn’t look like anything related to Rectangle. 

If Rectangle is not running or Rectangle has been deleted, then it is not possible for any of Rectangle’s functionality to occur.

**Comment by whisper74541** [comment]
The mouse you're moving around is the terminal. We're talking about the ability to split-screen when you put the terminal into a new desktop. The + shape to split didn't come out originally, but it came out after I installed rectangle, and I didn't get any emails, so I posted it on GitHub.

**Comment by rxhanson** [comment]
This is unrelated to Rectangle, perhaps you just didn't notice it prior to installing Rectangle.

**Comment by whisper74541** [comment]
Thank you so much for your response. We wish you nothing but the best.
