### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by dotyerts** [rxhanson/Rectangle#142]
macOS version: 10.15.5
Rectangle version: 0.27

Seems like there is CPU usage normally at 0.0 energy usage in activity monitor, yet jumps to 0.1 or 0.2 at random times even when windows are not being snapped. Do you have any insight?

**Comment by rxhanson** [comment]
If you have snap windows by dragging enabled, Rectangle will get the accessibility element for the frontmost window when you click. This is most likely what you're seeing. If you drag the window, then it will run some calculation on cursor location to determine if you're in a snap area, and this can push CPU up closer to 1% depending on how much you're moving the window around.
