### ISSUE TITLE
halveHeightUp Doesnt work as expected

### ISSUE THREAD

**Issue by rohitsrivatsav** [rxhanson/Rectangle#1429]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Sonoma 14.5
Rectangle version: 0.81 (87)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

I set up a custom shortcut for halveHeightUp and halveHeightDown .  halveHeightDown does cut down the vertical height by 50% as expected. However when  halveHeightUp is used  ( on full length window) doesnt do anything , halveHeightUp shortcut only works for windows that are already 50% cutdown and it maximizes to full 100% length.  My assumption was halveHeightUp is meant to slice the vertical width by 50% towards Up but so far doesnt seem to work that way

**Comment by rxhanson** [comment]
I'm not quite sure I understand exactly where things are going wrong. If you don't mind, can you make a quick screen recording and provide logging? To show logging, hold the option key in the menu bar menu and select View Logging...

Thanks!

**Comment by rohitsrivatsav** [comment]
[Rectangle Logs.log](https://github.com/user-attachments/files/16446322/Rectangle.Logs.log)

When a window is maximized or occupies full height of screen , pressing CTRL+OPT+SHIFT + UP_ARROW does nothing to the window.
Instead when window only occupies bottom half of screen ,  pressing CTRL+OPT+SHIFT + UP_ARROW maximizes the window to full height instead

 You could probably see in logs

**Comment by rohitsrivatsav** [comment]
Sorry couldnt record the screen . Somehow quicktime on my mac isnt recording my screen. Will upload if i do end up recording again

**Comment by rohitsrivatsav** [comment]
[RectangleConfig.json](https://github.com/user-attachments/files/16516059/RectangleConfig.json)


Hereis my config

**Comment by rohitsrivatsav** [comment]
Update , i realized after exporting config , i had two commands with same shortcut. So i fixed that , quit the app and started again ..VOLLA it works now . Appreciate you pointing me in the direction of looking at config . This ticket can be closed :).
