### ISSUE TITLE
Move window slightly

### ISSUE THREAD

**Issue by jandusek** [rxhanson/Rectangle#143]
Since relative window resizing is supported (Make Smaller / Make Larger), would it make sense to also support relative window positioning? (Move Slightly Left / ...).

Need for relative resizing and positioning of windows using a keyboard was how I originally discovered Rectangle. I thought "Move Left" would do exactly that, but that moves window to the edge.

**Comment by rxhanson** [comment]
I don't have plans to add this in, but I would consider a pull request for it. I think it would probably work best as an alternate behavior for the current Move actions, enabled via Terminal command. Closing this one out, but feel free to submit a PR.
