### ISSUE TITLE
clearer link to/explanation for Key Codes app

### ISSUE THREAD

**Issue by joeldcanfield** [rxhanson/Rectangle#1439]
Please move/copy this information to a more prominent place in [Terminal Commands](https://github.com/rxhanson/Rectangle/blob/main/TerminalCommands.md)

`This extra command is not available in the UI. You'll need to know which keycode and modifier flags you want (try the free key codes app: https://apps.apple.com/us/app/key-codes/id414568915)`

The menu links jump directly to the 'how to' bits, skipping past this important and usefil information. This might leave the uninitiated but motivated to spend lots of time wondering why your math for the modifierFlags doesn't add up. I mean, it could. Not that *I* just spent an hour on that. The Key Codes app makes it intuitively obvious even to the casual observer.

**Comment by rxhanson** [comment]
Thanks for the feedback, I put this information at the top of the Terminal Commands page. I'll close this one out, but feel free to comment further if you don't think the change is sufficient and we'll get it right.

**Comment by joeldcanfield** [comment]
Perfect. Thanks for the quick fix. I LOVE RECTANGLE. ahem. sorry for shouting.
