### ISSUE TITLE
VLC does not

### ISSUE THREAD

**Issue by livni** [rxhanson/Rectangle#1444]
- [ V] This is a new bug that hasn't been documented in a closed issue or in the Readme.

Maximizing VLC leaves some of the window below the display. In particular the part with the controls, which is annoying.
Reproduced with a 1920 x 1248, MPEG-4 AAC, H.264 file. This may be different for different aspect ratio videos, as I think what Rectangle does is match the width of the player with the width of the screen.

I imagine this is a product choice, however IMHO it's worse not seeing the whole window, than to maximize screen utilization.

macOS version: 14.5
Rectangle version: 0.82 (88)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):

**Comment by rxhanson** [comment]
Thanks for reporting. Unfortunately, this is on VLC. Rectangle uses the Accessibility API in macOS to tell a window which dimensions to use and it is up to an app to respond correctly to those commands.

**Comment by livni** [comment]
I sent them an email pointing to this thread, hopefully they'll address
