### ISSUE TITLE
Slovak localization improved

### ISSUE THREAD

**Issue by Svec-Tomas** [rxhanson/Rectangle#1451]
Hi Ryan,

Please find attached the file containing my translation. I have corrected some translations and finished some untranslated strings. 

Please let me know if anything else is needed.

Thanks!

**Tomáš Švec**
[Main.xcstrings.zip](https://github.com/user-attachments/files/16825653/Main.xcstrings.zip)

**Comment by rxhanson** [comment]
Thanks! I'll turn this into a pull request and make sure everything looks good.

**Comment by Svec-Tomas** [comment]
Do I need to translate [this here](https://github.com/rxhanson/MASShortcut/blob/master/Framework/Resources/en.lproj/Localizable.strings) as well to have Rectangle fully translated, right?

**Comment by rxhanson** [comment]
Yes, that would also need to be translated.

**Comment by Svec-Tomas** [comment]
OK, here is the translated file.

I just want to make sure SPACE is used there as a SPACE between two words or SPACE as a Spacebar key?

I have translated it as Sp
[MASshortcut.zip](https://github.com/user-attachments/files/16835353/MASshortcut.zip)
acebar (key).

Thanks.
