### ISSUE TITLE
Feature Request Move Focus

### ISSUE THREAD

**Issue by jrbrodie77** [rxhanson/Rectangle#146]
Thanks for working on Rectangle, I love it.  One thing that drive me nuts in OS X is having to use the mouse to switch focus from one display to another.  It would be great if Rectangle could do this. Apparently there have been utilities that move the mouse from one to the other. I'd love it if this were built into rectangle.

**Comment by rxhanson** [comment]
Sorry, this isn't really something I have plans to add into Rectangle, even if there were a pull request for it. This is kind of a one-off feature, and it makes sense to me to have a small separate app that manages focus of windows. Thanks for the feedback, though. There are other users that have requested some similar features with selecting focus, so it's possible there's something else open source out there that I'm unaware of that does this.

**Comment by xero** [comment]
do you have a suggestion before a small app for focusing? this is literally the feature that is missing from rectangle in my opinion. otherwise, it's an amazing application that does everything I want, except for that. thanks for your consideration and potential suggestions

**Comment by xero** [comment]
doesn't look like this has configurable hotkeys sadly
