### ISSUE TITLE
Animate resizing via keyboard shortcuts?

### ISSUE THREAD

**Issue by Rylon** [rxhanson/Rectangle#1465]
Hi, I tried Sequoia's new window tiling and I still much prefer the way Rectangle works, especially the customisation, but the little animations in Sequoia when a window moves into the new location are very nice. Are those new APIs available for Rectangle to use at all? Would be the best of both worlds for me!

Thanks for a great app!

**Comment by rxhanson** [comment]
Thanks for the feedback! Unfortunately, there is no way to do this as a 3rd party. I'm not aware of any new APIs for it.

**Comment by Rylon** [comment]
Ah that's a shame, is it something you could do yourself, or would that be too laggy? Not to worry anyway, I stuck with Rectangle as the built-in approach was just too inflexible.

**Comment by rxhanson** [comment]
Yes, unfortunately it would be laggy provided the options available. If anyone wants to give it a go and gets something good working, I would be fine merging a pull request for it.

**Comment by Rylon** [comment]
Ok cool, no worries then, thanks again!

**Comment by savked** [comment]
Just wanted to check whether anything has changed regarding this with the release of Tahoe 26?

**Comment by rxhanson** [comment]
As far as I know, there are no new APIs that would allow a 3rd party to do this in a nice way.
