### ISSUE TITLE
Opening and exiting fullscreen video

### ISSUE THREAD

**Issue by cale23** [rxhanson/Rectangle#1472]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Sequoia 15.0
Rectangle version: v0.83 (89)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): There are no logs when reproducing this.

For example, opening YouTube fullscreen on double-click and exiting it by tapping the Esc key does not restore the previously maximized window, it's shorter in height afterward when exiting the fullscreen.

I don't know if this is Rectangle-related.

I don't have the native tiling windows enabled in the macOS settings.

**Comment by rxhanson** [comment]
Thanks for reporting. Unfortunately, this is an issue in macOS and is not related to Rectangle.
