### ISSUE TITLE
Gaps doesn't work with keyboard shortcuts

### ISSUE THREAD

**Issue by drasbeck** [rxhanson/Rectangle#149]
macOS version: 10.15.4 (19E287)
Rectangle version: 0.27 (32)

I enabled gaps via terminal, and they work when I place windows via the menu bar Item, however, when I try to do the same via keyboard shortcuts (which is my preferred method) my windows are not honoring the gaps settings.

I have tried with a 5 and 10 pixels gap.

**Comment by rxhanson** [comment]
Are you certain that you do not have any other window manager apps running? Can you paste what's in the Rectangle logs?

**Comment by drasbeck** [comment]
Embarrassing. Magnet was running. 😅 For future reference, where is the log saved?

**Comment by rxhanson** [comment]
No worries. 

https://github.com/rxhanson/Rectangle#view-debug-logging
