### ISSUE TITLE
MacOS Sequoia (15.0) + Arc Browser Full Screen Mode = RectangleApp not working

### ISSUE THREAD

**Issue by davabi** [rxhanson/Rectangle#1493]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 15.0
Rectangle version: 0.83 (89)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): nothing

So Full Screen Mode now implies RectangleApp shortcut not working
I tried all the reboot/reset/quit/restart thing.

**Comment by rxhanson** [comment]
Thanks for reporting. Using Rectangle to adjust the size/position of a full screen app isn't supported; it's a macOS limitation. Let me know if I'm misunderstanding and if there is indeed a change in behavior that I can adjust.
