### ISSUE TITLE
McAfee flagging Rectangleapp.com 

### ISSUE THREAD

**Issue by holamau** [rxhanson/Rectangle#150]
Hello, 

This is more of a heads-up than an issue.

McAfee End-Point security is flagging your site as a security risk. 

Just wanted to let you know that maybe some potential users may be deterred by this warning. 

Regards, 
Mau.

this is a screenshot of the warning given by McAfee:
<img width="627" alt="Screen Shot 2020-05-12 at 9 06 55 AM" src="https://user-images.githubusercontent.com/6577028/81701667-f4396f80-942f-11ea-9823-b6257bd2af8f.png">

**Comment by rxhanson** [comment]
Thanks for the heads up! Definitely appreciated.

I've gone ahead and submitted a reclassification to McAfee, but I'm not sure how long it takes for them to review it.

**Comment by rxhanson** [comment]
Looks like McAfee has accepted my reclassification. Any chance you could try it out again and let me know if you still get that warning?

**Comment by holamau** [comment]
Hey!

Yeah, I'm accessing it with the browser I used yesterday and it's not yelling at me anymore!

Glad they reacted quickly!
