### ISSUE TITLE
New version 0.84(90) conflicts with mac Stage manager

### ISSUE THREAD

**Issue by henwenrou** [rxhanson/Rectangle#1502]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version:15.0.1
Rectangle version:v0.84(90)

The system Settings are not changed after installing the new version, and the left background program of mac Stage manager  automatically hides until the mouse moves to the left edge of the screen

**Comment by rxhanson** [comment]
Thanks for reporting. Recent versions of Rectangle will only adjust the built-in tiling settings of macOS if selected, not the Stage Manager settings. Stage Manager will hide if a window overlaps the Stage Manager area, and you can adjust the area that Rectangle will leave for Stage Manager in the gear tab of the settings window.

**Comment by rxhanson** [comment]
Closing this out, but feel free to comment further if I've missed something.
