### ISSUE TITLE
Arc browser detached from any space not resizing as expected

### ISSUE THREAD

**Issue by remy90** [rxhanson/Rectangle#1511]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

When using the right-half command in arc browser  for a window outside of any space. This is often the default for hyperlinks that are opened. You'll see Open in <space> in the top right corner.
I would expect the same result as a full window in a space selected context, which expands to the full right/left size.
What I observe is a move to the right location/direction without the appropriate resizing.

macOS version: 14.7.1 (15.x too)
Rectangle version: 0.84 (90)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 
(For right half command)
2024-11-12T11:46:08Z: AX sizing proposed: (1194.0, 964.0), result: (1194.0, 964.0)
2024-11-12T11:46:08Z: AX position proposed: (1323.0, 35.0), result: (1323.0, 35.0)
2024-11-12T11:46:08Z: AX sizing proposed: (1194.0, 964.0), result: (1194.0, 964.0)
2024-11-12T11:46:08Z: rightHalf | display: (0.0, 71.0, 2560.0, 984.0), calculatedRect: (1280.0, 25.0, 1280.0, 984.0), resultRect: (1323.0, 35.0, 1194.0, 964.0), srcScreen: LG HDR WFHD, destScreen: LG HDR WFHD, resultScreen: LG HDR WFHD

**Comment by rxhanson** [comment]
Thanks for the details. This seems to work as expected for me, although your logs do point to something being not quite right. My steps for getting a standalone (non-space) window are right-clicking on a link and selecting "Open in Little Arc". Is that a valid way to reproduce it for you, or should I try something different?

**Comment by remy90** [comment]
One way to reproduce that I've found is to open a link from outside of Arc (and open with Arc if not your default browser), i.e. a Mail app. Arc doesn't know which space to add it to, so it asks. I don't think you can do this directly from the browser because the assumption is you've already opened the link in the space you wish to place it inside.

You'll see signs in the corner of the window, where "work" is the <profile name> and Open in "Dev" refers to the space:
![Screenshot 2024-11-12 at 17 30 44](https://github.com/user-attachments/assets/2d538dfb-9d4d-49bf-a400-9b9d66c291f5)

**Comment by remy90** [comment]
Seems to work as expected on my personal M3 macos (15.0.1). It's possible there may be an issue with 14.x or there's been a recent update to Arc. In any case, I'll close this
