### ISSUE TITLE
Document gapSize / padding

### ISSUE THREAD

**Issue by Wilfred** [rxhanson/Rectangle#1512]
Issue #96 mentions instructions in the readme, which no longer exist. The readme at the time was: https://github.com/rxhanson/Rectangle/blob/4c5acf3cba8f770f00e054e49a46b4ae7aa97be4/README.md#details-on-adding-gaps-between-windows

Is this intended to be documented in https://github.com/rxhanson/Rectangle/blob/main/TerminalCommands.md? I can see other settings there, but no mention of gapSize.

The setting suggested still seems to work, e.g. `defaults write com.knollsoft.Rectangle gapSize -float 10` adds the padding as expected.

**Comment by rxhanson** [comment]
Gap size was removed when it became configurable in the gear tab of the settings window.

**Comment by cvlvxi** [comment]
Holy crap I just found this. Thank you
