### ISSUE TITLE
changing sizeOffset has no effect

### ISSUE THREAD

**Issue by esseti** [rxhanson/Rectangle#1521]
I want to change how much the smaller/larger changes the size when activated, i found that i can set it, however, even with this:
`defaults write com.knollsoft.Rectangle sizeOffset -float 500`
there's no effect
and the value is correctly set
```
❯ defaults read com.knollsoft.Rectangle sizeOffset -
500
```

**Comment by rxhanson** [comment]
If you haven't already, restarting Rectangle is required for this to take effect.

If it still isn't working, try this: 
```
defaults write com.knollsoft.Rectangle.plist sizeOffset -float <NUM_PIXELS>
```
Then restart the app.

**Comment by esseti** [comment]
Btw, i'm on Pro, is the setting the same? See https://github.com/rxhanson/Rectangle/issues/1522

**Comment by esseti** [comment]
nevermind, i'm in the wrong place https://github.com/rxhanson/RectanglePro-Community?tab=readme-ov-file

**Comment by rxhanson** [comment]
Closing this one out. Let me know if you still hit any issues here.
