### ISSUE TITLE
[Feature Request] Option to set window on top (of other windows)

### ISSUE THREAD

**Issue by josesa** [rxhanson/Rectangle#153]
Suggestion to have the option to set windows on top. 
As is part of window management, it fits nicely on the goal of Rectangle.

Wanted to record it here even if not addressed immediately.

**Comment by rxhanson** [comment]
Sounds like you want to use keyboard shortcuts to focus a window. This isn't something I plan on adding into Rectangle, but there are other users that have expressed interest in similar behavior. Perhaps someone else would be interested in building that up in a fork.

https://github.com/rxhanson/Rectangle/issues/91
https://github.com/rxhanson/Rectangle/issues/97
