### ISSUE TITLE
Some Option-key keybindings don't work in Terminal on MacOS Sequoia

### ISSUE THREAD

**Issue by yubo56** [rxhanson/Rectangle#1530]
- [X] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 15.2
Rectangle version: v0.85 (91)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): None

I have the behavior of two keybindings to compare. Snap to left half = "Option+left" and Maximize = "Option+M". When pressing "Option+left" in either Terminal or other apps, snap to left works. When pressing "Option+M" in other apps, works. But when pressing "Option+M" in Terminal, it sends a non-ASCII character and doesn't trigger the Rectangle keybinding. This behavior is reproducible with a few "Option+<key>" keybindings but not others.

This is new in MacOS 15, it was working correctly in MacOS 14. Is [this](https://www.reddit.com/r/macapps/comments/1fjpiiw/psa_macos_15_breaks_optionkey_hotkeys/) related? Is this fixable in Rectangle, or via a MacOS setting (I've tried many to no avail)?

**Comment by rxhanson** [comment]
I can't reproduce this, which points to something going on with your setup. As a quick sanity check, do you have Terminal ignored in Rectangle (in the menu bar menu)?

**Comment by yubo56** [comment]
No Terminal is not ignored. Okay, very interesting then, I've dug through a bunch of Terminal settings and not found anything. Well, you should feel free to close this if you can't reproduce it, I'll figure it out eventually hopefully :)
