### ISSUE TITLE
Bell sound when "repeated execution of half and quarter actions" is disabled

### ISSUE THREAD

**Issue by lulor** [rxhanson/Rectangle#158]
macOS version: macOS Catalina 10.15.4
Rectangle version: 0.29

Hi there,
I don't remember if this was an issue in the past versions, but recently I've noticed that when the "Halves to thirds (repeated execution of half and quarter actions)" feature is disabled, every time I erroneously repeat a "half action", I hear an error bell sound. Would it be possible to disable it?

Anyway, thank you so much for Rectangle!

**Comment by rxhanson** [comment]
Thanks for reporting, try v0.30: https://github.com/rxhanson/Rectangle/releases/tag/v0.30

**Comment by lulor** [comment]
Wow, that was quick :)

I can confirm that the sound went away with the latest update, thanks!
