### ISSUE TITLE
Problems Resizing Notion and Firefox

### ISSUE THREAD

**Issue by klickreflex** [rxhanson/Rectangle#163]
macOS version: 10.15.5
Rectangle version: 0.30 (35)
logs (In Rectangle menu, hold option, "View Logging..."): Empty

Notion and Firefox behave weird and unpredictable with Rectangle. I think it is better shown in a screencast than described with words:

Notion: https://www.loom.com/share/22622196f222418dbed75e62f2207835
Firefox: https://www.loom.com/share/6ca14fd6f5d44713af922eb925851978

It's the same via all controls: Shortcuts, Menu item and Mouse-drag. 

At first I thought this might be Electron-related, but the fact that VS Code and Slack are not affected but Firefox is speaks against that. 

Possibly related: 
#108 
#101

**Comment by rxhanson** [comment]
Thanks for taking the time to make videos and look through the issue backlog. 

This actually looks to be the macOS bug noted in the [Readme](https://github.com/rxhanson/Rectangle#window-movingresizing-appears-animatedsmooth-instead-of-quick-and-windows-dont-end-up-where-you-expect). 

In summary, you can
1. Try to avoid the scenarios that cause this in macOS, as noted in the Readme
2. File a bug with Apple
3. Use the workaround build of Rectangle noted in the Readme.

For reference, here's the related issues:
https://github.com/rxhanson/Rectangle/issues/29
https://github.com/rxhanson/Rectangle/issues/94
https://github.com/rxhanson/Rectangle/issues/15

**Comment by klickreflex** [comment]
Oh, and I thought I had researched the issue properly 🙈  
Thanks for referencing the possible solution. Will file a bug report and try the alpha build 👍  (only have things in the a11y settings that really need it).

**Comment by rxhanson** [comment]
Thanks for reporting back. I'm going to close this one out, since there's unfortunately nothing more I can do from Rectangle's perspective at this time.
