### ISSUE TITLE
Feature request: Fixed window sizes (presets)

### ISSUE THREAD

**Issue by svenjacobs** [rxhanson/Rectangle#169]
First of all thank you very much for this magnificent application!

Would it be possible to include a functionality for resizing a window to a specific width and height in pixels? For example if this function is executed a dialog could ask for desired width and height or the user could select from a list of presets? I think this would be very useful for instance for screen recordings, to ensure that a window fits into a specific video resolution.

Many thanks!

**Comment by rxhanson** [comment]
Interesting idea. I've actually never thought about allowing a user to specify pixel dimensions. I can't think of any other times that this would be desired other than your mentioned case of specific screen recording resolution. It would also be necessary to allow the user to select position of the window as well. For simplicity of the app, unfortunately I don't think I would add it in. I'll keep it in mind if any features in the future overlap this type of functionality, though.

**Comment by zapme** [comment]
I'd like to vote for this as well.  With remote work so prevalent, being able to target a window size is critical for screen sharing.  It's the only reason that I use SizeUp instead of Rectangle.  Would be beneficial to have shortcuts for the common 4:3 resolutions as well as 16:9

**Comment by svenjacobs** [comment]
FYI I created a small [NodeJS application](https://github.com/svenjacobs/macos-window-resizer) for resizing macOS windows. However it's very rudimentary and just provides a command line interface. I would still like to see this functionality in Rectangle 🙂
