### ISSUE TITLE
gaps+distance from top

### ISSUE THREAD

**Issue by StefKors** [rxhanson/Rectangle#171]
I would love an option to set a distance from top, which will make it possible to work together with apps like [Pecan](https://github.com/zzzeyez/Pecan)

Reading through the code it looks like an extra clause [here](https://github.com/rxhanson/Rectangle/blob/master/Rectangle/WindowManager.swift#L97-L101) might be enough. Alternatively specifying gaps as an array might also be an option.

Happy to send in a PR, but I'm not familiar with swift. If you're willing to guide me into the right direction, I could help out.

**Comment by rxhanson** [comment]
I can see merging a PR with this.

Unless you're ok with smaller top half/quarter windows than bottom, having a set distance from the top would change the vertical center of the screen. This means that you would want the window calculation to be based on a `visibleFrameOfScreen` size that subtracts out your specified distance from the top. You could probably just update the `UsableScreen(s)` accordingly in the `WindowManager` before they are used for the window calculation. That way you're not doing a lot of additional calculation after the fact at the point when the gaps are applied. 

It would be best if this additional logic were pulled into a separate class, maybe as a static function so as to minimize the lines of code added to the WindowManager.

I think that should be enough to get you started?

**Comment by StefKors** [comment]
Thanks @rxhanson I think it will be enough. From the sounds of it Updating the `usableScreen` size makes the most sense. Should this PR only contain options for the distance to the top, or should it also have the option for any of the other sides? 

I'll have a go at it over the weekend and open a draft PR for it.

**Comment by rxhanson** [comment]
It would be best to go ahead and knock out options for other sides as well, but I would still merge the PR even if it only had top. Other sides are useful to have (particularly the bottom, but sides as well) because 3rd party dock applications aren't currently accounted for by Rectangle. Each side would have its own config value added to the `Defaults` class.

**Comment by Middlerun** [comment]
I'd love to be able to specify a bottom gap. I use uBar as a dock replacement and currently I'm having to maximise windows manually so they won't underlap uBar.

**Comment by mattCameron09** [comment]
@StefKors Any update on the draft for this? I also use uBar and am having issues with overlapping. Ideally I'd like to have uBar on the bottom.

**Comment by StefKors** [comment]
@mattCameron09 sadly I haven't gotten around to work on this, I keep reminding myself that I should, but so far i haven't been able. If anyone else want to take a stab at it please go ahead 👍

**Comment by Middlerun** [comment]
I've just spent some time working on this. I've got it working nicely with some hard-coded values, next I've got to set them up as config values. Hopefully I can get a pull request up on the weekend.

**Comment by rxhanson** [comment]
Closing this one out since it's in v0.34+ 🥇

**Comment by JoeriTheGreat** [comment]
> Closing this one out since it's in v0.34+ 🥇

Can you please elaborate on how to do this ? 
I have tried using following commands in the terminal:
"defaults write com.knollsoft.Rectangle screenEdgeGapBottom -int 10"
"defaults write com.knollsoft.Rectangle marginBottom -float 100" 

But these commands seem to do nothing ? I'm using Ubar4 and i would just need to have a margin bottom.

**Comment by Middlerun** [comment]
`defaults write com.knollsoft.Rectangle screenEdgeGapBottom -int 10` should do it. You also need to restart Rectangle after setting it.

**Comment by JoeriTheGreat** [comment]
> `defaults write com.knollsoft.Rectangle screenEdgeGapBottom -int 10` should do it. You also need to restart Rectangle after setting it.

Yes restarting rectangle works for me! Thanks
