### ISSUE TITLE
Option to forget previous window size

### ISSUE THREAD

**Issue by DrRob** [rxhanson/Rectangle#172]
After using a Rectangle shortcut to resize/reposition a window, if I move the window then it snaps back to its previous size.  I would like to disable that.  Often I put a window into a corner just to set its size, and then drag it elsewhere.

**Comment by rxhanson** [comment]
Is this what you're looking for?
https://github.com/rxhanson/Rectangle#disabling-window-restore-when-moving-windows

**Comment by DrRob** [comment]
Perfect, thanks.  (Could be a tickbox in the Settings...?)
