### ISSUE TITLE
Snapping feature is instable

### ISSUE THREAD

**Issue by dploeger** [rxhanson/Rectangle#174]
macOS version: 10.15.5
Rectangle version: 0.3.0
logs (In Rectangle menu, hold option, "View Logging..."): no logs were written

When trying to snap on the top of the screen to maximize it, I have problems reaching a stable point where I can drop the window. This looks like this:

![2020-06-17 at 09 33 gifcask 2020-06-17 09_37_27](https://user-images.githubusercontent.com/203453/84869335-2f0d7380-b07e-11ea-8266-56e5743614b9.gif)

(it "flickers" much more, but the gif dropped those frames)

**Comment by rxhanson** [comment]
I take it this doesn't happen for any of the other snap areas? 

At a start, maybe try increasing the margin for the top snap area:
https://github.com/rxhanson/Rectangle#changing-the-margin-for-the-snap-areas

Your video shows some pretty strange behavior from what I can tell, so I think there's something more going on here. Are you aware of any other apps running that might be listening to drag events from the event stream when you drag something to your menu bar? You could increase the top snap margin to be larger than the menu bar and see if the snap area is unobstructed when it's below the menu bar but within the snap margin.

**Comment by dploeger** [comment]
Argh, sorry. It really is a problem because of running bettertouchtool at the same time. I have disabled the snap features of btt but that didn't seem to work completely as it seems.

However, increasing the top snap area works as a workaround. 

Thank you very much!
