### ISSUE TITLE
Is there a way to set up Rectangle to start automatically on boot?

### ISSUE THREAD

**Issue by atsalolikhin-spokeo** [rxhanson/Rectangle#175]
Hi! I just switched to using MacOS, and Rectangle is making my life much easier, it's actually increased my productivity and allows me to have a stable setup -- much appreciated!

Is there a way to set up Rectangle to start automatically?  I didn't see any setting like that in the Rectangle UI (which I know you keep simple intentionally) -- maybe there is some Terminal command I need to run?

Thanks again for an elegant and useful app!

**Comment by atsalolikhin-spokeo** [comment]
I've added Rectangle to my "Login Items" list of items to open automatically when I login, as per https://www.lifewire.com/how-to-add-startup-items-to-mac-2260903

**Comment by rxhanson** [comment]
Adding it to your login items list works just fine. Here's the setting in the app settings:

<img width="602" alt="Screen Shot 2020-06-19 at 6 50 47 PM" src="https://user-images.githubusercontent.com/13651296/85159525-ea403300-b25d-11ea-9b70-13ad21c44dc2.png">
