### ISSUE TITLE
Right traverse is 'backwards' when using 'traverse on subsequent left/right keypress'

### ISSUE THREAD

**Issue by stgarf** [rxhanson/Rectangle#18]
When I use the `Next/Previous Display` shortcut Rectangle traverse my displays in the following order (just keep this in mind, because this is how I'd expect the next part of Rectangles functionality to work when using half actions):
* `Next`: `1 --> 2 --> 3 --> 4 --> loop back around`
* `Prev`: `4 --> 3 --> 2 --> 1 --> loop back around`

But when `Traverse displays on subsequent left or right execution` is enabled:
![Screen Shot 2019-10-11 at 6 22 14 PM](https://user-images.githubusercontent.com/1694002/66692711-eaf7e280-ec55-11e9-8e79-51e067c848f6.png)

Rectangle moves my window **_left_** (or backwards, however you'd like to look at it) as I'd expect and traverses my displays in the correct (backwards) order: `4 --> 3 --> 2 --> 1 --> loop back around`.

However, Rectangle traverses my displays in a the same order when transitioning **_right_** (or forward): `4 --> 3 --> 2 --> 1 --> loop back around` which seems reverse to how I'd expect it to happen in my head (and is also visually jarring when you're pressing `right` but it jumps to the next `Previous` display).

Here's my displays layout for reference:
![Screen Shot 2019-10-11 at 6 23 48 PM](https://user-images.githubusercontent.com/1694002/66692865-70c85d80-ec57-11e9-977f-e7627abd944c.png)

**Comment by rxhanson** [comment]
Ok, I think I understand this one. 
Next/Prev Display is properly working. 
With "Traverse displays..." selected, left works properly but right goes backwards.

This bug exists because I only have 2 displays, so I haven't noticed it. Let me see what I can do here.

**Comment by rxhanson** [comment]
Let me know if v0.8 fixes it: https://github.com/rxhanson/Rectangle/releases/tag/v0.8

**Comment by stgarf** [comment]
@rxhanson Works as expected :) -- Thank you very much 🚀 👍!

Fixed by cdd96ec (for posterity).
