### ISSUE TITLE
Can't switch between displays

### ISSUE THREAD

**Issue by dantebarba** [rxhanson/Rectangle#184]
macOS version: 10.13.6
Rectangle version: 0.30 (35)
logs (In Rectangle menu, hold option, "View Logging..."): 

`
2020-06-30T22:47:17-03:00: Nil calculation result
`

IDK if this is a bug or a feature request. But I can't switch windows between workspaces. I only have one display monitor connected but I have more than one workspace active in mission control. I'm attaching a screenshot with the issue. 

![Screen Shot 2020-06-30 at 22 43 13](https://user-images.githubusercontent.com/6656541/86194079-ed6fd480-bb23-11ea-93d9-6a26ed278708.png)

Maybe it's not the intended functionality and it should only work to switch between monitors, but it would be awesome to send to different workspaces with a shortcut just like you can do in Linux:

> In ubuntu: (...) Press Ctrl+Alt and an arrow key to switch between workspaces. Press Ctrl+Alt+Shift and an arrow key to move a window between workspaces. (...)

Regards
Dante.

**Comment by rxhanson** [comment]
This is a common request. Here's the most recent issue for it: https://github.com/rxhanson/Rectangle/issues/137.

> In short, Apple doesn't provide public APIs for spaces. If at some point they do, I'll be glad to to revisit this.

If someone implements this in an elegant way, I'd consider merging a PR for it since so many people are interested in it.
