### ISSUE TITLE
Youtube Firefox Fullscreen

### ISSUE THREAD

**Issue by 211217613** [rxhanson/Rectangle#186]
macOS version: 10.15.5 (19F101)
Rectangle version: Version 0.30 (35)
logs (In Rectangle menu, hold option, "View Logging..."): 

Step 1: almost maximize Firefox
Step 2: put YouTube video into full screen
Step 3: exit YouTube video full screen
Step 4: watch the previous "Almost Maximized" Firefox shrink to bottom left of screen.

It seems like rectangle doesn't remember the position of the the Firefox window after exiting YouTube full screen and defaults to _size_ and _position._

**Comment by rxhanson** [comment]
Sorry - looks like I never replied to this one. I was never able to reproduce an issue here. Think you could record a quick video to demonstrate this issue?

**Comment by rxhanson** [comment]
Just doing some housekeeping and closing out old issues. Let me know if this is still a reproducible issue and if you can record a quick video demonstrating it.
