### ISSUE TITLE
Center two thirds?

### ISSUE THREAD

**Issue by acousticbiker** [rxhanson/Rectangle#187]
Hi there, great app - thanks for providing an improvement to Spectacle! I saw that you are not accepting new feature requests but thought I'd throw this one in there because it seems to be a missing variation of existing options. Would you consider adding a 'Center two thirds' option? I currently use left or right two thirds and then center to achieve this but one click/keystroke would be nice.

**Comment by rxhanson** [comment]
Duplicate of https://github.com/rxhanson/Rectangle/issues/148 and https://github.com/rxhanson/Rectangle/issues/52

Maybe this can be explicitly added in when the UI is updated to handle more actions.

**Comment by brakende** [comment]
This would be very much appreciated! On my 34', some apps are better in center 2/3ds.

**Comment by sinharaksh1t** [comment]
> > Execute the following terminal commands to modify the Almost Maximize ratio.
> > `defaults write com.knollsoft.Rectangle almostMaximizeHeight -float 1`
> > `defaults write com.knollsoft.Rectangle almostMaximizeWidth -float 0.66`

Exactly what I was looking for! Thanks for the workaround!

**Comment by folsze** [comment]
Do note that you have to restart reactangle for it to take effect! 
(restarting of any previously active apps not necessary)
