### ISSUE TITLE
Top Half/Bottom Half - to implement 1/3 & 2/3 options

### ISSUE THREAD

**Issue by Easen** [rxhanson/Rectangle#19]
I have just switched from Spectacle and one feature that I used quite often that Rectangle doesn't implement is the Top 1/3 option. I see you have implemented this for the "Left Half" & "Right half" options where multiple innvocations will resize the window to 2/3 and then 1/3.

I think I might be able to add this feature as the project looks fairly straight forward and well laid out. However as per your contributing guidlines, is this something that you would accept via a PR?

**Comment by rxhanson** [comment]
This behavior should be preserved from spectacle - multiple invocations of top half or bottom half **should** resize to 2/3 then 1/3. If this isn't the case for you, then it's a bug. It works for me, and you can take a look at TopHalfCalculation.swift or BottomHalfCalculation.swift to see the logic.

Let me know if I'm misunderstanding.

**Comment by rxhanson** [comment]
In thinking about it a little more, this could be a bug depending on the application's window that you're trying to move/resize. It's a little broken for Terminal (and probably iTerm), when the default behavior for window sizing based on character spaces prevents Rectangle from getting a good read on whether the window has been resized to 1/2 or not. This shouldn't be a hard fix, so it can be a part of this issue.

**Comment by Easen** [comment]
You're correct. I just assumed that the behaviour hadn't been done as I was trying to resize an iTerm window.

The issue is indeed with the way iTerm/terminal does it's veritical resizing, rounding up/down to the next line. 

As a workaround I've updated the rectCenteredWithinRect() method to use an error margin and it seems to have fixed the issue for me. I'll commit it and push it up so you can take a look. 

I'm sure there are better ways to fix this issue... :)

**Comment by stgarf** [comment]
@rxhanson I literally just ran into this issue today with iTerm2 too and came here to report this as a bug and then read this issue. So count this as a +1 from me.

**Comment by rxhanson** [comment]
This fix is now in v0.9. Closing it out but feel free to reopen if there's any issues.
