### ISSUE TITLE
Missing left-top 1/3 and left-bottom 1/3

### ISSUE THREAD

**Issue by taiya** [rxhanson/Rectangle#193]
Not sure it's a feature request, or a request for consistent behavior :)

**Comment by rxhanson** [comment]
With "cycle across displays..." unchecked, current behavior would allow this as a repeated execution of top left and bottom left. Otherwise, would this be covered by https://github.com/rxhanson/Rectangle/issues/177?

**Comment by taiya** [comment]
Ah, excellent, didn't see there was a "cycle" nature to the top/left right
Yes, that's basically my scenario – ultrawide monitor – equivalent of 3x
vertical 14" ;)

**Comment by rxhanson** [comment]
Closing this one out since the functionality that's not in the app is tracked by https://github.com/rxhanson/Rectangle/issues/177
