### ISSUE TITLE
Issue while transferring .plist

### ISSUE THREAD

**Issue by ladislas** [rxhanson/Rectangle#197]
macOS version: 10.15.6
Rectangle version: Version 0.30 (35)
logs (In Rectangle menu, hold option, "View Logging..."): n/a

In Catalina, copying the .plist from on computer to another, both running the same version of Rectangle doesn't set the same shortcuts. The file is rewritten when the app is launched.

https://github.com/rxhanson/Rectangle#preferences-storage

**Comment by ladislas** [comment]
So, after trying a few more times to copy my shared .plist, either from terminal or from Finder, and rebooting, I was able to get it to work. 

Not sure what did what though. If you have the working workflow like "turn of rectangle, delete the .plist, copy your .plist, reboot your computer, launch rectangle", that would be of great help :)

**Comment by rxhanson** [comment]
Thanks for the update. I can see this being a common issue where the better solution is something other than direct interaction with the plist or defaults. I'm going to close this one out and plan to implement https://github.com/rxhanson/Rectangle/issues/190 in a future release.

**Comment by ladislas** [comment]
Thanks!
