### ISSUE TITLE
Small space between iTerm2 windows

### ISSUE THREAD

**Issue by yochem** [rxhanson/Rectangle#2]
Thank you for this awesome project! I'm glad to see a Spectacle-based project that's actually actively maintained.

I noticed one issue though, there seems to be a small space around iTerm2.

### Versions
- MacOS: 10.14.5
- Rectangle: 0.1.2 (3)
- iTerm2: 3.2.9

### Screenshots
![image](https://user-images.githubusercontent.com/23235841/60808288-2df27780-a188-11e9-963c-f1220559bd6d.png)

The gap can be seen between the two windows, and to the right of the iterm2 window. There is no gap when using two Brave Browser windows next to each other. Do you think this is a Rectangle issue, or an iTerm2 issue?

Ps. When this project grows, will you think about adding an issue template? It's easier for you to get the information you need, and easier for people that fill in an issue to provide the information. I tried to provide as much as possible though :) 

Have a nice day,
@yochem

**Comment by rxhanson** [comment]
@yochem thanks for being an early Rectangle user! 

My thought for why this is happening is that iTerm2 will only resize in increments of character widths. According to a spectacle [issue](https://github.com/eczarny/spectacle/issues/280), you can change this setting in iTerm2 as follows:
`$ defaults write com.googlecode.iterm2 DisableWindowSizeSnap -integer 1`

In my testing, Spectacle, Magnet, and Rectangle all resized the iTerm2 windows identically, leaving the slight bit of space without that iTerm2 setting set.

There are some differences between Spectacle and Rectangle in terms of the logic here, so I find it interesting that they behaved the same for me. Namely, I left out a "quantized" window mover from Spectacle.

I'll probably close out this issue as "behaves as expected", unless you think it is behaving more differently from Spectacle than what I'm experiencing.


That's a good point on the issue template, I better get that in place. Thanks for including the details in your issue.

**Comment by yochem** [comment]
Thanks, the defaults command worked like a charm!

**Comment by ilyam8** [comment]
> According to a spectacle issue, you can change this setting in iTerm2 as follows:
> $ defaults write com.googlecode.iterm2 DisableWindowSizeSnap -integer 1

I am sure there are a lot of `iterm2` users and it would be nice to have this in the README, the bug is very annoying and an eyesore imo.
