### ISSUE TITLE
Firefox 79 does not respond to hotkeys anymore

### ISSUE THREAD

**Issue by cgrabenstein** [rxhanson/Rectangle#202]
macOS version: 10.15.6
Rectangle version: 0.31
logs (In Rectangle menu, hold option, "View Logging..."): _Empty_

With the latest update of Firefox to v79 the browser does not respond to any hotkeys anymore. I just downloaded version 78.0.2 to double check, and the hotkeys worked with the older version.

I also tried to use some rather obscure hotkey to avoid conflicts with a possibly newly added hotkey of Firefox, but it seems to be a general problem, not specific to any chosen hotkey.

**Comment by rxhanson** [comment]
Thanks for reporting. Firefox v79 is working fine for me. Typically these types of scenarios are out of control of anything that could be done from within Rectangle. You might want to try restarting Firefox v79 or macOS as well.

**Comment by cgrabenstein** [comment]
Amazing, restarting did the trick. Thanks for the hint, I will close this issue.
