### ISSUE TITLE
Slack (and others) do not respect resizing 

### ISSUE THREAD

**Issue by duffner** [rxhanson/Rectangle#203]
macOS version: 10.15.4
Rectangle version: .31
logs (In Rectangle menu, hold option, "View Logging..."): 

When trying to resize Slack, it does not respect any of the short-cuts.  Do you have any thoughts on this one? 

Also, I do not see the "View Logging" in the Menu, maybe this no longer exists, or possibly blind :)

**Comment by rxhanson** [comment]
Duplicate of https://github.com/rxhanson/Rectangle/issues/108

TLDR: Try restarting Slack or macOS, and make sure you didn't accidentally check "Ignore Slack" in the menu.

Logs aren't necessary for this one, but if it comes up in the future:
> In Rectangle menu, **hold option**, "View Logging..."

**Comment by nk9** [comment]
Restarting Slack worked for me.
