### ISSUE TITLE
Snapping issues with Preview

### ISSUE THREAD

**Issue by benjaminbogdanovic** [rxhanson/Rectangle#21]
macOS 10.15
MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)

When the sidebar is visible on Preview, it seems to overlap the windows when snapping. This is not the case when the sidebar is hidden. The cause seems to be that Preview will not allow the pdf to zoom out any further. I am not sure if anything can be done to mediate this?

Thanks in advance!

<img width="1275" alt="Screenshot 2019-10-14 at 20 38 18" src="https://user-images.githubusercontent.com/16837687/66778198-f56ae400-eec2-11e9-9cf3-5b2068427ac1.png">

**Comment by rxhanson** [comment]
Sorry for the delay, just had a chance to look at this. From my testing, this is just a matter of Preview's windows not being allowed to resize smaller - kind of annoying that they would set such a wide min width. Rectangle doesn't have the ability to resize a window to be any smaller than the size you can manually resize a window.

With that said, the app Magnet shows a small popup window that says when a window can't be resized to be more narrow, and that feature might be a welcome addition to Rectangle. I'm going to close this issue, but I may add a new one to track the explanatory window.
