### ISSUE TITLE
"The Key Combination Shift+Command+F cannot be used..."

### ISSUE THREAD

**Issue by JacobTaylor-RCC** [rxhanson/Rectangle#211]
macOS version: 10.14.6
Rectangle version: 0.32
logs (In Rectangle menu, hold option, "View Logging..."): no log entries

See included screenshot. That combination is not bound, I both deactivated the binding in the OSX keyboard menu part of system settings and also totally cleared the binding. This is the shortcut I used with Spectacle, but rectangle blocks its use. I also restarted rectangle just in case it didn't stick without a restart. Halp?

<img width="419" alt="Screen Shot 2020-09-01 at 17 30 15" src="https://user-images.githubusercontent.com/39351909/91918911-30ac0800-ec79-11ea-9ac0-ada038efa337.png">

**Comment by rxhanson** [comment]
Just check the box for "Allow any keyboard shortcut" in the settings tab of the prefs window.

**Comment by JacobTaylor-RCC** [comment]
oh! Got it, thank you.

**Comment by vanderhoop** [comment]
For anyone else who stumbles on this issue with newer versions of Rectangle, just a heads up that the option you need to engage has been renamed to 'Remove keyboard shortcut restrictions'. 

Rectangle version: 0.57

**Comment by alichtman** [comment]
> The option you need to engage has been renamed to 'Remove keyboard shortcut restrictions'.

This option is in the **Rectangle** settings, not macOS settings.
