### ISSUE TITLE
Space between vertical windows

### ISSUE THREAD

**Issue by Fossil01** [rxhanson/Rectangle#213]
macOS version: 10.15.6
Rectangle version: 0.32
logs (In Rectangle menu, hold option, "View Logging..."): Empty

I just installed Rectangle instead of Magnet because when using Magnet I always had too much space between two windows verically stacked. But now Rectangle has the same issue, I am wondering if this is OS related and how I would go about fixing it?

https://imgur.com/a/CWMNqfm

You can see the screenshot above. Left window is browser, full height. On the right my terminal (black) and database manager vertically stacked. The orange you see if my desktop wallpaper.

**Comment by rxhanson** [comment]
Are you using iTerm2? If so, try the command here: https://github.com/rxhanson/Rectangle#window-resizing-is-off-slightly-for-iterm2

Quoted from a stackexchange question: 
> Terminals have a fixed character width and height, and most (all?) terminal application programs make the window an even multiple of that size (then add the window title, some margin around the sides, etc.), so there will never be a partial row or column visible.

I don't know the setting for Terminal to achieve the same as that defaults command for iTerm, but there's probably some setting for it.

**Comment by Fossil01** [comment]
iTerm 2 indeed. I did not see that paragraph in the readme before :-) It works perfectly now, cheers.
