### ISSUE TITLE
Option to not revert window to previous size when unsnapping

### ISSUE THREAD

**Issue by WhiteMac** [rxhanson/Rectangle#216]
Hello, currently when I unsnap a window with Rectangle it reverts to its pre-snapped size. Sometimes I snap a window just to get it to a certain size quickly but then I want to move it around my screen and not necessarily keep it anchored to an edge. A snapping tool I used prior to Rectangle had a setting for whether unsnapped windows should be reverted to previous size or not. I'd love to see that option in Rectangle too.

Thank you.

**Comment by rxhanson** [comment]
You can disable this with a terminal command.
https://github.com/rxhanson/Rectangle#disabling-window-restore-when-moving-windows

If anyone's interested in contributing, this would be a simple first issue to implement. The only catch is that I'd only look to merge a PR that is localized (preferably using [DeepL](https://www.deepl.com/translator)).

**Comment by WhiteMac** [comment]
I've enabled the setting, thank you! Apologies for not exploring the Terminal commands.

**Comment by rxhanson** [comment]
This is now available as a checkbox in the settings in v0.34.
