### ISSUE TITLE
[KR] Some letters of welcome title are cut off

### ISSUE THREAD

**Issue by sboh1214** [rxhanson/Rectangle#217]
macOS version: 11.0 beta(20A5354i)
Rectangle version: v0.32(37)
logs (In Rectangle menu, hold option, "View Logging..."): It is not needed

I'm Korean user, and as the title and picture as follows, some letters of welcome title are cut off.
It seems to be 
`/* Class = "NSTextFieldCell"; title = "Welcome to Rectangle!"; ObjectID = "kYm-Ye-gOR"; */
"kYm-Ye-gOR.title" = "Rectangle에 오신 것을 환영합니다!";`

However, it shows only "Rectangle에 오신 것을 환영".

Thanks.

<img width="402" alt="스크린샷 2020-09-06 오후 4 15 03" src="https://user-images.githubusercontent.com/30364442/92320496-d934e000-f05c-11ea-99e9-3131975aef0f.png">

**Comment by rxhanson** [comment]
Thanks for reporting! I'll put a fix in for this in the next release.

**Comment by rxhanson** [comment]
This should be fixed in [v0.34](https://github.com/rxhanson/Rectangle/releases/tag/v0.34). (However, all the new items in v0.34 have not been localized yet).

Closing this one out, but feel free to comment or open a new issue if something else comes up.
