### ISSUE TITLE
Proposal: Making "Launch on login" the default?

### ISSUE THREAD

**Issue by cpsauer** [rxhanson/Rectangle#218]
First and foremost: thanks for making something so useful and sharing it with the world :)

I was wondering if you'd consider making "Launch on login" the default. It's easy enough to enable when you know it's there, of course, but I'm asking for others, like, say, my parents who'd install hoping to have snapping by default across the OS--and be surprised to find that it had gone away after they restarted their machine. Seems like it's the default across other window management apps for this reason.

Thanks for your consideration,
Chris

**Comment by rxhanson** [comment]
Makes sense to me. This has been the behavior mainly to align with an Apple design guideline I read a long time ago. Since Rectangle's not on the App Store, I think it's acceptable to make the change.

**Comment by rxhanson** [comment]
Launch on login is now enabled by default in [v0.34](https://github.com/rxhanson/Rectangle/releases/tag/v0.34), in the scenario that the app has not been launched before.

Closing this one out, but feel free to comment or open a new issue if it's not working properly on a fresh install of v0.34.
