### ISSUE TITLE
Right and bottom thirds not working

### ISSUE THREAD

**Issue by esambo** [rxhanson/Rectangle#22]
Thanks for creating a Spectacle replacement, what works better on macOS Catalina.

### Correct Behavior
Resizing multiple times to `Left Half` or `Top Half` work fine, with:
1. `1/2`
2. `2/3`
3. `1/3`

### Bug
But resizing multiple times to `Right Half` or `Bottom Half` doesn't work the same, and does:
1. `1/2`
2. `1/2` towards the middle of the screen at starting at the `2/3` location, but it doesn't touch the side of the screen anymore!
3. no 3rd resize option at all, and starts up with `1/2` again!

**Comment by stgarf** [comment]
@esambo I can confirm similar issues. Do you have multiple monitors?

Bottom half definitely has some bug where it refuses to resize it sometimes (seems after I test some other half that this is triggered).

Right and bottom half also do this weird thing where they seem resize partially on another display before snapping back to the proper display.

Here's a GIF repoducing the issue for Right and Bottom a few times:
https://media.giphy.com/media/Yq8OP167KODHCJhcOZ/giphy.gif (sorry for the potato quality, I think giphy downsampled).

**Comment by esambo** [comment]
Yes, I noticed it with multiple monitors, but it has the same problems with just my MacBook Pro. Playing around with it some more definitely shows several other screen resizing issues, where it sometimes doesn't even go down at all. A verbose log file with the entered keyboard shortcut combinations and the current and the newly calculated window coordinates might be helpful for troubleshooting

**Comment by rxhanson** [comment]
This would most likely be fixed by the fix for https://github.com/rxhanson/Rectangle/issues/19 (not complete yet). The existing logic for determining if 1/3 or 2/3 should be executed is dependent on window size/pos fitting exactly the calculated rectangle, and that's not a guarantee depending on an app or size of screen. If https://github.com/rxhanson/Rectangle/issues/19 doesn't fix it, we can dig into it deeper. 

I might add a debug logging mode, but it probably won't make it into the next release.

**Comment by rxhanson** [comment]
Try this version: https://github.com/rxhanson/Rectangle/releases/tag/v0.9
It has updated behavior from https://github.com/rxhanson/Rectangle/issues/19 that should fix at least some of the behavior that you're seeing. My guess is that you might still see some issues, so it'll accelerate getting a debug logging mode in place. In the meantime, @esambo, what apps are you seeing this with, and what's your screen resolution?

**Comment by esambo** [comment]
@rxhanson Version 0.9 doesn't seem to work at all for _right_ or _bottom_ 1/2, 1/3, 2/3, as the `Right Half` or `Bottom Half` seems unable to move the window to that side, and even if I move it there with `Move Right` or `Move Down`, the `Bottom Half` or `Right Half` just move the outside edge of the window, instead of the inside one!

**Comment by rxhanson** [comment]
@esambo can you send a video?

**Comment by esambo** [comment]
@rxhanson I don't have time trying to convert it into a GIF. Can I email it to you? My email is the same username on GMail as on GitHub

**Comment by rxhanson** [comment]
@esambo thanks for the video. That's some bizarre behavior, no doubt. Silly question: are you positive that no other window manager apps are running at the same time? 

My next task is debug logging mode. I'll post back here when it's ready.

**Comment by rxhanson** [comment]
Also, is the behavior identical when selecting window actions from the menu?

**Comment by esambo** [comment]
1. 👍 on a verbose logging output with a debug log level. (Perhaps have a preference option to enable/disable it?) It would be nice to log:
    - timestamp
    - keystrokes (or at least the action being taken, based of the keystroke)
    - current window coordinates, or location & dimension
    - newly calculated window coordinates
2. Yes, I only have Rectangle.app running. Quitting it causes no window resizing to occur at all anymore, until I start it up again.
3. Yes, using the Rectangle.app menu bar menu entries to select `Bottom Half` (or any of the other `* Half` options) has the same resizing problems.

**Comment by esambo** [comment]
I just installed the latest macOS Catalina 10.15 Software Update (Build `19A602`) and restarted my MacBook Pro. It is now working fine!

**Comment by rxhanson** [comment]
If you don't mind me asking, which version of macOS were you on before? Seems like there was a coordinate system inversion between the two versions.

**Comment by esambo** [comment]
I must have been on the [Original Software Update release (Build `19A583`)](https://en.wikipedia.org/wiki/MacOS_Catalina#Releases) of macOS Catalina.
But I don’t restart my MacBook Pro unless I have too, so I probably hadn’t rebooted since that original Catalina upgrade. 
I am therefore not sure if a simple upgrade might have fixed it too... I’m sorry that I didn’t give that a try first.

**Comment by rxhanson** [comment]
Thanks for letting me know. At the very least, I'm glad that it's working properly! I'm just adding in debug logging now, so in the future if you run across anything we can just set a flag and see better what's going on.
