### ISSUE TITLE
Window Previews

### ISSUE THREAD

**Issue by Onyx808** [rxhanson/Rectangle#222]
I have switched from HyperDock and love Rectangle, however one feature that I do miss is the window previews, is there a way to accomplish it?

Thank you!

**Comment by rxhanson** [comment]
Thanks for posting. This feature is kind of outside of the scope of what I would look to add into Rectangle. 

Closing this one out since I have no plans to implement it, but if anyone is interested in creating a pull request for it then I would definitely consider it.
