### ISSUE TITLE
Option to select keybinds on first load, but can't choose Rectangle/Spectacle afterwards

### ISSUE THREAD

**Issue by jasikpark** [rxhanson/Rectangle#223]
macOS version: 10.15.4
Rectangle version: 0.32 (37)
logs (In Rectangle menu, hold option, "View Logging..."): N/A

So basically I want the ability to reset my keybinds to either Rectangle or Spectacle keybinds

**Comment by jasikpark** [comment]
ah - maybe make the cli more obvious from settings?

**Comment by rxhanson** [comment]
If you click Restore Default Shortcuts, then it'll let you pick again (I'll update the readme).

**Comment by jasikpark** [comment]
Oh, ok i just did the command line setting

**Comment by prufrock123** [comment]
@rxhanson - Just wondering if you are able to update the readme with the "restore default shortcuts" tip?  Thanks!
