### ISSUE TITLE
Zsh shows error when changing the window sizeOffset 

### ISSUE THREAD

**Issue by MrNotch9** [rxhanson/Rectangle#224]
macOS version: 10.5.6
Rectangle version: 0.32(37)

I wrote this code in the terminal ``defaults write com.knollsoft.Rectangle sizeOffset - float <60>``
but it showed me this error ``zsh: parse error near `\n'``. I tried the same code on my other mac and it worked.

**Comment by rxhanson** [comment]
Try this:
`defaults write com.knollsoft.Rectangle sizeOffset -float 60`

**Comment by MrNotch9** [comment]
it worked thanks
