### ISSUE TITLE
Add spacing option

### ISSUE THREAD

**Issue by saschaeggi** [rxhanson/Rectangle#225]
I love Rectangle and it replaced Magnet for me.

I know you're not accepting any new feature request but maybe you still have an ear for this idea: it would be very cool to set an offset in the settings (spacing) for Windows. so that Windows don't go edge-to-edge but would have a spacing between them. See example:

Without spacing:
<img width="3360" alt="without_spacing" src="https://user-images.githubusercontent.com/5558166/93304884-053f2680-f7fe-11ea-9d0e-f47ca15574c7.png">

With spacing option:
<img width="3360" alt="with_spacing" src="https://user-images.githubusercontent.com/5558166/93304896-0a9c7100-f7fe-11ea-8dd0-24bf2e1f2c17.png">

This would be a great enhancement setting.

Keep up the good work & Thanks for considering,
Sascha

**Comment by rxhanson** [comment]
https://github.com/rxhanson/Rectangle#adding-gaps-between-windows

**Comment by saschaeggi** [comment]
How could I oversee this? So awesome! 
Maybe we can have this as a setting in the preferences as well? 💪💙😍

**Comment by rxhanson** [comment]
I think I will add this in as a preferences setting in a future release. I have avoided it so far to keep the prefs simple (and avoid yet another thing that has to get localized).
