### ISSUE TITLE
Adding a 3x2 split

### ISSUE THREAD

**Issue by larsen161** [rxhanson/Rectangle#227]
Hopefully this possible not a feature request. I didn't find a better way to ask a question if there is a support forum please let me know.

**Rectangle can do this**
![Screen Shot 2020-09-16 at 6 32 43 AM](https://user-images.githubusercontent.com/1272692/93332541-99ea5a00-f7e7-11ea-8e0f-74620e9c10c8.png)

**Can it do this?**
![Screen Shot 2020-09-16 at 6 32 56 AM](https://user-images.githubusercontent.com/1272692/93332578-a5d61c00-f7e7-11ea-9d36-947787819fa2.png)

**Comment by rxhanson** [comment]
No worries on posting a question here. It isn't available right now, but I'm implementing it for the next release. Here's the issue that's tracking it:
https://github.com/rxhanson/Rectangle/issues/177
