### ISSUE TITLE
Automatic placement of windows by type or title

### ISSUE THREAD

**Issue by medisoft** [rxhanson/Rectangle#229]
It would be nice to have a way to configure certain type of window by application or title to be placed on specific location and size automatically

For example, I want that when I open telegram and skype, telegram to be in the left/bottom part of the screen, and skype left/top.

**Comment by MrNotch9** [comment]
+1 
I'd also like that when I press a hotkey, it snaps certain apps to their allocated space

**Comment by rxhanson** [comment]
I don't have plans to add this into Rectangle, so I'm going to close this one out. 

If someone creates a pull request with this functionality in it, then I would consider it.
