### ISSUE TITLE
Feature Request: Useless Gaps

### ISSUE THREAD

**Issue by adamalbrecht** [rxhanson/Rectangle#23]
On larger screens, many find it aesthetically pleasing to have gaps between tiled windows. Several other window managers support this and I would love to see this added as an option to Rectangle.

There has been some discussion of this (including a patch) in the Spectacle issue tracker, which has since been removed. [But here is a cached version for reference](https://webcache.googleusercontent.com/search?q=cache:eH9MY-QJw14J:https://github.com/eczarny/spectacle/issues/290+&cd=1&hl=en&ct=clnk&gl=us&client=safari).

Thanks for the great work!

**Comment by rxhanson** [comment]
Sorry, I'm not accepting any feature requests at this time (see [CONTRIBUTING.md](https://github.com/rxhanson/Rectangle/blob/master/CONTRIBUTING.md)). I would consider a pull request for this feature, as it's something that can be done via NSUserDefaults without having to clutter the UI, but I have no plans to implement it.

**Comment by rxhanson** [comment]
Alright, useless gaps are in https://github.com/rxhanson/Rectangle/releases/tag/v0.17

Let me know if you get a chance to test it out.
