### ISSUE TITLE
How to disable animations between sizing?

### ISSUE THREAD

**Issue by theronic** [rxhanson/Rectangle#234]
Recently switched to Rectangle from Spectacle. How can I disable the animation between resizing?

Animations in MacOS have [drawn some ire](https://apple.stackexchange.com/search?q=disable+animations+%5Bmacos%5D) over the years for not being optional. It would be nice for the delay to be optional in Rectangle, or very fast. Additionally, it uses more battery to trigger intermediate reflows of complex UIs.

**Comment by rxhanson** [comment]
Rectangle does not perform resizing animation. If you're experiencing animation, then you're most likely experiencing a macOS bug as noted in the [readme](https://github.com/rxhanson/Rectangle#window-movingresizing-appears-animatedsmooth-instead-of-quick-and-windows-dont-end-up-where-you-expect).

This has been reported a number of times - https://github.com/rxhanson/Rectangle/issues/165 is the only issue I've left open for it at this time.

The behavior should have been the same for you with Spectacle as it is with Rectangle.

**Comment by rxhanson** [comment]
(Closing this one out since there's nothing further that can be done for this in Rectangle)
