### ISSUE TITLE
Window width 1/2 -> 1/3 -> 2/3 toggle

### ISSUE THREAD

**Issue by vascopimenta** [rxhanson/Rectangle#246]
I'd like to vote for/request a behaviour that was present in Spectacle that I think was handier than the way it is currently implemented in Rectangle.

In Spectacle, the same shortcut would toggle through defining a window as (for example) left half, left third, left two-thirds.
This is, IMHO, simpler and easier to remember than having to define three shortcuts for the three widths. Then add the same for right hand side, all four corners, etc., and you see where I'm going with this.

Thank you for this great piece of software.

**Comment by rxhanson** [comment]
Uncheck the box "Cycle across displays..." in the settings tab of the preferences window.

**Comment by vascopimenta** [comment]
Silly me. @rxhanson. Thank you.
