### ISSUE TITLE
Snap area preview enhancement

### ISSUE THREAD

**Issue by R0LA1mRifcF8yAkk** [rxhanson/Rectangle#249]
Hey, I am coming from Magnet, which I bought some years ago. Magnet and Rectangle are basically identical, except Rectangle has more features, which is great.

There's only one thing that was slightly better in Magnet, and that's the preview box that appears when you drag a window to a snap area. It had slight fading animations when they appeared/disappeared and the borders were a bit more pronounced. Right now, aliasing is rough on the corners of the preview box.

That's all, not sure if it's a feature quest rather than an enhancement request. It would make the whole thing feel polished, in my opinion.

**Comment by rxhanson** [comment]
Good feedback, thanks! 

I haven't touched that part of the app in quite some time, so I'll plan on taking a look at this one soon.

**Comment by R0LA1mRifcF8yAkk** [comment]
That's great to hear, I'm glad you're considering this.

Would screenshots or recordings help? Or would that be a bit too close to plagiarism? Or maybe you want creative freedom instead, haha?

**Comment by R0LA1mRifcF8yAkk** [comment]
Just updated and it looks great, thanks! I suppose you can close this now.

**Comment by rxhanson** [comment]
Thanks for testing it out and letting me know!

**Comment by R0LA1mRifcF8yAkk** [comment]
I've encountered a visual bug when switching from one "footprint" window to another, e.g. drag a window between 2/3 and 1/3 spots so the footprint stays on screen.

I'm not sure if it's deliberate but there's no animations this way. It'd be nice to have them fade in those cases as well.

**Comment by rxhanson** [comment]
I see what you mean. Right now the fade is only on footprint show/hide, not on resize. When I revisit this part of the code again, I'll see what I can do.
