### ISSUE TITLE
Top snapping opens Mission Control

### ISSUE THREAD

**Issue by zhiayang** [rxhanson/Rectangle#250]
macOS version: 10.15.7
Rectangle version: 0.35 (40)

When dragging a window to the top edge, most of the time it will instead open the mission control view if i stay there too long (and by too long, it's like 0.5s?). It's quite hard to use top-edge snapping with this behaviour.

I haven't found a way to disable this in macOS itself, so is there a possibility to work-around this in Rectangle?

thanks.

**Comment by rxhanson** [comment]
Although there is probably something that could be done on Rectangle's side to change some of this behavior, it's not something I plan on adding in.

Mission control is displayed either when the velocity of the window drag is faster than a certain threshold, or if you continue to move the cursor up when it is at the top. 

My first recommendation is to just move with a lower velocity or when you reach the menu bar, or to stop once you reach the top. 

My second recommendation is that you can adjust the margin for the top snap area and make it larger, with the terminal command listed at [Changing the margin for the snap areas in the readme](https://github.com/rxhanson/Rectangle#changing-the-margin-for-the-snap-areas).

Typically, I don't like to tell a user to change what they're doing to match the behavior of the app, but this is a scenario where that is by far the better option than changing macOS behavior or trying to compensate by adjusting the app's behavior in a way other than adjusting the snap area margins.

**Comment by zhiayang** [comment]
Ah, that's understandable. Increasing the margin a bit greatly reduces the chances of it happening, thanks!

**Comment by raxigan** [comment]
If someone is still looking for a decent solution you can try [my hammerspoon script](https://gist.github.com/raxigan/aa2b840c9cce8b4b578d7ee6d0c7e8d9)
