### ISSUE TITLE
Spectacle style shortcuts

### ISSUE THREAD

**Issue by cjh9** [rxhanson/Rectangle#252]
Hi!

It would be nice to allow spectacle-style shortcuts so you don't have to remember so many shortcuts.

For instance: Ctrl + Command + Left
1st time press: Resize to half screen to the left.
2nd time press: Resize to 2/3 of screen to the left.
3rd time press: Resize to 1/3 of screen to the left.

This actually simplifies the application, right now there are too many shortcuts for all the different settings... Check on spectacles preferences, there are fewer settings there. Just some thoughts, this is preventing me to switch to rectangle :)

**Comment by rxhanson** [comment]
Uncheck the box for "Cycle across displays..." in the settings tab.
