### ISSUE TITLE
Spanish translation is incomplete despite the translation being complete in the code

### ISSUE THREAD

**Issue by berman00** [rxhanson/Rectangle#254]
macOS version: 10.15.7
Rectangle version: v0.36(41)
logs (In Rectangle menu, hold option, "View Logging..."): Non aplicable

Some strings in the the spanish version aren't translated, eg: "Restore window size when unsnapped"
I've checked the localization files, and all the strings seem to be correctily translated in the file: .../es.lproj/Main.strings, however, some of the translations, including the ones I experienced, are missing in the file .../es-419.lproj/Main.strings.

My best guess is that rectangle is using _es-419.lproj_ for the spanish translations, when it should be using _es.lproj_.

**Comment by rxhanson** [comment]
Thanks for reporting. When I test with Spanish, the proper translations are displayed. 

MacOS selects the translation file to use based on your machine localization, not Rectangle (or any other app). What is your specific localization?

**Comment by berman00** [comment]
@rxhanson  Not sure were to chenck that. Best I can do is tell you that I have the region set to Argentina and language set to Spanish(Argentina). Hope that helps

**Comment by rxhanson** [comment]
es419 is "Spanish (Latin America)"

If the regular Spanish ones are identical or good enough, I can just copy those over to es419.

**Comment by berman00** [comment]
@rxhanson they seem good enough to me. Very glad you figured out so quickly. Take care!

**Comment by rxhanson** [comment]
Copied over es into es-419 and will close this issue once it gets released.

**Comment by rxhanson** [comment]
Now released in [v0.37](https://github.com/rxhanson/Rectangle/releases/tag/v0.37).
