### ISSUE TITLE
Window loses focus when moving it to the next display with a fullscreen app

### ISSUE THREAD

**Issue by artberryx** [rxhanson/Rectangle#255]
macOS version: 10.15.7 (Catalina)
Rectangle version: 0.36 (41)
logs (In Rectangle menu, hold option, "View Logging..."): 

When I attempt to move a window to the next display with a fullscreen app, it loses focus.

In the case of Magnet, it automatically focuses on the moved window.

I am not sure if this is a bug or desired behavior, but I would appreciate it if it could be fixed.

**Comment by rxhanson** [comment]
I put a fix in for this in [v0.37](https://github.com/rxhanson/Rectangle/releases/tag/v0.37). It now behaves the same as Magnet from what I can tell. 

There is an edge case with apps when you have multiple windows of the same app open where it's possible to still have windows hidden from view. This is present on Magnet as well, and there's not an elegant way to address this from my perspective. 

Closing this one out, but feel free to comment or reopen if you still have issues with v0.37.

**Comment by artberryx** [comment]
I appreciate your quick reply.

But the issue has not been resolved though I tried updating Rectangle to v0.37(42) and restarting my laptop.

The aspects of the issue can be reproduced as follows:
1. Monitor 1 (left) shows a fullscreen app (it is not showing the menu bar).
2. Monitor 2 (right) shows a windowed app.
3. When I enter Ctrl + Option + Command + Left Arrow on the windowed app on Monitor 2, it disappears.
4. However, I can find the moved window on the Mission Control of Monitor 1. That is, I have to manually focus on the non-fullscreen pane on Monitor 1 to expose the moved window.
5. In the case of Magnet, it makes the pane move so that it automatically focuses on the moved window.

**Comment by rxhanson** [comment]
Hmm. This is the behavior that I implemented in 0.37, and it works for me. It's possible that there's an edge case that I'm unaware of. In the next release, I'll have to add some logging to see why it wouldn't work for you.

**Comment by artberryx** [comment]
An update on this issue: It works well after updating my macOS to Big Sur from Catalina 🎉 .
