### ISSUE TITLE
Moving to edges also changes the unrelated {x,y} coordinate

### ISSUE THREAD

**Issue by evancharlton** [rxhanson/Rectangle#263]
I don't know whether this is a bug or a feature -- it was unexpected behavior to me, so I saw it as a bug. However, maybe the current implementation is a feature. If this is the case, then this request is a feature.

# Situation

1. Open a new Finder window
1. Manually resize this window to be some arbitrary size (let's say 500px x 500px)
1. Manually drag this window to the bottom-left-ish corner. Not snapped to an edge, but also not centered vertically.
1. Use the Rectangle feature for "Move to Edge > Move Right"

# Outcome
 - The window's size is unchanged (great!)
 - The window is snapped to the right edge (great!)
 - The window is vertically centered (unexpected!)

If I then use the "Move to Edge > Move Up" feature, I would expect the window to be in the top-right corner. Instead, it winds up centered on the top edge.

Based on the thumbnails in the UI, this is a feature. However, it's pretty unexpected behavior for me -- I was expecting a translation of the window along only one axis.

![image](https://user-images.githubusercontent.com/418560/98929582-a33c2e00-24db-11eb-8c9c-12e8d4106646.png)

Thoughts?

**Comment by rxhanson** [comment]
You can change this behavior with a terminal command:

https://github.com/rxhanson/Rectangle#move-updownleftright-dont-center-on-edge

I agree, the standard behavior should be not to center it. I will most likely change the default behavior in a future release.

**Comment by evancharlton** [comment]
Oh that's great! If I find myself bored some weekend, maybe I'll use this as an excuse to learn OSX development and send you a PR!

Thanks for the tip about the command to change it.
