### ISSUE TITLE
Icon style Big Sur

### ISSUE THREAD

**Issue by giovannimariacusaro** [rxhanson/Rectangle#266]
It's not a bug, but a suggestion / inspiration for an icon that maintains its identity but adapts to the style of MacOS Big Sur.
Free to download, duplicate and modify this figma project:
https://www.figma.com/file/3HhSm5XpH7mGkFrN7hljFO/Rectangle-icon?node-id=1%3A2

**Comment by rxhanson** [comment]
This is awesome, thanks! I can't think of any changes to suggest to it. I will roll it into the next release.

**Comment by giovannimariacusaro** [comment]
@rxhanson thanks!
I am happy that half an hour of this boring Sunday in lockdown in Italy was productive!
The file has a very simple structure if you or anyone want to make changes in the future.

**Comment by rxhanson** [comment]
Released! https://github.com/rxhanson/Rectangle/releases/tag/v0.38
