### ISSUE TITLE
Fixed corner grids

### ISSUE THREAD

**Issue by sumgr0** [rxhanson/Rectangle#268]
Thank you for the amazing tool.

Allow to fix the borders in the Rectangle preference, to avoid app window covering that grid space.

This can be helpful when using Geektool setup to ensure no overlap of window on the background widgets or desktop folder row.

Hope this can be helpful for the community.

**Comment by sumgr0** [comment]
Example: I've got this widget for Network information using Geektool. When snap the windows to the left corner, it cover the information. If I can fix the grid to avoid windows being snap in that corner, the information is always accessible.
![image](https://user-images.githubusercontent.com/11391119/99550520-cfc2df00-29e0-11eb-8885-976f34e074f8.png)

**Comment by rxhanson** [comment]
I believe what you're looking for is this:
https://github.com/rxhanson/Rectangle#setting-gaps-at-the-screen-edges

**Comment by rxhanson** [comment]
Housekeeping; closing this one out since I think it is functionality that's already included in the app.
