### ISSUE TITLE
PreferenceDialog: Description text for hiding menu bar is not displayed completely in Japanese

### ISSUE THREAD

**Issue by ryonakano** [rxhanson/Rectangle#273]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: High Sierra
Rectangle version: 0.38

![スクリーンショット 2020-11-24 9 37 40](https://user-images.githubusercontent.com/26003928/100031360-cf8b6f00-2e38-11eb-81d3-f19d4b4eb451.png)

The underlined translation is cropped and not completely shown. The translated string here is "メニューバーのアイコンが非表示の場合にメニューを開くには、FinderからRectangleを再起動**してください。**" and we're missing the last part "**してください。**" here. I expect this sentence should be wrapped and all of it should be displayed.

**Comment by fabifabulous** [comment]
This is happening for the German translation as well. If you go back to the "page" where the shortcuts are listed and click on the little arrow (>) that expands and shows the advanced shortcuts for Thirds, Fourths and Sixths and than go back to the "gear icon" the text is displayed completely.

**Comment by rxhanson** [comment]
Thanks for reporting. I'll fix this for the next release.

**Comment by ryonakano** [comment]
![スクリーンショット 2020-12-11 13 54 54](https://user-images.githubusercontent.com/26003928/101865006-7baeb300-3bb8-11eb-8fb2-0ec22a230dfe.png)

This issue was fixed in 052d995. Thank you for your fix @rxhanson! :tada:
