### ISSUE TITLE
Microsoft OneNote ignoring Rectangle

### ISSUE THREAD

**Issue by macbikegeek** [rxhanson/Rectangle#275]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Catalina 10.15.7
Rectangle version: 0.30 (35)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):  no log data shown in logging window
OneNote version 16.44 (20111807)

Microsoft OneNote used to work with Rectangle. Something changed with a recent update and it seems to be ignoring Rectangle. Keyboard shortcuts get system alert tone and nothing happens. All resizing options in Rectangle menu are grayed out.

**Comment by rxhanson** [comment]
Thanks for reporting. 

My guess is that Rectangle is unable to obtain the accessibility element of the OneNote window. This is commonly reported with Electron based apps, like VSCode. 

If you restart OneNote, does the problem still persist? That's been the solution for the other apps, like VSCode.

If the issue persists, my recommendation is to file an issue with the OneNote team. There's not really anything logical that could be done from Rectangle's side, so I'm going to close this one out.

**Comment by macbikegeek** [comment]
Hi Ryan,

Thanks for the quick response. A restart fixed it but Interesting because it was just restarted after an update. Good to know for the future. First time I’ve seen it happen.

Best,
Lee
