### ISSUE TITLE
Laggy window (Open Core)

### ISSUE THREAD

**Issue by b4nst** [rxhanson/Rectangle#278]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.0.1 (20B50)
Rectangle version: v0.38

_Disclaimer: I know this a somehow wild configuration, so I do not expect much works on this issue unless it's a quick fix._

When using Rectangle on my Mac Pro 5,1 (Open Core 0.6.3, rx580 GPU) moving the windows around is not fluid anymore. It's very likely links to the hardware, since it's running just fine on my 2020 MBPro. If you guys/girls have any idea of the root cause or how to find it, I'm willing to help.

**Comment by rxhanson** [comment]
I think what you're experiencing on your Mac Pro is the macOS bug: https://github.com/rxhanson/Rectangle#window-movingresizing-appears-animatedsmooth-instead-of-quick-and-windows-dont-end-up-where-you-expect

Here's the issue that I've left open for it: https://github.com/rxhanson/Rectangle/issues/165

Let me know if that's not it.

**Comment by b4nst** [comment]
I'm not sure, that may be the case indeed. I may have misunderstood the issue when I first read it. In my case resizing windows with Rectangle works just fine. it's just when I move them around and this is not "animated" and definitively not "smooth" at all. It's the same feeling than a low FPS game. But maybe that's exactly what is described and I just didn't understand it well.

**Comment by rxhanson** [comment]
This issue has a short video that shows the "animated" window movement: https://github.com/rxhanson/Rectangle/issues/29

If you want to add a quick video, it should be pretty easy to tell if it's this. You could also just run the on-screen keyboard on either mac and compare, since that always reproduces this issue for me. 

Outside of this issue, there might not be anything I can do from Rectangle side. Rectangle just tells the accessibility API in macOS what size and location to set for a window. But, I definitely won't rule anything out.

**Comment by rxhanson** [comment]
v0.40 has a fix for the "animated" window movement. Does your open core still have issues on v0.40?

**Comment by b4nst** [comment]
Nope, I can still reproduce the issue on open core with v0.40

**Comment by rxhanson** [comment]
Thanks for reporting back. As mentioned, I am pretty certain this is outside the realm of what can be done in Rectangle, but if you want to attach some logs then I'll see if there's anything abnormal (hold option in the menu and click view logging).

**Comment by rxhanson** [comment]
Just doing some housekeeping and closing out issues that aren't actionable from Rectangle side. If anything on this changes feel free to comment.

**Comment by b4nst** [comment]
Yup, totally agree with you. As I said opening this issue, it's an odd configuration and I don't expect Rectangle to fix macOS issues.
