### ISSUE TITLE
Ignored apps are not receiving keypress events from shortcuts

### ISSUE THREAD

**Issue by solkaz** [rxhanson/Rectangle#28]
If I have an application that Rectangle is ignoring, and I try to use a shortcut in the app that matches a shortcut in Rectangle, the app will not receive the key combo. For example, I'd like to use `Cmd+Option+<Arrow Up>` within Visual Studio Code, which is also a shortcut set in Rectangle; although I have toggled "Ignore Code" to true, the action is not registered to VSCode, but the window also doesn't resize. Spectacle had this feature, which I would appreciate, as otherwise I have to quit Rectangle for in-app shortcuts to work properly.

**Comment by rxhanson** [comment]
I’m away from my mac this week but will queue this one up for next release when I return.

**Comment by rxhanson** [comment]
Try this out and let me know if it works properly. If it's good, then I'll put it on the update channel.

https://github.com/rxhanson/Rectangle/releases/tag/v0.10

**Comment by solkaz** [comment]
It is working, thank you so much! ❤️

**Comment by michaeljohnbennett** [comment]
how do you do an ignore? I can't see it in any options or docs.

**Comment by rxhanson** [comment]
@michaeljohnbennett: https://github.com/rxhanson/Rectangle/issues/47
