### ISSUE TITLE
Can't open Rectangle in 0.39 (and 0.38)

### ISSUE THREAD

**Issue by achou11** [rxhanson/Rectangle#282]
Just updated to the [latest release](https://github.com/rxhanson/Rectangle/releases/tag/v0.39) (via Homebrew) and now I can't open the application. Tried downloading via the .dmg directly but had the same issue.

EDIT: Also seems to be an issue for 0.38. I tried installing that release manually and ran into the same error. Installing 0.37 had no issue and works as expected

![image](https://user-images.githubusercontent.com/18542095/101229151-d1410800-366c-11eb-9c76-6c5b1c5ce21d.png)

- [X] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 10.15.7 (Catalina)
Rectangle version: 0.38 and 0.39
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):

**Comment by rxhanson** [comment]
v0.38 and v0.39 are both universal binaries (for supporting Intel & M1). Have you had any issues with other universal binary apps? 

I'm in an awkward situation where I don't have access to a Catalina install to test anything out. My bootable Catalina image is no longer bootable.

**Comment by achou11** [comment]
Ah that would make sense. Not sure I've explicitly downloaded any other universal binaries, although I have apps that have updated to versions to support both architectures (don't think I've run into issues with those).

**Comment by JamesSlalom** [comment]
I'm having the same issue, it appears to launch on startup. But won't re-open/resume after sleep.

**Comment by achou11** [comment]
Looks like this is no longer an issue after installing 0.40

Not sure what happened but hopefully doesn't show up again 😄
