### ISSUE TITLE
Feature request/preview: Enlarged pixel threshold to trigger snap by dragging

### ISSUE THREAD

**Issue by Simon-Tang** [rxhanson/Rectangle#298]
Rectangle works very well for me, however having two monitors makes it harder to snap windows in the centre regions by dragging, since the cursor can't "collide" with the edge of either display for snapping.

I think this could be made easier if the snapping margins were easier to hit for cross-display borders. The simplest solution might be to enlarge margins for all snap regions by default, or make this a configurable value.

How would this sound to you as a PR topic?

**Comment by rxhanson** [comment]
Is this what you're looking for?

https://github.com/rxhanson/Rectangle#changing-the-margin-for-the-snap-areas

**Comment by Simon-Tang** [comment]
Yes... I skimmed through and misinterpreted that section! Thanks for the pointer.
