### ISSUE TITLE
Improve README readability for muggles

### ISSUE THREAD

**Issue by Crocmagnon** [rxhanson/Rectangle#3]
The readme mentions `NSUserDefaults` and `MASShortcut` which I - as a muggle in macOS development - don't understand.

Would it be possible to clarify these terms or rephrase ? 🙂

**Comment by rxhanson** [comment]
README is now updated. The blurb about the Magnet defaults might go away if it makes more sense to provide that setting in the UI at some point, but for now I prefer to keep it out of the UI for simplicity of people coming to Rectangle directly from Spectacle. NSUserDefaults and the defaults terminal command are pretty widely used, so I didn't dig into the details on it. Let me know if you still don't think it's good to go and I'll add more to it. Thanks for giving Rectangle a go!

**Comment by Crocmagnon** [comment]
Much better, thanks for the clarifications! 😃
