### ISSUE TITLE
Custom ratio for Almost Maximise

### ISSUE THREAD

**Issue by e-magon** [rxhanson/Rectangle#30]
Hello!
I've been using Rectangle for a bit and I'm finding this app useful.

I have a question though. Is it possible to have the ratio used in the [AlmostMaximizeCalculation.swift](https://github.com/rxhanson/Rectangle/blob/cd0ca9d2d72525d079ccc2eecb5bf394720d6e62/Rectangle/WindowCalculation/AlmostMaximizeCalculation.swift#L17L19) file editable through a setting?
I'm referring to this part of the code:
```
// Resize
calculatedWindowRect.size.width = visibleFrameOfScreen.width * 0.9
calculatedWindowRect.size.height = visibleFrameOfScreen.height * 0.9
```
Instead of using the hardcoded value 0.9 it would be cool to have a variable user-defined in the settings.

Thank you!

**Comment by rxhanson** [comment]
https://github.com/rxhanson/Rectangle/releases/tag/v0.10

`defaults write com.knollsoft.Rectangle almostMaximizeRatio -float <VALUE_BETWEEN_0_&_1>`

Then restart the app

**Comment by e-magon** [comment]
Thank you for the fast response!
I know I'm nitpicking, but would be possible to have two different value for the width and height?

If it's not possible it doesn't matter, it's not that important.

Thank you again

**Comment by rxhanson** [comment]
I'm ok with that, but there is potential it could take some time before I push another release out.

**Comment by e-magon** [comment]
Ok that's fine
Thank you again!

**Comment by rxhanson** [comment]
Alright, finally got around to it. 

https://github.com/rxhanson/Rectangle/releases/tag/v0.14

`defaults write com.knollsoft.Rectangle almostMaximizeHeight -float <VALUE_BETWEEN_0_&_1>`
`defaults write com.knollsoft.Rectangle almostMaximizeWidth -float <VALUE_BETWEEN_0_&_1>`

(`almostMaximizeRatio` no longer works)

**Comment by e-magon** [comment]
Great, thank you!

**Comment by erusev** [comment]
Thanks for adding these options! 

The options work great for me, but the ideal option would let me set a margin in `px`:

```
defaults write com.knollsoft.Rectangle almostMaximizeMargin -float <NUM_PIXELS>
```

I use `almostMaximize` for screenshots, and for this use case, I find that the same margin on each side works best.

I thought I should share this in case it's useful at some point.

**Comment by rxhanson** [comment]
@erusev I don't think I'll add that one in myself unless there's more demand, but I would consider a pull request for it.

**Comment by btxtiger** [comment]
Can we possibly add a config input in the settings for this?
Its very inconvenient to set it via command line each time

**Comment by martin-braun** [comment]
> Can we possibly add a config input in the settings for this? Its very inconvenient to set it via command line each time

@rxhanson I second this. Thanks for the options, so this issue isn't an issue for me anymore, but I still believe it would be more useful to have this configurable within the GUI, so people don't have to research here to figure out if it is possible or not.

**Comment by Arszilla** [comment]
I'd appreciate this as well - as I have to first maximize, then downsize to my desired dimensions (Smaller x2) to get my desired size.
