### ISSUE TITLE
The application “Rectangle.app” can’t be opened.

### ISSUE THREAD

**Issue by phillyc** [rxhanson/Rectangle#301]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 10.15.7 (19H15)
Rectangle version: 0.40
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

I've tried uninstalling and reinstalling both from the .dmg download on the website and with brew install --cask rectangle. No dice either way.

Love this tool, so it would be great for it to be working again!

**Comment by rxhanson** [comment]
Catalina appears to have intermittent issues with the universal binary built for both intel & m1. 

https://github.com/rxhanson/Rectangle/issues/282

I don't have a Catalina build that's bootable at the moment. I searched a little bit for "The application can't be opened Catalina" and it brought back this: 
https://superuser.com/questions/898124/the-application-someapp-app-can-t-be-opened

Maybe that path might lead somewhere?

As a workaround, you can go back to v0.37 for the time being, which is not a universal binary.

**Comment by stevenocchipinti** [comment]
Another big fan of Rectangle, thank you!

I'm also having the same issue on Catalina.
I tried running it from the command line to see if I could get more info and got this, not sure if that's useful for you:

```
$> ./Rectangle 
Failed to execute process './Rectangle'. Reason:
exec: Input/output error
```

I went back to `0.37` as suggested and it working fine.

**Comment by mlturner88** [comment]
Yeah, I could not get `0.40` to work and went back to `0.39` and everything is good.

**Comment by phillyc** [comment]
I walked back from 0.40 through to 0.37, which worked. No luck with 0.38 or 0.39.

https://github.com/rxhanson/Rectangle/releases/tag/v0.37

I did try the chmod suggestion in the StackOverflow answer, but that didn't do anything (as the file permissions were already set to execute).

I'll be on the look out for future updates and will try each and update here if they resolve this issue.

**Comment by rxhanson** [comment]
Just doing some housekeeping and I think this is no longer an issue. I'm pretty sure that it was a macOS bug that was fixed a while back. Feel free to comment or reopen if it's still an issue.
