### ISSUE TITLE
Thanks for this project

### ISSUE THREAD

**Issue by Kiran-Rao** [rxhanson/Rectangle#302]
This isn't an issue/bug. 

I want to say thank you for this project. As someone who regularly works with 2-3 monitors, I'm able to effortlessly control where windows are place. 

It's a great productivity tool that I use every day

**Comment by rxhanson** [comment]
Thanks for the kind words! I'm glad to hear it :)

**Comment by JaiRelan** [comment]
I second that! Thanks a lot for making this free and open source! 

My Mac wouldn't be the same without
