### ISSUE TITLE
Rectangle Does Not Auto Update

### ISSUE THREAD

**Issue by CaptainCustard** [rxhanson/Rectangle#310]
macOS version: macOS Big Sur 11.1
Rectangle version: v0.40 (45)
Logs are not available. 
**Problem:**
Every few weeks/months I run the update manually and find out an update that should have been automatically downloaded and installed. The settings for checking automatically is checked. I am not sure if that is a problem because I downloaded it using Homebrew Cask.

Thank you.

**Comment by rxhanson** [comment]
Thanks for reporting. I think I've fixed this in v0.41. Of course, no way to know for sure until the next release, but make sure you're at 0.41 for now.

https://github.com/rxhanson/Rectangle/releases/tag/v0.41

**Comment by andre-lx** [comment]
You can close this. 

Update to v0.42 (47) was automatically.

Thanks :)
