### ISSUE TITLE
Rectangle appears to cause Notification Center to freeze

### ISSUE THREAD

**Issue by rxhanson** [rxhanson/Rectangle#317]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.1
Rectangle version: 0.40
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

From an email:

Having Rectangle running causes the Notification Center to freeze when I click on notifications to ungroup some of them and sometimes when I click to read notifications from Apple News. Quitting Rectangle and force quitting Notification Center resolves this issue every time.

**Comment by rxhanson** [comment]
I can't reproduce this, but if anyone else can reproduce it let me know.

**Comment by jrochell** [comment]
I can reproduce this consistently. Just started happening today. If I have Rectangle running and try to select an item in notification center, it will stop responding. 

I hit this on version .38 and also on .40. MacBook Pro using an external display. Big Sur 11.1. Nothing shows in the "View Logging" screen. 

Happy to provide any additional info.

**Comment by rxhanson** [comment]
@jrochell, thanks for letting me know. If you uncheck the box for "Snap windows by dragging", do you still see the issue?

**Comment by jrochell** [comment]
Yeah, that seems to have fixed it! 🙌

**Comment by rxhanson** [comment]
This might be fixed with "Snap windows by dragging" enabled in v0.42.

Closing this one out since I can't reproduce it, it seems to affect a small amount of users, and disabling Snap windows by dragging is an existing workaround.

**Comment by nytr0gen** [comment]
Hi @rxhanson! Thanks for your work on this application. It's amazing! I wanted to mention that this isn't fixed in v0.44. 

Disabling "Snap windows by dragging" seems to work consistently (at least since I found this post). 

My suggestion would be to mention this workaround in the `README.md`. Might help some users struggling with this 😄

**Comment by rxhanson** [comment]
Sure, thanks for the feedback @nytr0gen. https://github.com/rxhanson/Rectangle/blob/master/README.md#rectangle-appears-to-cause-notification-center-to-freeze

**Comment by kekkokk** [comment]
Actually I had a similar problem before with Magnet and then with Rectangle that resolved by unchecking "snap windows...".
This is described in my bug report on Chrome: [MonoRail Bug Report](https://bugs.chromium.org/p/webrtc/issues/detail?id=13943#c1)

The biggest issue is that other than that specific debug page, all the video meeting I do o Chrome tends to stutter the video a lot if Rectangle or Magnet are opened BEFORE opening a new Chrome window.
