### ISSUE TITLE
Breaks System Preferences > Security & Privacy (hang, freeze)

### ISSUE THREAD

**Issue by andreialecu** [rxhanson/Rectangle#332]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.1
Rectangle version: N/A
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): N/A

I used Migration Assistant to migrate from an 8GB Mac Mini M1 to a 16GB Mac Mini M1. 

All apps were fine after the migration except Rectangle:

- After loading it on the new mac, it opened its prompt to enable it in `System Preferences/Security & Privacy`, except that it freezes with a spinning pinwheel.
- Tried restarting a bunch of times and this always happens. I'm no longer able to go into `Security & Privacy`.
- I then tried removing Rectangle so that I could reinstall it, but I was not able to even delete it from Applications. Finder would hang moving it to the bin. Had to force quit Finder.
- Only thing that worked was to `rm -rf Rectangle.app` from `/Applications`, but the `Security & Privacy` pane still hangs now and is inaccessible.

I was wondering how to undo whatever it did to `Security & Privacy`, I assume some configuration files are left behind. Any ideas would be appreciated.

**Comment by andreialecu** [comment]
Relevant:

```
Command:          System Preferences
Path:             /System/Applications/System Preferences.app/Contents/MacOS/System Preferences
Identifier:       com.apple.systempreferences
Version:          14.0 (14.0)
Build Version:    81
Project Name:     SystemPrefsApp
Source Version:   486000000000000
Parent:           launchd [1]
PID:              611
Time Since Fork:  101s

Event:            hang
Duration:         102.00s
Duration Sampled: 1.00s (process was unresponsive for 101 seconds before sampling)
Steps:            10 (100ms sampling interval)

Hardware model:   Macmini9,1
Active cpus:      8

Time Awake Since Boot: 146s
Time Since Wake:  n/a (machine hasn't slept)

Fan speed:        1687 rpm

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------


Heaviest stack for the main thread of the target process:
  10  start + 4 (libdyld.dylib + 94004) [0x180894f34]
  10  ??? (System Preferences + 9012) [0x104eee334]
  10  NSApplicationMain + 1064 (AppKit + 15792) [0x18310bdb0]
  10  -[NSApplication run] + 600 (AppKit + 206348) [0x18313a60c]
  10  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1312 (AppKit + 263972) [0x183148724]
  10  _DPSNextEvent + 2036 (AppKit + 270900) [0x18314a234]
  10  -[NSApplication _sendFinishLaunchingNotification] + 236 (AppKit + 307544) [0x183153158]
  10  -[NSApplication _postDidFinishNotification] + 340 (AppKit + 308288) [0x183153440]
  10  -[NSNotificationCenter postNotificationName:object:userInfo:] + 64 (Foundation + 42576) [0x1816a0650]
  10  _CFXNotificationPost + 720 (CoreFoundation + 290960) [0x180937090]
  10  _CFXRegistrationPost + 440 (CoreFoundation + 1152832) [0x180a09740]
  10  ___CFXRegistrationPost_block_invoke + 52 (CoreFoundation + 1152980) [0x180a097d4]
  10  __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28 (CoreFoundation + 492968) [0x1809685a8]
  10  ??? (System Preferences + 22896) [0x104ef1970]
  10  ??? (System Preferences + 130792) [0x104f0bee8]
  10  ??? (System Preferences + 99468) [0x104f0448c]
  10  ??? (System Preferences + 31852) [0x104ef3c6c]
  10  ??? (System Preferences + 34136) [0x104ef4558]
  10  -[NSCFRunLoopSemaphore wait] + 44 (ViewBridge + 18736) [0x187005930]
  10  -[NSCFRunLoopSemaphore wait:] + 368 (ViewBridge + 19312) [0x187005b70]
  10  +[NSCFRunLoopSemaphore _observe:whilePerforming:] + 364 (ViewBridge + 22032) [0x187006610]
  10  __29-[NSCFRunLoopSemaphore wait:]_block_invoke + 252 (ViewBridge + 23076) [0x187006a24]
  10  __29-[NSCFRunLoopSemaphore wait:]_block_invoke_2 + 144 (ViewBridge + 23320) [0x187006b18]
  10  __CONSIDER_WHO_REQUESTED_THIS_WAIT_BEFORE_SENDING_BUG_TO_VIEWBRIDGE__ + 24 (ViewBridge + 23400) [0x187006b68]
  10  __29-[NSCFRunLoopSemaphore wait:]_block_invoke_3 + 116 (ViewBridge + 23524) [0x187006be4]
  10  invokeRunLoopInModeForDuration + 332 (ViewBridge + 23868) [0x187006d3c]
  10  __invokeRunLoopInModeForDuration_block_invoke_2 + 36 (ViewBridge + 24048) [0x187006df0]
  10  CFRunLoopRunSpecific + 600 (CoreFoundation + 530240) [0x180971740]
  10  __CFRunLoopRun + 1216 (CoreFoundation + 533356) [0x18097236c]
  10  __CFRunLoopServiceMachPort + 380 (CoreFoundation + 540312) [0x180973e98]
  10  mach_msg + 76 (libsystem_kernel.dylib + 4248) [0x180840098]
  10  mach_msg_trap + 8 (libsystem_kernel.dylib + 3304) [0x18083fce8]
 *10  ??? (kernel.release.t8101 + 202224) [0xfffffe0007c3d5f0]
```

Note that the pane was working fine prior to attempting to open it via Rectangle. Doubt it could be a coincidende. Especially since dragging it to the big was also impossible and only `rm -rf` worked.

**Comment by rxhanson** [comment]
That sounds like a horrible experience, sorry that this happened. 

In terms of restoring system prefs, the only thing I can think is to reboot your mac (or do a complete power down then power back on if things are still weird). 

Apple has changed some of the underlying mechanisms behind accessibility enabled apps in Big Sur, so my suspicion is that this is a path that Apple testers have not gone down. What may be happening with the migration is that Rectangle is already recognized as an app that requires accessibility **_before_** it prompts you to open System Prefs. These types of scenarios have led to hanging in System Prefs in the past. In a normal install, macOS is unaware that Rectangle needs accessibility privileges until the app checks to see if accessibility is enabled for the app.

Unfortunately, what you've experienced is a macOS side bug that Rectangle triggered.

A possible fix that I'll think about is just getting rid of the Accessibility prompt window in Rectangle altogether. This would lead to a worse user experience because the built-in macOS prompts are not preemptive (and not as informative) and would force the user to restart the app after that first run, but it would likely prevent this scenario from happening.

**Comment by andreialecu** [comment]
So I tried to reinstall Big Sur, on top of my existing installation: This did not help, problem returned. Seems to be tied to the user account I guess.

Also I now I booted in Safe Mode and it also did not help. 

Additionally, I tried reinstalling Rectangle to see if it would help in any way. It did not, and now when trying to remove it Finder is stuck while removing it (just like my initial experience):

<img width="516" alt="Screenshot 2021-01-17 at 14 39 57" src="https://user-images.githubusercontent.com/697707/104843215-14300580-58d2-11eb-8d69-f42f02a0befd.png">

My main problem right now is that I cannot access the pane in System Preferences and I need to enable a bunch of other apps there (Logitech mouse app, and some others).

Googling this issue has turned out no answers, it's been reported a lot in previous macOS versions but there is no good solution. (tried `tccutil reset`, etc)

**Comment by andreialecu** [comment]
FWIW can't even stop the move to bin without force quitting Finder:

<img width="516" alt="Screenshot 2021-01-17 at 14 44 18" src="https://user-images.githubusercontent.com/697707/104843297-87397c00-58d2-11eb-9606-9d3d5eac3609.png">

**Comment by andreialecu** [comment]
I just created a new account and it seems that even on this fresh account I cannot access `Security & Privacy`, still freezes. So the issue isn't tied to my main user account.

I can also see `Rectangle` in Applications in the new account, and cannot delete it from there either (except with `rm -rf`).

Agreed that this seems to be a (bad) macOS bug. Any pointers on how to work around or what to try would be appreciated.

**Comment by andreialecu** [comment]
Found some information about the accessibility settings for apps being stored in `TCC.db`. Rebooted to recovery mode to run `csrutil disable` then deleted the file. No success.

I just realised now that trying to delete *any* app results in Finder spinning forever. System seems bricked.

The system logs mention this service crashing repeatedly:
```
Jan 17 15:42:55 Mac-mini com.apple.xpc.launchd[1] (com.apple.sysextd[1517]): Service exited due to SIGTRAP | sent by exc handler[1517]
Jan 17 15:42:55 Mac-mini com.apple.xpc.launchd[1] (com.apple.sysextd): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

This also seems relevant: `ExtensionFinishUninstallingAction`

```

Crashed Thread:        1  Dispatch queue: sysextd.extension_manager

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       EXC_ARM_BREAKPOINT at 0x00000001a2d3e338 (brk 1)
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Trace/BPT trap: 5
Termination Reason:    Namespace SIGNAL, Code 0x5
Terminating Process:   exc handler [1513]

Application Specific Information:
dyld3 mode
Fatal error: 'try!' expression unexpectedly raised an error: sysextd.ExtensionFinishUninstallingAction.actionErrors.outstanding_references: file sysextd/extension_manager.swift, line 422
 

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x0000000197481acc __ulock_wait + 8
1   libdispatch.dylib             	0x000000019730ce04 _dlock_wait + 56
2   libdispatch.dylib             	0x000000019730d1ac _dispatch_group_wait_slow + 60
3   libdispatch.dylib             	0x0000000197310308 dispatch_block_wait + 284
4   sysextd                       	0x00000001028eeb38 0x1028e8000 + 27448
5   sysextd                       	0x00000001028f1a34 0x1028e8000 + 39476
6   sysextd                       	0x00000001028f1264 0x1028e8000 + 37476
7   libdyld.dylib                 	0x00000001974d4f34 start + 4

Thread 1 Crashed:: Dispatch queue: sysextd.extension_manager
0   libswiftCore.dylib            	0x00000001a2d3e338 _assertionFailure(_:_:file:line:flags:) + 508
1   libswiftCore.dylib            	0x00000001a2d3e338 _assertionFailure(_:_:file:line:flags:) + 508
```

Not sure what to do besides trying to use Time Machine to back up my user data then reinstall macOS from scratch.

**Comment by andreialecu** [comment]
I ended up reinstalling macOS Big Sur from scratch (nuking all partitions, leaving *anything* behind being completely unsuccessful).

I installed Rectangle again on the fresh install and everything is good now. Hopefully a macOS update will resolve this.

**Comment by rxhanson** [comment]
Thank you for documenting what happened and what you found.

If anyone else has this issue or something similar, please let me know so I can prioritize building a workaround into Rectangle over waiting for a macOS update.

**Comment by cgruber** [comment]
Related, I'm having the same sort of issue with several apps, including Drovio, on Big Sur, so this seems like it is not an isue with Rectangle.

**Comment by gifnub** [comment]
Hi everyone! Just got the same problem with disk drill utility. Security & Privacy hang. Stuck during  moving to bin. Have to  force quit Finder. Any files linked wirh app can`t be deleted (for example- aliases). I unistalled it successfully. Other files (not linked with app)  can be deleted with no probs. No progress with safe mode and System Integrity Protection (csrutil disable). Guys, does anyone have any ideas?

**Comment by triste24** [comment]
got the same problem without Rectangle
