### ISSUE TITLE
It's 2021...

### ISSUE THREAD

**Issue by erikhuizinga** [rxhanson/Rectangle#334]
...but the latest release still thinks it's 2021. 😉

---

- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

Rectangle version: https://github.com/rxhanson/Rectangle/releases/tag/v0.42

**Comment by rxhanson** [comment]
Haha thanks! I forgot to update the copyright year in the about window, too. It's updated, for next release :)
