### ISSUE TITLE
Delay between mouse cursor reaching edge and UI element showing resize area is too long

### ISSUE THREAD

**Issue by yunuserkaya** [rxhanson/Rectangle#352]
It is too long and needs to be adjustable. Feels like forever even though it probably is around 100ms.

**Comment by rxhanson** [comment]
You can disable the "fade" with this command:

`defaults write com.knollsoft.Rectangle footprintFade -int 2`

https://github.com/rxhanson/Rectangle#modify-the-footprint-displayed-for-drag-to-snap-area

Is that what you are looking for here?

**Comment by yunuserkaya** [comment]
You’re right my apologies. I did a defaults read and somehow macOS won’t list all available keys until you add those in

**Comment by yunuserkaya** [comment]
A UI option would be sweet but it may be a power use feature

**Comment by rxhanson** [comment]
Closing this one out since the terminal command is present. I have thought about a "power user settings tab" that basically contains all of the things that are not in the UI but can be set via terminal command.

**Comment by yunuserkaya** [comment]
This is because the accessibility API ends up asking the NSWindow in the app for its origin, and window drags are done server-side and the app only updates its position every 100ms.
