### ISSUE TITLE
When border edge is increased, inside edge is not rounded

### ISSUE THREAD

**Issue by yunuserkaya** [rxhanson/Rectangle#354]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Big Sur
Rectangle version: 0.42
<img width="56" alt="image" src="https://user-images.githubusercontent.com/22533048/105569653-3f628c80-5cf8-11eb-808c-24f8d8aab180.png">

**Comment by rxhanson** [comment]
This should be fixed in v0.43

**Comment by yunuserkaya** [comment]
This fix didn't carry over when updated. Does it require the repeat the setting
<img width="69" alt="image" src="https://user-images.githubusercontent.com/22533048/107817521-1fd4e780-6d2b-11eb-97a4-e9593c8c5e15.png">

**Comment by rxhanson** [comment]
I will update this again - I think my corner radius for the border might be 1 or 2 degrees too small still (I tried out a lot of different values and might have mistakenly landed on one that didn't actually fix it).

**Comment by rxhanson** [comment]
I took another look at this, and this is actually how macOS draws a border for the box view window. While it would be possible to draw this border using custom frames, it's not something I plan on implementing. I have no reason to reject a PR with this change, though.
