### ISSUE TITLE
Install via home-brew doesn't work

### ISSUE THREAD

**Issue by codingbutstillalive** [rxhanson/Rectangle#361]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.1
Rectangle version: does not apply
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): see error message below

I just had a fresh install of homebrew. When I run 

`brew install --cask rectangle`

it gives me the following output:

**_Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-cask /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask` exited with 128._**

Maybe this is not a problem of rectangle. But even then the install instructions on the rectangle website should be adapted.

**Comment by rxhanson** [comment]
Works for me. ¯\_(ツ)_/¯

Here's an issue in homebrew cask that matches what you've experienced: https://github.com/Homebrew/homebrew-cask/issues/82273

If you find out what's wrong and you believe there is something beneficial to be added to the Readme, please create a pull request.

**Comment by rxhanson** [comment]
Or if you do figure it out and it doesn't make sense to put it in the readme, then feel free to put another comment here so it might help others that come across this.

Thanks!
