### ISSUE TITLE
Change priority of overlapping commands

### ISSUE THREAD

**Issue by matthewdippel** [rxhanson/Rectangle#37]
OS: Mojave 10.14.6
Rectangle: Version 0.10 (14)

Many of the commands have overlapping default shortcuts:
Next Display: Control + Option + Command + Right Arrow, 
Next Third: Control + Alt + Right Arrow, 
Make Larger: Control + Option + Shift + Right Arrow, 
Upper Right: Control + Option + Right Arrow
Right Half: Option + Command + Right Arrow

This can cause some strange behavior on multi monitor setups when you try to move a window between displays. When you enter the key combination for Next Display, the window can move to the next display, but then move back to the right half of the previous display right after. 

It would be better if when the key combination for Next Display was input, Rectangle did not also execute the commands that share a subset of the key combination. This would make the default movement commands more consistent, as right now it feels there is some randomness involved in their actual execution order.

**Comment by rxhanson** [comment]
Are you sure that you don't have any other window managers also running?

**Comment by matthewdippel** [comment]
You are right, I had an old one running in the background that didn't show up in my taskbar. My mistake.
