### ISSUE TITLE
Add ability to disable both "Move to adjacent display on repeated left or right commands" and "repeated half actions cycle 1/2, 2/3, and 1/3" options

### ISSUE THREAD

**Issue by charleseff** [rxhanson/Rectangle#370]
It seems odd to have to choose between the two options of "Move to adjacent display on repeated left or right commands" and "repeated half actions cycle 1/2, 2/3, and 1/3" options".  I'd rather that entering a rectangle command more than once does nothing.

**Comment by rxhanson** [comment]
https://github.com/rxhanson/Rectangle#halves-to-thirds-repeated-execution-of-half-and-quarter-actions

Changing to a discussion so users can upvote if they want this in the UI
