### ISSUE TITLE
Traverse displays vertically

### ISSUE THREAD

**Issue by randomrouleur** [rxhanson/Rectangle#38]
Hi, first of all - love the app, so thank you very much!
I've enabled the 'traverse displays' option in Preferences, which is great for multiple monitors.  However, I have my MacBook screen below my external monitor, so I have to send the windows sideways to get it onto the other display.  Would it be simple enough to enable traversal of displays in a vertical orientation, in addition to the current horizontal behaviour?
Cheers, Campbell

**Comment by rxhanson** [comment]
I like this idea. I'm on board with it getting rolled into Rectangle, but I don't quite have the bandwidth to add it in myself at this time. A PR would be welcome.
There is actually a nontrivial amount of work that would have to be done here. 
Here's my initial thoughts on what would need to be done.
* Currently, screens are ordered in terms of their left/right positions, so there would have to be additional code that provides them ordered in top to bottom positions.
* The top and bottom half actions would have to be modified to behave in the same way as the right and left half actions, using the new top to bottom screen positions.
* The move up and move down actions would have to be modified to behave in the same way as the  move right and move left actions, using the new top to bottom screen positions.
* The setting for "Traverse displays..." would have to be updated, along with the translations for each language.

**Comment by randomrouleur** [comment]
Ha, I figured that it might not be entirely straightforward!  One for the future features list...
