### ISSUE TITLE
Rectangle freezes when in a MS Teams meeting

### ISSUE THREAD

**Issue by MattJStone** [rxhanson/Rectangle#386]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 10.15.7
Rectangle version: 0.38 (43)

When I join a MS Teams meeting, rectangle keyboard shortcuts stop working and the rectangle icon is unresponsive. When the meeting is over, rectangle starts working again.

If I kill the rectangle process and start a new one while in the MS Teams meeting, it works fine until a new MS Teams meeting is started

**Comment by rxhanson** [comment]
Thanks for reporting. Unfortunately, this sounds like something for which there is no fix possible from within Rectangle. MS Teams meetings might have some kind of behavior that hijacks the Accessibility API that Rectangle relies on. If you come across any other window manager apps that aren't affected by MS Teams, then perhaps there is something that can be done.

**Comment by MattJStone** [comment]
Fair enough
