### ISSUE TITLE
Sound feedback

### ISSUE THREAD

**Issue by feidens** [rxhanson/Rectangle#39]
With the newest version there is a sound feedback every time I use a shortcut.
These seems to be an issue or rather one should have the option to deactivate the sound feedback.

**Comment by rxhanson** [comment]
I can't reproduce this, and nothing has changed in the code that would prompt sound feedback to occur. Perhaps something else has changed on your system? Specifically, which version of Rectangle, and which version of macOS are you using?

**Comment by feidens** [comment]
Sorry the issue was based on the combination of an running install of spectacle and rectangle.
