### ISSUE TITLE
allow option-based shortcuts

### ISSUE THREAD

**Issue by leoduan** [rxhanson/Rectangle#40]
I suggest to allow option-based shortcuts, such as option-left, option-right. Since they are less used compared to command-based and control-based, hence less likely to have shortcut conflicts.

**Comment by rxhanson** [comment]
Check the box for "Allow any shortcut" in the settings tab. 

I'm sure there's good reason why MASShortcut prevents those by default, but I can't think of anything that uses those in macOS off the top of my head.

**Comment by fuzzy76** [comment]
They are used for moving to start and end of lines in text areas.
