### ISSUE TITLE
Window blinks on next screen when moved to edge adjacent to that screen

### ISSUE THREAD

**Issue by exadeci** [rxhanson/Rectangle#41]
macOS version: 10.15.1
Rectangle version: 0.10 (14)

Sometimes on a window on a 3 parallel displays setup, the window jumps to another screen while you are moving it (haven't tested with more or less monitors).

Pick any `window control + option + Command + <-` for example, press that combination severaly times and eventually the bugs happens.

**Comment by rxhanson** [comment]
In the next release, I'll add some updated logging and a dedicating log viewer (since viewing logs the Apple way is a total pain). This should help us figure out what's going on for you, as I don't currently have three monitors to test on.

**Comment by rxhanson** [comment]
Alright, the new release is up: https://github.com/rxhanson/Rectangle/releases/tag/v0.12

Here's the steps for viewing logs:
https://github.com/rxhanson/Rectangle#view-debug-logging

Hopefully, this will give us enough insight to figure out what's going on. If not, it may take a couple more iterations of updated logging. 

When you get a chance, paste some of your logs of erroneous behavior.

**Comment by exadeci** [comment]
The new release might have fixed the issue as I wasn't able to reproduce it.

I'll confirm on this ticket in a few days if it doesn't come back.

**Comment by exadeci** [comment]
So I've found a new/different issue, when the window is on my leftmost screen and I move it to the right half of that screen, the window blinks on the screen that is on the right then goes to the expected position.
It only happens when the window is maximized (alt+command+f)
Here's the logs:
```
2019-12-02T11:44:38+11:00: AX position proposed: (-960.0, 23.0), result: (-960.0, 23.0)
2019-12-02T11:44:38+11:00: AX sizing proposed: (960.0, 1057.0), result: (984.0, 1057.0)
2019-12-02T11:44:38+11:00: AX position proposed: (-984.0, 23.0), result: (-984.0, 23.0)
2019-12-02T11:44:38+11:00: AX sizing proposed: (984.0, 1057.0), result: (984.0, 1057.0)
2019-12-02T11:44:38+11:00: rightHalf | display: (-1920.0, 0.0, 1920.0, 1057.0), calculatedRect: (-960.0, 23.0, 960.0, 1057.0), resultRect: (-984.0, 23.0, 984.0, 1057.0), srcScreen: DELL P2719HC, destScreen: DELL P2719HC, resultScreen: DELL P2719HC
```

**Comment by rxhanson** [comment]
I'll look to add another distinguishing factor for the logging of the monitor names to make it easier in the future (I thought about that after the release, haha). The name has no bearing on the functionality of the app, though.

According to the logs, the window is unable to be resized to the intended size, and that may or may not have something to do with it. I've seen some similar behavior when I've tested out two monitors (I actually typically just use a MacBook Pro and no extra monitors for development), so I should be able to test this out a little further on my own. It might be a bug inherent to macOS, so finding a workaround might be time consuming if that's the case. 

Which application does this happen with? (I'll also add the application name to the logs in the future).

As for the initial issue here, the fact that it's not a problem anymore points to it being something with macOS accessibility, which can be pretty buggy at times. There were no code changes in this past Rectangle release that would have affected this behavior. Sometimes an app reinstall or remove/add in System Prefs - Privacy - Accessibility can fix these kinds of weird issues. It's annoying, but it seems to be more and more common now that apple is buckling down on these workflows in recent macOS releases.

**Comment by exadeci** [comment]
It was with Chrome but the bug also happens with Slack, Iterm and probably every other window.

It happens between two identical monitor the 3rd one though is my macbook's display so smaller but the new bug I have isn't happening on it.

Was Spectacle using some other way?

**Comment by rxhanson** [comment]
I got some time to test this out, and it has to do with moving the window, then resizing it, which would be more noticeable when going from a larger window to a smaller window. I'll see what I can do for the next release.

**Comment by rxhanson** [comment]
Alright, I put a change for the window blinking on the next screen in https://github.com/rxhanson/Rectangle/releases/tag/v0.13.

This is definitely a macOS bug, but hopefully the change in v0.13 fixes it. Keep me posted when you get a chance to try it out.

**Comment by exadeci** [comment]
@rxhanson Unfortunately 0.13 didn't fix the new issue (the old one didn't happen again).

One thing that could help you, is that the issue only happens from a screen of the same size and **only** towards the main display (the one with the menu bar) when it's on the center screen.

Bug happens when the window is full screen and gets resized to the right side of the left screen and the menu bar is on the center screen:
[][-][smaller]

Can't reproduce with the menubar on the left screen:
[-][][smaller]

**Comment by rxhanson** [comment]
Alright, v0.15 has another attempt at fixing it:
https://github.com/rxhanson/Rectangle/releases/tag/v0.15

Let me know if you see any difference.

**Comment by exadeci** [comment]
Looks fixed @rxhanson  thanks!
