### ISSUE TITLE
[BUG] cannot write almostMaximize property

### ISSUE THREAD

**Issue by ztlevi** [rxhanson/Rectangle#420]
Not sure if this is a bug but I am aware of a weird behavior. I cannot write almostMaximize property but maximize, rightHalf, leftHalf works.
```
  defaults write com.knollsoft.Rectangl almostMaximize '{keyCode = 45; modifierFlags = 1310720;}'
```
Using this command but the plist remains unchanaged. I tested after quit the app.

macOS version: 11.2.3
Rectangle version: v0.42
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):

**Comment by rxhanson** [comment]
Your command is missing an e on Rectangle, but if you have it spelled correctly when you execute it and it's still not working then try adding .plist to the end of com.knollsoft.Rectangle.

Alternatively, just use prefs editor: https://apps.tempel.org/PrefsEditor/

**Comment by ztlevi** [comment]
oh well. my bad. it works 🤦
