### ISSUE TITLE
Rectangle works under Rosetta for Apple Silicon

### ISSUE THREAD

**Issue by DStoyanoff** [rxhanson/Rectangle#426]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.2.3
Rectangle version: 0.44

Hello and thanks for the amazing app. It works very nice and it saves my day with a multi-monitor setup.

I've noticed however that in the website it's mentioned that it works with Apple Silicon and it indeed does work. I've noticed however in Activity Monitor that it's said to be running under Intel arch (Rosetta). Is this intended and if so, is there a plan to release a native version for Apple Silicon?

Thanks

**Comment by rxhanson** [comment]
The last several versions of Rectangle have been the universal binary (v0.44 included), compiled for both Intel & Apple silicon. The only way I can guess that it would be running with Rosetta is if you checked the box for _Open using Rosetta_ in the _Get Info_ window in Finder. Here's an article that talks about how to do that: 
https://www.macworld.com/article/338843/how-to-force-a-native-m1-mac-app-to-run-as-an-intel-app-instead.html

**Comment by DStoyanoff** [comment]
Hey, thanks for your reply.

I definitely didn't do that, but perhaps it automatically decided to run it under emulation. I've unchecked it and it seems good now, thanks
