### ISSUE TITLE
Move Safari Between Displays Maximizes Window

### ISSUE THREAD

**Issue by michaelmcdonald** [rxhanson/Rectangle#437]
- [X] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 10.15.7 (19H2
Rectangle version: 0.45 (50)

As the title says: any time I move a Safari window between displays it automatically executes a maximize, even if the window was not previously maximized. I have multiple Safari windows open; however none of them are in a maximized state. If you need me to provide a log or perform additional testing I'll gladly do so!

**Comment by michaelmcdonald** [comment]
New discovery: this only happens when I'm moving the Safari window between a horizontally oriented display to a vertical display (and vice versa).

**Comment by rxhanson** [comment]
This is a remnant of Spectacle behavior. I've never liked it, so I'll probably change it in the next release.

**Comment by rxhanson** [comment]
I think this should be fixed in 0.48. Let me know if you get a chance to test it out.

**Comment by michaelmcdonald** [comment]
All fixed! Thanks a ton!
