### ISSUE TITLE
Matlab crash with Rectangle

### ISSUE THREAD

**Issue by walterrrossi** [rxhanson/Rectangle#444]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.2.3
Rectangle version: 0.45
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

I have found a bug with Matlab using your app. 
If the app is running and you decide to use a feature of Matlab, this will make crash the application. I know that is a Matlab problem, because also with other snapping app it occurs. By the way I am facing another problem, if I turn on "ignore Matlab" in Rectangle settings, I have seen that if Matlab opens another window, Rectangle doesn't ignore more snapping for Matlab and this brings to other crashes.
I hope that there's a fix to it, because to have Matlab working well I have to quit Rectangle.
Thank you for your work!

Edit: I've seen that other times this issue is already opened, but my issue is a bit different, in fact I am noticing that Ignore this app doesn't work properly

**Comment by rxhanson** [comment]
If you ignore Matlab in the most recent Rectangle release, Rectangle will no longer interfere with Matlab.

Closing this one out, but feel free to comment or reopen if you still have issues.
