### ISSUE TITLE
Big Sur + Rectangle = NotificationCenter freeze with 100% CPU usage

### ISSUE THREAD

**Issue by chriswessels** [rxhanson/Rectangle#448]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Big Sur 11.2.3 (20D91)
Rectangle version: 0.45

While Rectangle is running, NotificationCenter becomes unresponsive and uses 100% of one CPU core. Closing Rectangle and restarting notification center (`sudo killall -9 NotificationCenter`) fixes it

**Comment by rxhanson** [comment]
Thanks for reporting. Unfortunately, I cannot reproduce this. 

Try disabling "Snap windows by dragging". It is likely something that is unavoidable while Rectangle has this feature enabled, based on an issue reported by a couple other users.

**Comment by chriswessels** [comment]
Thank you @rxhanson, that fixed it
