### ISSUE TITLE
Vertical 1/3 postions

### ISSUE THREAD

**Issue by sinedied** [rxhanson/Rectangle#45]
Love the tool, was a heavy Spectacle user and you pushed it a bit further and ironed out few issues, well done 👍 

Though there's one small thing that was in spectacle but I'm missing in rectangle is the vertical 1/3 positions: I use one of my 2 screens vertically (and I know a lot of devs do that!) and it would be very useful to have it back! And to not clutter more the shortcuts/options, it could be done using the existing 1/3 positions shortcuts, just detecting if screen height > screen width to apply vertical thirds instead of horizontal one, what do you think?

I can take a look a it to propose a PR if you're ok with that?

**Comment by sinedied** [comment]
Wow, I just looked at the code and saw that it was already implemented, sorry for the noise 👍

**Comment by leocaseiro** [comment]
I was going to request that, how to use the shortcuts/commands for 1/3 vertical? Thanks

**Comment by rxhanson** [comment]
@leocaseiro when you execute a thirds command, Rectangle checks the dimensions of the screen that the frontmost window is on and will automatically set the 1/3 window size/position for landscape or portrait accordingly. Although this works properly for me when I've tested it out, perhaps there is a bug since https://github.com/rxhanson/Rectangle/issues/112 was filed.

**Comment by kissge** [comment]
I also came here to request this similar feature to find it's implemented!
I guess showing some tips on keyboard shortcut setting pane would be helpful because current ".* Third" icons imply that it always work horizontally?

**Comment by gvivster** [comment]
Here to say I too use a vertical monitor, and for several months I've had no idea it COULD do vertical thirds until I came here and looked at this thread. A tip somewhere in the UI would be lovely!

(And honestly, in case you've been considering it - the ability to do vertical thirds on my horizontal monitor would be pretty awesome or a few niche uses, too.)

(PS: Thanks for this badass app I use every day.)
