### ISSUE TITLE
Resizing a window doesn't restart the 1/2 - 2/3 - 1/3 cycle

### ISSUE THREAD

**Issue by rxhanson** [rxhanson/Rectangle#46]
macOS version: 10.15.1
Rectangle version: 0.12

If I resize the width of a window, then perform a left or right half action, I would expect the window to snap to 1/2 instead of the next value in that cycle.

**Comment by rxhanson** [comment]
I put a fix in v0.13 for this, but it requires that drag window snap is enabled. If someone needs this to work this way without drag window snap enabled, it can be reopened.

**Comment by yalmasri** [comment]
I need this one as I don't use the drag window snap.
thanks a lot

**Comment by rxhanson** [comment]
@yalmasri just a heads up that it's a fairly involved change to fix this without drag window snap enabled, so it may take a while before I get the time to put it in. I'll keep it on my list though.

**Comment by yalmasri** [comment]
Thanks for the answer, I’m just voting for this feature so you can consider it.
🙏👍🏻✌🏻
