### ISSUE TITLE
Snapping to "Center Half" doesn't continue to "Center Third" with subsequent presses

### ISSUE THREAD

**Issue by ZeeEssDoubleU** [rxhanson/Rectangle#465]
App does not snap to "Center Third" after snapping to "Center Half" on subsequent key presses.  I would think this should behave like the other "Half" options (ie "Left Half"), where the option will snap to its "Thirds" and "Two Thirds" variants if there is not another hotkey set for those respective options.

macOS version: 11.3 (20E232)
Rectangle version: 0.45 (50)

**Comment by rxhanson** [comment]
Currently this is enabled via a hidden config:

defaults write com.knollsoft.Rectangle centerHalfCycles -int 1

Followed by an app restart.

I'll probably enable it by default in a future release - it's just that it got added in much later and I wasn't sure if I wanted it to be the default behavior initially.
