### ISSUE TITLE
Weird key combination in Keyboard preferences in Sierra

### ISSUE THREAD

**Issue by 1alessandro1** [rxhanson/Rectangle#468]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 10.12.6 16G2136
Rectangle version: 0.46
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): [logs.txt](https://github.com/rxhanson/Rectangle/files/6489687/logs.txt)

Hi, today when using Rectangle on macOS Sierra, while creating a new shortcut, the keyboard interceptor detects the key `^A` even if I'm only pressing `CRTL`, therefore any `CTRL+OPT+Left/Right` do not work because of this.

I don't think the log is going to be useful, since when pressing the CTRL+OPT+Right combination nothing happens since I  guess the `A` key is being detected too for no apparent reason

I've tested if `CRTL` button works as expected outside of Rectangle *Keyboard Shortcuts*, e.g. in macOS `Terminal` if CRTL+A is pressed the cursor goes back at the beginning of the line, and when I press `CTRL` nothing happens, only if I press `A` key too it works as expected.

**Comment by rxhanson** [comment]
This sounds like something that is specific to your setup/keyboard (even though you said that you have proper behavior in Terminal). I recommend setting a keyboard shortcut in another application altogether, or in macOS System Prefs -> Keyboard -> Shortcuts, and if you have expected behavior there then we can narrow the scope further.

**Comment by 1alessandro1** [comment]
The problem is that I've installed every OS from when Rectangle is compatible (from El Capitan to Big Sur) and Sierra is the only one affected.

Also, I'm connecting to the PC with VNC viewer, which allows full shourtcuts sharing when using rectangle

**Comment by rxhanson** [comment]
Thanks for the additional details. 

Unfortunately, there's nothing in Rectangle that would cause different behavior, nor is there any change that I would be willing to pursue to accommodate a rather unique fix for Sierra accessed via VNC viewer. I'm pretty confident that there is something particular about your setup that is causing the issue, and that it is likely outside the scope of what a fix in Rectangle could even correct.

**Comment by 1alessandro1** [comment]
Understood, is there anybody with Sierra willing to test Rectangle with build version 16G2136?

**Comment by rxhanson** [comment]
Doing some housekeeping and closing this one out. Feel free to comment if anything else comes up on it.
