### ISSUE TITLE
Rectangle app is disabled on Notion app.

### ISSUE THREAD

**Issue by lim0606** [rxhanson/Rectangle#470]
- [v] This is a new bug that hasn't been documented in a closed issue or in the Readme.
macOS version: macOS Catalina 10.15.6
Rectangle version: Version 0.46 (51)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

It seems like the Rectangle app is disabled on the Notion app. I couldn't find a thread regarding this. Is there anyone who can give me some pointers to use Rectangle app on the Notion app?

<img width="1680" alt="Screen Shot 2021-05-17 at 10 22 10 AM" src="https://user-images.githubusercontent.com/4983224/118504776-c84d7a00-b766-11eb-9e14-54b722b268a6.png">

**Comment by rxhanson** [comment]
Try restarting Notion. 

There are a handful of apps that sometimes do not properly interface with the accessibility API in macOS, which is used to manage windows.

Unfortunately nothing from Rectangle's perspective that can be done about this - you'll want to file a bug with Notion.

**Comment by lim0606** [comment]
Thanks for the response.

Restarting the Notion app works!
