### ISSUE TITLE
Rectangle do not notify about available updates

### ISSUE THREAD

**Issue by sigo** [rxhanson/Rectangle#493]
I have enabled this option (_Check for updates automatically_) but never get any notification/alert about new versions or auto-update. Tested probably since 2 years at two different macbooks.

<img width="602" alt="Screen Shot 2021-06-17 at 11 43 44" src="https://user-images.githubusercontent.com/321881/122372847-4c12a600-cf61-11eb-9325-bc4c4520b777.png">

- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.4
Rectangle version: Version 0.43 (48)
~~Logs if applicable (In Rectangle menu, hold option, "View Logging..."):~~

**Comment by sigo** [comment]
I've seen https://github.com/rxhanson/Rectangle/issues/194, and at the beginning I show my plist settings:

```
> defaults read com.knollsoft.Rectangle.plist

{
    "NSStatusItem Preferred Position Item-0" = 421;
    "NSWindow Frame SUUpdateAlert" = "530 489 620 392 0 0 1680 1025 ";
    SUAutomaticallyUpdate = 1;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2021-06-17 09:38:56 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 766570249;
    SUUpdateRelaunchingMarker = 0;
    alternateDefaultShortcuts = 1;
    lastVersion = 48;
    launchOnLogin = 1;
}
```

**Comment by rxhanson** [comment]
Years later (sorry!), I never was able to reproduce this. If this comes up again, it's likely due to something preventing Sparkle from requesting or responding to an update. Meaning it would be something like a corporate VPN/firewall restriction.
