### ISSUE TITLE
After uninstalling with AppCleaner, I can still use it

### ISSUE THREAD

**Issue by lucky13820** [rxhanson/Rectangle#494]
I uninstalled Rectangle with AppCleaner, I don't have it running anymore. But when I drag a window to the edge, it still shows the Rectangle overlay, and the snapping works too. I don't know how should I completely uninstall it. 

![CleanShot 2021-06-22 at 16 04 55](https://user-images.githubusercontent.com/7293811/123010505-98038780-d373-11eb-95f8-fcf6bb59360a.jpg)

macOS version: 11.4
Rectangle version: 
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):

**Comment by rxhanson** [comment]
That doesn't look like it's coming from Rectangle. Perhaps it's from BTT?

**Comment by lucky13820** [comment]
Oh, I feel dumb. It is from BTT.
