### ISSUE TITLE
3rd snapping **with the Mouse only**

### ISSUE THREAD

**Issue by daslicht** [rxhanson/Rectangle#499]
Hi,
is there a way to have 3rd snapping **with the Mouse only** ?
3 snapping zones instead of just left / right ?

The solution you suggesed implies using a BUTTON! Not the Mouse Only.\
Have a look how Microsoft Powertoys solves this ...
~Marc

**Comment by daslicht** [comment]
Thanks

**Comment by rxhanson** [comment]
Drag the window to the bottom of the screen for thirds, using the mouse only.

> Bottom left, center, or right third | Respective third
> Bottom left or right third, then drag to bottom center | First or last two thirds, respectively

https://user-images.githubusercontent.com/13651296/123517572-06ad5180-d6a2-11eb-9b58-b8000ddf7420.mov

If you're asking for Fancy Zones, that's a huge feature, worthy of a separate app in my opinion. I don't have plans to add that into Rectangle, although I see no reason to refuse a PR for Fancy Zones. I prefer my paid superset of Rectangle, [Hookshot](https://hookshot.app), over Fancy Zones, anyway - it's much faster and uses less system resources than a what a Fancy Zones implementation would use. Hookshot would use either a key or a mouse button (unless you combined it with my other app, [Hyperkey](https://hyperkey.app)), or you could configure [Multitouch](https://multitouch.app) to execute the Hookshot if you really didn't want a button press, and you just wanted gesture based window management.

**Comment by daslicht** [comment]
Thank you very much for taking time to create the video ! <3
