### ISSUE TITLE
Center Two Thirds

### ISSUE THREAD

**Issue by odnoletkov** [rxhanson/Rectangle#52]
This layout feels missing with all one-third and two-third options. I find this particular window position very useful – on a full-size display. Alternatives available – center one-third, full-screen – are significantly different.

The work around I currently use is two shortcuts – 'First Two Thirds' and 'Center Third'. Would be great to reduce that to a single dedicated shortcut.

In terms of shortcut itself looks like <kbd>⌃⌥R</kbd> would fit nicely in the current scheme. Between 'First Two Third' <kbd>⌃⌥E</kbd> and 'Last Two Thirds' <kbd>⌃⌥T</kbd>. That with alternate layout, not sure about the default one.

Let me know if you find the idea good – I may be able to submit a PR

**Comment by rxhanson** [comment]
I don't have a huge desire to add another thirds action, but I can see that a number of people want a more customizable "Almost maximize", which is essentially what you're looking for. In the next release, I was going to make both width and height of "Almost maximize" separately customizable (via command line - not in the UI at this time). That way, you could set the width to 2/3 and the height to 1/1 for "Almost maximize". 

Of course, this would use up the "Almost maximize" functionality, but I suspect that most users would be ok with it. The alternative would be adding separate custom action(s) that lets the user specify the window dimensions (something I don't have strong desire to add).

Thoughts?

**Comment by rxhanson** [comment]
https://github.com/rxhanson/Rectangle/releases/tag/v0.14

Execute the following terminal commands to modify the Almost Maximize ratio.

`defaults write com.knollsoft.Rectangle almostMaximizeHeight -float 1`
`defaults write com.knollsoft.Rectangle almostMaximizeWidth -float 0.66`

Then restart the app.

Feel free to reopen if something's not working right here.

**Comment by odnoletkov** [comment]
This is a good workaround for my case. Thank you for implementing this so quickly!

**Comment by bcaddy** [comment]
Is this still the best way to implement a "centered two thirds" or "center half" configuration?

**Comment by rxhanson** [comment]
@bcaddy Center half was added in a few releases ago. That's still the best way to implement centered two thirds.

**Comment by braydenm** [comment]
For anyone else who was a bit slow at deciphering the above comment, the way I got Center Two Thirds to work was with the following options together:

- Bind "Center Half" to a shortcut, and
- Set "Repeated commands" to "Cycle 1/2, 2/3, and 1/3 on half actions"

Now, pressing the Center Half shortcut twice will result in a centered two thirds (while also giving you the option of 1/2 and 1/2 width windows - perfect for ultrawide monitors)
