### ISSUE TITLE
Not working under Monterey Public Beta

### ISSUE THREAD

**Issue by Aluhut** [rxhanson/Rectangle#556]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12/ Monterey (Public Beta)
Rectangle version: 0.4.8
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

Rectangle just don't response on the shortcuts

**Comment by rxhanson** [comment]
Thanks for reporting. I don’t typically support macOS betas because a lot tends to shift around, leading to wasted time. I appreciate the heads up, though, since this will lead to a quicker bug fix turnaround if the issue still persists in a non-beta release.

**Comment by rxhanson** [comment]
Just curious, have you tried Rectangle on a later beta and seen different results?
