### ISSUE TITLE
Sparkle feed download urls all leading to 503 errors

### ISSUE THREAD

**Issue by discentem** [rxhanson/Rectangle#56]
It seems like all the download links in the [Sparkle Feed ](https://rectangleapp.com/downloads/updates.xml) are leading to HTTP 503 errors: 

> This page isn’t workingrectangleapp.com is currently unable to handle this request.
> HTTP ERROR 503

This is definitely affecting https://rectangleapp.com/downloads/Rectangle0.12.dmg and https://rectangleapp.com/downloads/Rectangle0.14.dmg

**Comment by rxhanson** [comment]
The download links in the Sparkle feed are restricted to the Sparkle user agent. Users can download any release from https://github.com/rxhanson/Rectangle/releases.

Do you have a specific reason for trying to download from the Sparkle feed rather than the releases page?
