### ISSUE TITLE
Window doesn't retain size when moving to lager screen

### ISSUE THREAD

**Issue by aaronmoodie** [rxhanson/Rectangle#567]
When moving a window that had been Maximised from a small screen to a large screen, the window doesn't retain its current size and automatically maximises on the large screen.

**Comment by rxhanson** [comment]
This is intended functionality, but it’s not a big change to make it configurable via terminal command in a future release.

**Comment by aaronmoodie** [comment]
@rxhanson oh right, I've just come from using Spectacle which doesn't function that way. If you're able to add a config, that would be great. Thanks!
