### ISSUE TITLE
Tab switching in Chrome via mouse click is extremely slow when Rectangle is running

### ISSUE THREAD

**Issue by zollole** [rxhanson/Rectangle#577]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

Tab switching in Chrome via mouse click is extremely slow when Rectangle is running. The issue goes away immediately after closing Rectangle. It only happens in one window with very (!) many tabs.

macOS version: BigSUR 11.5.2
Rectangle version: 0.48
Logs if applicable: none present

**Comment by zollole** [comment]
The issue is tied to the snap via drag option (2nd from the top). Disabling it fixes it.

**Comment by rxhanson** [comment]
Thanks for reporting this. About how many tabs does it take to trigger this behavior?

**Comment by zollole** [comment]
Well... more than 600, that's for sure. ;)

However, when the option is disabled, tab switching is as quick as in other browser windows. Also, tab switching via keyboard is totally unaffected.

**Comment by rxhanson** [comment]
Doing some housekeeping and looking back at this one. Since I don't have plans to put in a fix Rectangle side for this, I'm going to close it out. I'd be open to a pull request if anyone wants to prioritize it and put in a fix though.
