### ISSUE TITLE
Preference window opening at startup

### ISSUE THREAD

**Issue by wyaqoob** [rxhanson/Rectangle#579]
Rectangle preference opens at startup when the 'Launch on login' preference is checked. I'm not sure why, because just opening the app doesn’t do that.

**Comment by rxhanson** [comment]
The prefs window will open if Rectangle is launched while it is already running. Perhaps it is somehow launching twice? 

First I would uncheck the box for launch on login and uninstall the app. Then log out and log back in. Then reinstall the app and see if you still have the issue.

**Comment by wyaqoob** [comment]
Thank you! ANd sorry for the slow reply. Uninstalling and removing associated files then reinstalling worked.
