### ISSUE TITLE
Status menu not usable with keyboard

### ISSUE THREAD

**Issue by paulistoan** [rxhanson/Rectangle#598]
In macOS, the shortcut for moving the focus to the status menus is ^F8. I am able to use this to select the rectangle status menu and can press the down arrow to open it, but after that I am not able to press down again to select an entry, or start typing an entry name to select it. This behavior seems to work for other applications (using down arrow or typing an entry name). Are you able to address please? I like the functionality offered by Rectangle but would like to use it without shortcuts, but rather in a menu fashion where I could open a menu and select the action I want myself. Separately, I could also work around this limitation if I could send Rectangle commands via the Terminal, because I could couple it with something like [dmenu-mac](https://github.com/oNaiPs/dmenu-mac). From what I was able to find out though, this is not possible, am I correct?

**Comment by rxhanson** [comment]
I’ll take a look at getting keys in the menu working on the next release which should be out soon. I would love to add scripting but it’s a more serious endeavor than I expected and would take a chunk of time.

**Comment by paulistoan** [comment]
Thank you!
