### ISSUE TITLE
Report as window manager to system

### ISSUE THREAD

**Issue by yochem** [rxhanson/Rectangle#6]
Hi!

Small thing, but maybe worth adding. When using Spectacle, the system (or at least, `neofetch`), knows the WM is Spectacle. This is not the case with Rectangle. 
![image](https://user-images.githubusercontent.com/23235841/62498098-606eaf00-b7de-11e9-8a53-6ba34b755088.png)
![image](https://user-images.githubusercontent.com/23235841/62498111-6c5a7100-b7de-11e9-81f8-c5f54dc470c0.png)
(look for the `WM:` part)

I don't know if this is a neofetch or a Rectangle issue, and I couldn't get a result when searching for 'wm' in the Spectacle repo. Any ideas?

**Comment by ndpete** [comment]
Looks like this is functionality in neofetch
https://github.com/dylanaraps/neofetch/blob/751f9059ee8e2a95a48fbaf84617865713ec8e46/neofetch#L1641

**Comment by rxhanson** [comment]
https://github.com/dylanaraps/neofetch/pull/1300

Thanks for hunting that down @ndpete.

**Comment by yochem** [comment]
Thanks, @ndpete! I hope Rectangle will grow enough to be added to Neofetch :)

**Comment by rxhanson** [comment]
neofetch PR merged!
