### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fuzzy76** [rxhanson/Rectangle#61]
So here's the thing: I never used Spectacle.

Your homepage tells me nearly nothing about what this app does. The github projects page tells me _some_, but it has no real info about how to configure or use this thing. :-/

**Comment by rxhanson** [comment]
Excellent point. I come from a perspective that window managers (and apps with keyboard shortcut recorders) are so widely used nowadays that there's not much need to sweat the "intro" details in documentation, but this is proof that it's not a good assumption to make (it's also a nice sign that Rectangle is starting to become more mainstream). A couple of questions to help me improve this:

1. Did you try installing the app first and then start looking for documentation, or were you deterred by the lack of documentation? 
1. If you installed the app first, at what point did you feel like you needed documentation?
1. If there was both a video and written documentation on how to configure and use the app, which would you use?
1. Out of curiosity, where did you hear about the app?

To at least get you up and running before things are documented, the functionality of Rectangle is nearly identical to Magnet. There's a ton of youtube videos on Magnet, if you are the type that prefers to watch a video.

Some quick details that should help as well:

- When you first run Rectangle, you should be prompted to authorize it in System Prefs for Accessibility. After authorizing it, the config window should be displayed. 
![image](https://user-images.githubusercontent.com/13651296/71896594-7cdb9280-3154-11ea-83a7-70b71c6df9d4.png)

- Each window action can be configured with a keyboard shortcut via the keyboard shortcut recorder (I think this should be self-explanatory).
- At this point, all of these keyboard shortcuts that are configured are active. You can try it out by simply pressing the keyboard shortcut combination for a window action.
- The main feature that's undocumented is dragging windows to snap them.
- If you drag a window to the point where your cursor is at the edge of the screen, an overlay will display that shows where your window should move/resize to when you release the click. Top is maximize, right & left are halves, corners are for quarter screen in the corners. Bottom is thirds.

If you find that you like the app and would like to contribute, a Norwegian translation would definitely be welcome :)

**Comment by rxhanson** [comment]
The screenshot has been added to the readme, along with a blurb on window snapping by dragging.

Closing this one out.
