### ISSUE TITLE
system error chime on macOS 12.0.1

### ISSUE THREAD

**Issue by hjobrien** [rxhanson/Rectangle#629]
Hi apologies if this is a known issue, but ever since I updated to macOS Monterrey, when I use either my existing keyboard shortcuts or use the button in the menu bar to resize windows I hear the macOS error chime (its like a blip, the same thing when entering an invalid terminal command). this repros 100% of the time for me, let me know if there would be helpful logs for me to upload for this, thanks!

**Comment by rxhanson** [comment]
I never experienced this, but it sounds like just restarting Rectangle once fixes it.

**Comment by hjobrien** [comment]
oh I feel dumb, could have sworn I tried that already but I did that again and it fixed it, thanks!
