### ISSUE TITLE
Unable to obtain window id

### ISSUE THREAD

**Issue by tatsuya** [rxhanson/Rectangle#630]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: macOS Monterey 12.0.1
Rectangle version: 0.49 (54)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

```
2021-11-08T09:39:03-05:00: Unable to obtain window id
```

Hi 👋 First of all thanks for developing and maintaining this app. It has been my favorite app for a long time.

I wonder if this was a known issue. I am getting an error `Unable to obtain window id` in the debug logging and am looking for a solution.

**Comment by tatsuya** [comment]
Never mind. I restarted the OS again and the issue was gone.

**Comment by paraita** [comment]
I had the same problem, might be specific to Monterey ?
Thanks for the solution :)

**Comment by Ryanb58** [comment]
Had the same issue after updating to Ventura 3.1 on my intel 16". Restart fixed it.
