### ISSUE TITLE
Display rotation not always taken into account

### ISSUE THREAD

**Issue by ct-clearhaus** [rxhanson/Rectangle#643]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.8
Rectangle version: v0.49 (54)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): N/A

Edit: I've adjusted the display rotation on one of my displays using "System Preferences.app" -> "Displays" -> "Rotation: 90º":
<kbd>
<img alt="Screenshot 2021-11-17 at 10 47 27" src="https://user-images.githubusercontent.com/6168505/142177190-28d2fcb8-6414-4ab6-b04f-d97ce0259f79.png" />
</kbd>

When, for instance, triggering the "Left Half" shortcut, the window fills the left half of the screen; perfect! However, when triggering the "First Third" shortcut, the window fills not the left-most third, but the top-most third of the screen.

Shortcuts affected (that I've stumbled upon):
* First Third
* Center Third
* Last Third
* First Two Thirds (I'm missing "Center Third", but that's another story 🤗 )
* Last Two Thirds

**Comment by rxhanson** [comment]
Rectangle uses display w/h for every window arrangement to determine if it should perform horizontal or vertical versions of most commands. I’m not quite sure precisely what is being incorrectly positioned for you based on this logic. Perhaps you could attach logs and your expected outcomes?

**Comment by rxhanson** [comment]
Doing some housekeeping and closing this one out, but feel free to comment further.
