### ISSUE TITLE
Missing `frontmost.app` replacing

### ISSUE THREAD

**Issue by sh-cho** [rxhanson/Rectangle#647]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.0.1
Rectangle version: latest ([016d58ba1b7ef7962f48ed28f6b4d4112f6a6709](https://github.com/rxhanson/Rectangle/tree/016d58ba1b7ef7962f48ed28f6b4d4112f6a6709))
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

https://github.com/rxhanson/Rectangle/blob/016d58ba1b7ef7962f48ed28f6b4d4112f6a6709/Rectangle/AppDelegate.swift#L415-L418

In here, `frontmost.app` replacing is missing.

<img width="310" alt="Screen Shot 2021-11-18 at 3 39 01 PM" src="https://user-images.githubusercontent.com/11611397/142365380-6dbc9b83-cb63-4cb5-bd25-245e9103353e.png">

So If I firstly open Rectangle and if `Show Todo Mode in menu` option is not checked, I can see frontmost.app string here.

Having said that, it's weird that I didn't enable `Show Todo Mode in menu` but Todo menu is still showing. It just happens when I didn't touch that option.

If I enable and disable that option, Todo menu is no longer showing normally.

**Comment by rxhanson** [comment]
Thanks for reporting. I’ll fix this in the next release

**Comment by rxhanson** [comment]
This should now be fixed in v0.50. Please reopen if anyone has further issues.
