### ISSUE TITLE
Rectangle greys out when I use VS Code. Works for all other apps except VS Code.

### ISSUE THREAD

**Issue by katiepestotnik** [rxhanson/Rectangle#649]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: MONTEREY 12.0.1
Rectangle version: 0.49
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):  No logs

**Comment by rxhanson** [comment]
Try restarting VSCode. There’s nothing that can be done Rectangle side to fix this.
