### ISSUE TITLE
Can not control the windows opened by other user

### ISSUE THREAD

**Issue by Zephyr-D** [rxhanson/Rectangle#650]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Big Sur 11.6
Rectangle version: 0.49
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

Thanks for the great app. I'm reporting one (potentially unsupported) issue: when I have an app opened by another user (by using `su - user` in the terminal and opening the app), its window can not be controlled by Rectangle. I do notice that such a feature is not supported by other similar snapping apps as well, so please feel free to close this issue if it's not feasible.

**Comment by rxhanson** [comment]
Right, as you suspected, this is due to macOS permissions and is not something controllable by Rectangle. Thanks for posting, though!
