### ISSUE TITLE
The key combination cannot be used

### ISSUE THREAD

**Issue by Jakobud** [rxhanson/Rectangle#657]
- [X] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.5.2
Rectangle version: 

I recently switched from Spectacle to Rectangle. I use Rectangle with default Spectacle shortcuts. The shortcut I use the most is "Maximize". The default shortcut for this is ALT+CMD+F. However I have always preferred to use the shortcut ALT+CMD+C instead. It's just easier and faster for me to hit that on the keyboard.

I notice that in Rectangle, that ALT+CMD+C is already set to "Center". So I remove this shortcut and then try to change "Maxmimize" to use this shortcut. I get the following:

![image](https://user-images.githubusercontent.com/87356/142900916-b4ad407a-d05b-4a8b-ba13-a19a197c1ec3.png)

So a couple things:

1. What is "Copy Style"? I don't see this in any menu item on any of my open programs.
2. Why is ALT+CMD+C available to use by default for "Center" in Rectangle but when you try to set it for something else would can't because it would interfere with "Copy Style"? How did it not interfere when used as the default shortcut for Center? Doesn't make sense.
3. I've used ALT+CMD+C with Spectacle for literally years without issue. Not sure why this is some sort of new issue now.

**Comment by rxhanson** [comment]
Check the box in the prefs for "Remove keyboard shortcut restrictions". I put in a fix so this won't be blocked in the next release, regardless of that setting.

**Comment by Jakobud** [comment]
Yes I saw this option. Thank you. I still don't know what the Copy Style is referring to. Oh well. Thanks

**Comment by rxhanson** [comment]
Copy Style is a font menu item that is in the default set of menu items for all Mac apps, which are there unless the developer removes them.

**Comment by Jakobud** [comment]
A little bit of UX feedback for you. Instead of having a popup that says a key can't be set because its restricted to XYZ, have the popup say "the shortcut is currently set to OSX's Copy Style function. Do you want to override this?" (Yes/No) or something like that. Then you could eliminate the preference for enabling setting of restricted shortcuts since the popup now serves 2 purposes. It serves as a warning and also serves as a way to override restricted shortcuts.
