### ISSUE TITLE
Fixed window location

### ISSUE THREAD

**Issue by rickysullivan** [rxhanson/Rectangle#66]
With Spectacle, any fixed sized window will center vertically and horizontally within the dimension/size given.

e.g.

I can cycle through half (or third/two thirds) I want an app to fill and it centers in both axis:

![Spectacle](https://user-images.githubusercontent.com/437480/72226011-fb22b380-35f0-11ea-94af-171d9fef844b.gif)

In Rectangle, it appears to pin the window to the x:0, y:0 of that area:

![Rectangle](https://user-images.githubusercontent.com/437480/72226012-037aee80-35f1-11ea-847b-939eb1588b30.gif)

If this isn't a bug, It would be nice to have an option to allow windows to center within their area.

macOS version: 10.14.6
Rectangle version: 0.15 (19)

**Comment by rxhanson** [comment]
Right. I agree that the desired behavior would be that of Spectacle's, with centering in the area. This will be slotted for the next release. 

Thanks for taking the time to make the gifs, definitely helpful for quickly understanding the issue.

**Comment by rxhanson** [comment]
Ok, try out this build and let me know if it looks good:
https://github.com/rxhanson/Rectangle/releases/tag/v0.16

**Comment by rickysullivan** [comment]
Looks good, ship it.

**Comment by rxhanson** [comment]
Thanks for testing it out! It's now officially released as part of v0.17, which will be published to the update channel momentarily. Closing this out.

**Comment by rickysullivan** [comment]
Neat.
