### ISSUE TITLE
moveCursor and autoMaximize not in Defaults.array

### ISSUE THREAD

**Issue by Aaron-Rumpler** [rxhanson/Rectangle#663]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

The `moveCursor` and `autoMaximize` preferences aren't in `Defaults.array`, meaning they won't be imported or exported. Is this simply an oversight or is there a reason for not importing and exporting these preferences?

**Comment by rxhanson** [comment]
Thanks! Simply an oversight. Feel free to put in a fix, or I'll do it when I get a chance.

**Comment by Aaron-Rumpler** [comment]
I'll put it in with #662.

**Comment by Aaron-Rumpler** [comment]
Fixed in #662
