### ISSUE TITLE
Swift runtime is embedded multiple times

### ISSUE THREAD

**Issue by Cyberbeni** [rxhanson/Rectangle#667]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.0.1 (21A559)
Rectangle version: 0.49

You can add `@executable_path/../../../../../Frameworks` to `Runpath Search Paths` of RectangleLauncher (since it launches the app relative to its location, moving it to a different spot already breaks it)
I don't know how to skip copying the Swift runtime twice but removing them from the exported app then resigning it should work.

**Comment by rxhanson** [comment]
Perhaps the smarter way to go about launch on login is to use the library by Sindre Sorhus. If that library doesn’t have this issue then I’ll refactor to that in the next release.

**Comment by Cyberbeni** [comment]
Also, what is the reason to use a separate app just to launch Rectangle at startup?

**Comment by rxhanson** [comment]
I won’t go into too much detail, but it’s the only way to provide this setting within the app that Apple hasn’t deprecated. I think the library I mentioned still does this, too.

**Comment by dabrahams** [comment]
Surprises me to see this; hasn't Swift's runtime been in the OS for a few years now?

**Comment by rxhanson** [comment]
Rectangle supports older versions of macOS.

**Comment by dabrahams** [comment]
Sure, sorry, I just meant I was surprised to see that it was a problem for someone running macOS version: 12.0.1 (21A559)

**Comment by rxhanson** [comment]
The Swift runtime gets bundled with the app unless the supported version is set to Mojave or later.
