### ISSUE TITLE
Function key shortcuts aren't displayed properly from menu bar

### ISSUE THREAD

**Issue by claytonrcarter** [rxhanson/Rectangle#69]
macOS version: 10.13.6  
Rectangle version: 0.15 (19)

Hi. I just downloaded the app and have been playing around with it. Great app; thanks for it!

If I set some shortcuts to the extended function keys on my keyboard, they don't appear to be displayed correctly in the menu that drops down from the menubar. They all just display as "F", not "F18", "F19", etc. It doesn't appear limited to the extended F keys, either; the same thing happens if I use "F5" as a shortcut. Note that they *are* displayed correctly in the preferences window.

In the preferences window:  
![Screen Shot 2020-01-16 at 9 13 36 AM](https://user-images.githubusercontent.com/1420419/72531953-85ad2200-3840-11ea-842b-fdf5baf5053e.png)

In the menu bar dropdown:  
![Screen Shot 2020-01-16 at 9 13 43 AM](https://user-images.githubusercontent.com/1420419/72531954-85ad2200-3840-11ea-941a-34d531f08b60.png)

Thanks again!

**Comment by claytonrcarter** [comment]
FYI, this still exists in 0.19. (I had installed 0.15 w/ `brew`, but just upgraded via the direct download.)

**Comment by rxhanson** [comment]
This got auto closed by GitHub upon merging the associated PR, but I haven't drafted a release that includes this change yet. I'll post back here when I generate a release (usually every couple of weeks or so).

**Comment by claytonrcarter** [comment]
Awesome. Thank you @rxhanson and @lexmiln! No rush; the app still works
just great w/o this.
