### ISSUE TITLE
Ability to define own grid "size"

### ISSUE THREAD

**Issue by M-Porter** [rxhanson/Rectangle#7]
Thoughts or opinions on letting the user define their own grid size? I use an ultra-wide monitor and for my setup, 1/3rds do not make sense for my use case. 1/4 grid does (terminal right most 1/4, editor middle 1/2, left size whatever else i want).

I'll be happy to open a PR and help out but I didn't want to start the work if you weren't on board with the idea.

**Comment by rxhanson** [comment]
In my opinion, the main difficulty surrounding this idea is the UI. Off the top of my head, the best UI for user defined grids is, well, a visual grid like in Moom. An alternative is having a handful of keyboard shortcut recorders with size & location input fields. Beyond that, there could be a table view that holds a customizable amount of shortcuts, which also has some inherent complexity. Any way you cut it, adding this kind of customization in the UI brings with some level of complexity.

It is possible to ignore UI entirely and let the "thirds" be configured via user defaults, and that might be the best way to go about it at first (and maybe always, since this is most likely something wanted primarily by a smaller percentage of users). Going this route, the only thing to be aware of is that the thirds calculations look at the screen ratio to determine appropriate third for landscape vs portrait oriented monitors. 

I'm on board with the approach that does not involve any UI changes. This also is dramatically less work. If you're good with that, I'm definitely up for reviewing any PRs that come my way.

Thanks!

**Comment by rxhanson** [comment]
I don't have any plans to implement this myself so I'm going to close it out. I don't mind accepting a PR if it looks good, though.

If I were to implement it, I would create two NSUserDefaults variables - one for the x value of each dividing line between screen thirds. This would be a string, so it could take "1/3" or "1/4", etc. Then it would just be a matter of parsing the string into a value and modifying the screen thirds "WindowCalculations" to handle the parsed strings. (Note that the two variables would be translated to y values for portrait mode).

The user would then just have to execute terminal commands to modify the two variables and restart the app. If you have any other questions, feel free to ask away.

**Comment by filoozom** [comment]
Hi, I think I might give this a shot with a bit of a more complex grid than just ratios of thirds. Basically, the idea would be that the user could specify `x`, `y`, `width` and `height` in ratios like you suggested. This way, we could have something like:

```
+---+---------+---+
| 1 |         | 1 |
+---+         +---+
| 1 |    3    | 1 |
+---+         +---+
| 1 |         | 1 |
+---+---------+---+
```

with a file looking like:
```
[
  { x: 0, y: 0, width: 1/5, height: 1/3, shortcut: 'control+option+u' },
  { x: 0, y: 1/3, width: 1/5, height: 1/3, shortcut: 'control+option+j' },
  { x: 0, y: 2/3, width: 1/5, height: 1/3, shortcut: 'control+option+m' },
  { x: 1/5, y: 0, width: 3/5, height: 1, shortcut: 'control+option+k' },
  { x: 4/5, y: 0, width: 1/5, height: 1/3, shortcut: 'control+option+o' },
  { x: 4/5, y: 1/3, width: 1/5, height: 1/3, shortcut: 'control+option+l' },
  { x: 4/5, y: 2/3, width: 1/5, height: 1/3, shortcut: 'control+option+.' }
]
```

At this point, it would also be easy to replace the right column with just two panels of height `1/2` for example.

I guess this leaves room for error, but it's the most versatile configuration file I could think of. I would also love to be able to change this on a per-screen basis, but I guess that's for a future version.

I was thinking about replacing basically every `*Calculation` class with one single `CustomCalculation` that would handle basically all of this.

What do you think? This would be very powerful for a bit more advanced users who want to take the time to configure their optimal layout. I for one would love to use this on my ultrawide monitor!

**Comment by rxhanson** [comment]
@filoozom Sounds to me like what you're looking for is hammerspoon: 
https://www.hammerspoon.org/go/
Check out the "Window Sizing" section there.

This degree of functionality is a little out of the scope of Rectangle - although I have thought about extracting the window calculation and movement functionality out of the app and into a library so things like this could be quickly written as new apps.

**Comment by mittalyashu** [comment]
I read few comments but not sure if this idea has been considered or not.

How about creating custom defined blocks?

You can say this feature is a simpler version of **ability to define own grid "size"**

**Comment by mupkoo** [comment]
I kinda agree that having the ability to specify the number of steps will be helpful, so instead of have 1/3 be a step, a person can decide that 1/4. 

In my case, I will probably go with 1/6 as I am working on a 13 inch display and a lot of times I find my self that I do "go to 2/3 and then resize up until I reach something around 5/6"

**Comment by leocaseiro** [comment]
This is an extension to hammerspoon that implements similar functionality https://github.com/peterklijn/hammerspoon-shiftit
It seems you can create your own sizes.

**Comment by dwt** [comment]
Thanks for the link to Hammerspoon, that seems like a great way to configure this myself. Just for posterity, I'll try to record my use case here.

I really like to work with small displays in 13"-14" laptops, and thus found ways to maximize my usable screen real estate.

I really like to work with overlapping windows, that is, a core layout of something like this:

```
|-------|----------------------------|
|       |                            |
|   1   |                            |
|       |               3            |
|-------|                            |
|       |                            |
|       |----------------------------|
|    2                  |    4       |
|------------------------------------|
```

- I use `1` to display part of a messenger, just enough to let me easily see if I got a new message. The window is usually slightly to much larger than the space allotted to it, but is overlapped by `2` and `3`.
- I use `2` for the terminal. Usually multiple tabs, to run docker containers and whatnot, but always in the foreground is the terminal running unit-tests triggered on save in the editor showing in `3`. The key here is that the last lines are really important to get the summary of the test execution, and then the start of some of the lines above it are visible as they usually give a good hint at what went wrong in the test I'm working on. Most of the window is hidden behind the editor, and the top of the terminal usually hides part of the messenger above.
- I use `3` for my editor, maximizing space for it. This is always in the foreground
- `4` is used on an as needed basis. Often by terminals showing log output from a running application, but can also be the bottom of a web browser window to make it easy to switch to while debugging something, or maybe a documentation window. Not as rigidly assigned as the others.

See an example here:
<img width="1512" alt="Untitled" src="https://github.com/user-attachments/assets/77d32b82-e297-46c0-9bfc-4e38fbd6edae">

I think that I can repurpose  the `move to the side of the screen` functionality, to ease setting this up? Or I can go for hammer spoon, but, I really like a UI to configure stuff. Ah well.

Still I would love if it was easier to use Rectangle.app to make this kind of setup easier to automate. Basically I would like to specify shortcuts that assigns a size (in percent of screen estate in hight and width) and then sticks the window to up to two sides of the screen.

**Comment by Aaron-Rumpler** [comment]
[Rectangle Pro](https://rectangleapp.com/pro) will let you do exactly this.
