### ISSUE TITLE
Sparkle Feed has incorrect download URL

### ISSUE THREAD

**Issue by hkim823** [rxhanson/Rectangle#70]
macOS version: 10.15
Rectangle version:0.19

I'm trying to automate deployment of Rectangle and using Autopkg https://github.com/autopkg/autopkg as a means to always have the latest release of Rectangle.  I've created a recipe based on the Sparkle feed on your website https://rectangleapp.com/downloads/updates.xml and when I try to use this info, it points to a url in the format of "https://rectangleapp.com/downloads/Rectangle{ver}.dmg" instead of "https://github.com/rxhanson/Rectangle/releases/download/v{ver}/Rectangle{ver}.dmg" 

Could you fix the update.xml file to reflect the true download locations for Rectangle?

**Comment by rxhanson** [comment]
The way to get the latest download from GitHub is to parse the JSON here: 
https://api.github.com/repos/rxhanson/Rectangle/releases/latest

There's a download link within that JSON.

The Sparkle url is right, it's just restricted.
