### ISSUE TITLE
Todo App gets positioned under the dock

### ISSUE THREAD

**Issue by hsingireddy** [rxhanson/Rectangle#713]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.6.2
Rectangle version: 0.49 (54)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 
2022-01-08T21:11:12-05:00: Unable to obtain window id
2022-01-08T21:11:12-05:00: AX sizing proposed: (800.0, 1415.0), result: (800.0, 1415.0)
2022-01-08T21:11:12-05:00: AX position proposed: (2640.0, 0.0), result: (2640.0, 25.0)
2022-01-08T21:11:12-05:00: AX sizing proposed: (800.0, 1415.0), result: (800.0, 1415.0)

Environment:
Dock is position to the right of the screen and Reflow Todo shortcut is pressed

Expected outcome: 
TodoApp will be placed to the right of the screen next to the dock. All the other windows will be moved to the non-todo part of the screen. There will be no gap between the "other window" and "Todo App"

Actual outcome:
Todo App is placed on the right edge of the screen, under the dock. Other windows reflown are still attached to the Todo App without any gap. But, when you run shortcuts that place windows to the right of the screen (Right half, last two thirds etc.) they leave a dock sized gap between the window and the Todo App. They are leaving the correct width (Dock + todo App) but because the Todo app is under the dock, it leaves a gap.

**Comment by rxhanson** [comment]
If you have window gaps configured, v0.50 should fix the gap around the Todo App window.

A macOS bug causes the windows to be placed under the dock in certain scenarios - most commonly seen when the dock is moved to a different display or unhidden. Unfortunately, there's not a good workaround for it.

**Comment by hsingireddy** [comment]
Here is some more info on existing behavior with screenshots

**_-- Dock is on the left --_** 

Reflow Todo command moves the application (Safari, in this case) window under the dock. It should stop at the dock unless the window was already placed under the dock by the user.

Reflow command output ::
![Left-Dock](https://user-images.githubusercontent.com/70454212/152099449-7295a7a9-437c-448d-a1a3-999e62cb579c.png)

Other commands like Maximize will correctly place the Safari window next to the dock.
Maximize command output on the Safari Window ::
![Left-Dock-Maximize](https://user-images.githubusercontent.com/70454212/152099937-cb9acb05-1570-4c00-b8f4-00761632f813.png)


**_-- Dock is on the right --_**
Reflow Todo command moves the todoWindow (Word, in this case) under the dock. It should stop at the dock.
Notice how Safari window is placed at the edge of the todo window. 

Reflow command output ::
![Right-Dock](https://user-images.githubusercontent.com/70454212/152100154-03a834ed-089c-4763-ae8d-2db60f582278.png)

Next, Commands like Maximize on Safari window now shows the gap between the todoWindow and the application window. Todo window was supposed to fill that gap during the reflow todo action. 

Maximize command output on the Safari Window ::
![Right-Dock2](https://user-images.githubusercontent.com/70454212/152100249-7f56b4e9-a872-4e04-95fc-03c491092e23.png)
