### ISSUE TITLE
Rectangle works or (mostly) not and I don't habe any clue why

### ISSUE THREAD

**Issue by Aluhut** [rxhanson/Rectangle#741]
- Rectangle always works just randomly, sometimes with the one monitor, then the other. Sometimes it works after restart or stand-by, then again just not (most of the times). 
Unfortunately, I have the behavior from the beginning (over two years) and actually love the app. Could you please help me to make it work permanently?

macOS version:
12.2
Rectangle version:
0.50
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 
unfortunately empty

**Comment by rxhanson** [comment]
I'll need a little more information about what specifically is not working. 

- Do commands work from the menu bar, drag to snap, or keyboard shortcuts? 
- Is there anything that changes when you notice Rectangle stop working? For example, opening the macOS on-screen keyboard will cause windows to switch to an alternate display mode that conflicts with the default behavior of the window management API.

**Comment by Aluhut** [comment]
> I'll need a little more information about what specifically is not working.
sure anything that I can provide :)
> 
> * Do commands work from the menu bar, drag to snap, or keyboard shortcuts?
I do have that issue right now. And no, nothing works now, neither the shortcuts, nor when I try it with the mouse via the menu bar 
> * Is there anything that changes when you notice Rectangle stop working? For example, opening the macOS on-screen keyboard will cause windows to switch to an alternate display mode that conflicts with the default behavior of the window management API.
Nope, my beste guess is, it must have something to do with the Display management. Im using several different monitors (for different purposes) and after switching the status of rectangle seems to change. Sometimes it works then, sometimes it stops. That seems to be the only constant that I can recognize. 


best wishes

**Comment by cwightrun** [comment]
I'm experiencing something similar. The hotkeys only work part of the time. I'll try to submit more information after work.

**Comment by cwightrun** [comment]
Note: I've enabled "Remove keyboard shortcut restrictions" in the settings, and it appears to be behaving consistently.

**Comment by Aluhut** [comment]
> "Remove keyboard shortcut restrictions"

Sorry but where can I find that setting?

**Comment by rxhanson** [comment]
"Remove keyboard shortcut restrictions" is just for allowing the shortcut recorder to record shortcuts that are typically used by other apps or within macOS. It does not affect the behavior of the shortcut execution or any other parts of the app. It's probably localized as something a little different.

**Comment by Aluhut** [comment]
Yesterday came the update and now it works!!!
Huge thanks! Life long and prosper!

**Comment by Aluhut** [comment]
Sorry but I have the same Issue again. A restart makes it work again, but that's honestly not a good solution.
It seems, after every sleep mode phase, is the reaction not more available.

**Comment by rxhanson** [comment]
@Aluhut, I think this might be due to something outside of Rectangle, and I still don't have enough information to troubleshoot or do anything about this. Perhaps you could create a screen recording, and show the logging while it's not working? To show the logging, hold the option key and select "View Logging" in the menu.

**Comment by rxhanson** [comment]
Doing some housekeeping and closing out old issues. Feel free to comment further if there's any updates here.
