### ISSUE TITLE
Rectangle not updating to 0.52 from the update button

### ISSUE THREAD

**Issue by hisel-sabermetrics** [rxhanson/Rectangle#767]
Rectangle not updating to 0.52 from the update button and keep saying that 0.51 is the latest version even after downloading from github.

macOS version: 12.2.1
Rectangle version: 0.51, 0.52
![Screenshot](https://user-images.githubusercontent.com/96913686/155921215-1736f139-f594-4d51-87ca-f993bbb7a7fa.png)

**Comment by rxhanson** [comment]
Thanks! It's working now.
