### ISSUE TITLE
Reflow TODO Placing window in incorrect location

### ISSUE THREAD

**Issue by akraemer007** [rxhanson/Rectangle#774]
**- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Monterey 12.2.1
Rectangle version: 0.53 (59)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

I don't use TODO mode, but I frequently use Reflow TODO. I updated rectangle recently and I am getting the incorrect behavior when activating Reflow TODO both from the menu bar and my assigned hotkeys. As seen in the second image below, Reflow TODO doesn't snap the todo to the right, it moves it mostly off screen with just a little bit of the todo window showing. I'd like the old behavior where the todo window is snapped to the right.

Side note: I get my desired position if I just enable TODO Mode, as shown in image 3. As far as I can tell, the incorrect behavior is limited to Reflow TODO.

Starting position:
![image](https://user-images.githubusercontent.com/12884043/156429457-82f0daeb-a6e8-422c-a3ad-1b8169ae5a8a.png)

After activating Reflow-TODO:
![image](https://user-images.githubusercontent.com/12884043/156429598-27fc6cf5-db9f-49b8-8051-dd5ff06e7a04.png)

Just using TODO-mode:
![image](https://user-images.githubusercontent.com/12884043/156429722-bb66e13b-4b0e-4533-a49e-912d90ba45ae.png)
**

**Comment by rxhanson** [comment]
Thanks for reporting. I noticed this as well, after the release was out the door. I'll plan a fix for the next release.

**Comment by stefmatik** [comment]
First of, awesome app!
just to clarify, since it does not seem to be only in Reflow Todo:
If I save the current layout which is asymmetrical and load it, it moves everything to the left, center(middle) or right. But I want my window to be in this weird position which is neither of the 3 above.

**Comment by rxhanson** [comment]
Closing this one out (it was fixed in a previous release). @stefmatik If you're still having an issue in Rectangle Pro, please open an issue in the tracking repo for Pro: https://github.com/rxhanson/RectanglePro-Community. I'm not sure I understand exactly what the issue was that you ran into, so I might need a little further information as well.
