### ISSUE TITLE
Rectangle does not prompt to use Spectacle shortcuts

### ISSUE THREAD

**Issue by hassanfa** [rxhanson/Rectangle#778]
Hi,

I have been using both Spectacle and Rectangle on my two Air and Pro. After migrating to Rectangle on my Macbook pro, it didn't prompt to use Spectacle shortcuts. But on the other one it did. I tried reinstalling to make that prompt appear again, but it does not.

Is there a way to revert back all shortcuts in Rectangle to use Spectacle shortcuts?

Thanks.

**Comment by rxhanson** [comment]
Click the restore default shortcuts button in the settings tab, and you'll be prompted there.
