### ISSUE TITLE
Is there a config for changing window size of a half or third? 

### ISSUE THREAD

**Issue by georgetony** [rxhanson/Rectangle#78]
Not a feature request. Just a question on how to change some settings. Is there an option that I can set that specifies width and or height of a window for a specific resize. For example, I like to increase the width of windows when I select First Two Thirds.

**Comment by rxhanson** [comment]
This isn't currently supported, but I'm not opposed to a pull request with this functionality. This is similar to https://github.com/rxhanson/Rectangle/issues/7.
