### ISSUE TITLE
Window does not keep size when mouse clicks it

### ISSUE THREAD

**Issue by amp-td** [rxhanson/Rectangle#780]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.2.1 (21D62)
Rectangle version: Version 0.53 (59)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): No logs are reflected here.

I have created a .gif to showcase what is occurring.

![CleanShot 2022-03-16 at 14 17 55](https://user-images.githubusercontent.com/101747017/158671204-86244dc0-a1c7-48fa-9ade-1f8fdfcc2087.gif)

![CleanShot 2022-03-16 at 14 21 57](https://user-images.githubusercontent.com/101747017/158672197-a6e05910-74ab-4537-8660-6c175bce8ee4.gif)

Anytime the window is selected with the cursor, that window reverts to it's previous size/state prior to any change from Rectangle.

**Comment by rxhanson** [comment]
That’s intended functionality. If you don’t want that behavior then uncheck the box for restoring window size when unsnapping.

**Comment by amp-td** [comment]
well, that's embarassing. 😭
thanks for clearing that up!
