### ISSUE TITLE
Doesn't work for WhatsApp

### ISSUE THREAD

**Issue by takim-13** [rxhanson/Rectangle#783]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

Every other application works but seems like it has a problem with WhatsApp. It doesn't do anything, it just plays the MacOS error sound. Great app hope you can solve it!

macOS version: 12.2.1
Rectangle version: v0.53 (59)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):

**Comment by rxhanson** [comment]
Sorry, that’s on WhatsApp to fix. You can try restarting WhatsApp.
