### ISSUE TITLE
Add a "Center Two Thirds" window option

### ISSUE THREAD

**Issue by CaaZaa** [rxhanson/Rectangle#788]
Similar to "First Two Thirds" and "Last Two Thirds", a "Center Two Thirds" window option would greatly help my workflow.

**Comment by rxhanson** [comment]
Duplicate of https://github.com/rxhanson/Rectangle/issues/52 (and others).

You can use a terminal command to get it: 

https://github.com/rxhanson/Rectangle/blob/master/TerminalCommands.md#almost-maximize

https://github.com/rxhanson/Rectangle/blob/master/TerminalCommands.md#add-an-extra-centering-command-with-custom-size

Alternatively, you can use the custom shortcut builder in [Rectangle Pro](https://rectangleapp.com/pro).

**Comment by PierBover** [comment]
I'm missing this feature too.

Is it possible to customize this but for window dragging instead of keyboard commands?

**Comment by rxhanson** [comment]
@PierBover Sorry for the delay. At the moment it is not an option in Rectangle. I don't have plans to add it in myself at this time, but see no reason to turn down a pull request for it.

(This is available in Rectangle Pro)

**Comment by PierBover** [comment]
> (This is available in Rectangle Pro)

I actually looked at Rectangle Pro and couldn't find this feature.

Are there any docs I could check?

**Comment by rxhanson** [comment]
![Image](https://github.com/user-attachments/assets/761eb3fb-29b0-4c3d-a89c-06375a720db7)

![Image](https://github.com/user-attachments/assets/fe89d96f-f5d2-43fa-9895-30175f689959)
