### ISSUE TITLE
Rectangle not working for other users on the system.

### ISSUE THREAD

**Issue by ysndr** [rxhanson/Rectangle#789]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

I'm working on a system with multiple user accounts.
While all accounts can start Rectangle, shortcuts are only recognized by Rectangle for one user.
I will do more testing later whether it works with only one user logged in.

macOS version: 12.2.1
Rectangle version: 0.53

**Comment by rxhanson** [comment]
I've tested this before and it worked fine. Is there anything unusual about the way your users are configured?

**Comment by ysndr** [comment]
My bad, it does indeed seem to work. However it initialized with a whole different configuration, so none of the shortcuts worked as expected
