### ISSUE TITLE
Right-click on traffic lights

### ISSUE THREAD

**Issue by xrr** [rxhanson/Rectangle#80]
Rectangle could be a nice open-source replacement to Flexiglass with the following features :
- right-click on the green traffic light will maximize the window
- right-click on the red traffic light will exit the application (I personally don't use this one)

Regards

**Comment by rxhanson** [comment]
I don't have plans to implement this at this time, but I would consider merging a pull request for it.

**Comment by 211217613** [comment]
would you consider paid feature requests via patreon?

**Comment by rxhanson** [comment]
@211217613 I appreciate the offer. I would consider paid feature requests, but just not yet. Gotta get a few things out the door and free up some time, which might take a while. I'll post back when the time is right 🙂
