### ISSUE TITLE
Doesn't work with IINA windows

### ISSUE THREAD

**Issue by bnaman50** [rxhanson/Rectangle#809]
Hello, 

I use [IINA](https://github.com/iina/iina) for my mac. However, rectangle shortcuts don't work properly with it. I am not sure if this is an issue with Rectangle or IINA. I am just mentioning here to bring to your notice. Hope you can figure it out. 

macOS version: 10.14.6 (Mojave)
Rectangle version: 0.49

Thanks, 
Naman

**Comment by rxhanson** [comment]
Thanks for reporting. 

At this point, if any applications don't work with Rectangle then it's because they are doing something nonstandard with their windows or they have a bug where the windows are failing to respond to the window management (accessibility) API. For apps that have the latter issue, you can try just restarting that app. 

From my perspective, there's nothing that can be done Rectangle side, so you'll have to file an issue with IINA.

**Comment by Aaron-Rumpler** [comment]
This looks to be by design. IINA keeps the aspect ratio of the window the same as the video that's playing, so it looks like when Rectangle tries to resize the window, the window is then shrunk on either the right or bottom to match the video aspect ratio.

**Comment by Aaron-Rumpler** [comment]
There might be a way of disabling that, but nothing was apparent at a quick glance in the settings. You would end up with black bars though if there is a way of disabling that.

**Comment by bnaman50** [comment]
@Aaron-Rumpler , I can understand this behaviour with Left/Right half. I checked it with VLC and they also had the same behaviour. Where it differed (and matters to me) is with the FullScreen option. 

Here is how it is with VLC --
![VLC](https://user-images.githubusercontent.com/5251592/166624916-a30e3ee4-24ef-46bf-911f-4f1242126033.png)


where as for IINA, there is empty space at the right --
![IINA](https://user-images.githubusercontent.com/5251592/166624925-6281999b-45fe-4fb0-a6ce-ff0af32d6175.png)

Sometimes, this space in on the bottom depending on the video resolution (I guess). It would be awesome if you could fix it? 

Thanks, 
Naman

**Comment by Aaron-Rumpler** [comment]
VLC looks to keep the width and simply change the height to match the aspect ratio (this can most easily be seen by snapping to the top and bottom halves, where VLC isn't contained within the area you try to snap it to). It also means that when maximising VLC, some of the content might end up off the bottom of the screen. Regardless, this behaviour is up to the application and isn't something Rectangle can change.

**Comment by bnaman50** [comment]
Thanks for your response, @Aaron-Rumpler .

It is actually a mistake on my part. I have posted this issue on IINA repo as well and I (mistakenly) thought I am interacting with IINA devs.  

Anyway thanks for clarification and all your help. 

Naman
