### ISSUE TITLE
Application is launched but invisible

### ISSUE THREAD

**Issue by pixmin** [rxhanson/Rectangle#81]
macOS version: 10.15.2
Rectangle version: 0.19 (brew)

When I launch the application, I can see it running in the activity monitor, but I have no way to access it, no icon in the menu bar, or in the dock, no window showing up when it starts.

I removed the configuration file ~/Library/Preferences/com.knollsoft.Rectangle.plist but it changed nothing.

I tried to pass it different parameters while launching it via the command line (/Applications/Rectangle.app/Contents/MacOS/Rectangle) but it didn't change anything.

I tried to remove / reinstall it. I'm at lost, how can I get it back?

Thanks.

**Comment by rxhanson** [comment]
Perhaps something is affecting the display of the menu item in the menu bar? Maybe you have too many icons in the menu bar and it's hidden by menu items?

When the application is launched while it is already running, the menu for the app should show up in the menu bar where the icon "would" exist. 

While the application is not running, disable the app in the macOS accessibility settings (System Prefs -> Security & Privacy -> Accessibility -> Privacy). Then start the app. It should prompt you to enable it in that same location, and after doing so the prefs window should open. Obviously, you wouldn't want to do that every time, but it can be used as a sanity check to look at the preferences and just make sure that the checkbox is unchecked for hiding the menu icon.

Let me know if you figure anything else out.

**Comment by pixmin** [comment]
Thanks, by doing this I've been able to get to the preferences window and untick the "Hide menu bar icon" option ;)

Maybe it would be good to show it in the dock if it's hidden in the menu bar?
