### ISSUE TITLE
macOS 13 Stage Manager option

### ISSUE THREAD

**Issue by decodism** [rxhanson/Rectangle#829]
macOS 13 is only in early beta and there could be some changes but I think it would be nice to have an option to support Stage Manager. It should be enough to ignore the recent apps area on the left (about 375px on my screen), in a similar way to the todo mode on the right. It should be checked that this area is enabled (`defaults read com.apple.WindowManager GloballyEnabled` is `true` and `defaults read com.apple.WindowManager AutoHide` is `false`).

**Comment by rxhanson** [comment]
Thanks! I do typically wait a little while before rolling in any changes, but if anyone else wants to make any changes with the proper `#available` macOS versioning then I'm good with rolling something in earlier and pushing out a new release.

**Comment by Aaron-Rumpler** [comment]
From what I've seen online, the Stage manager sidebar also auto-hides if it's covered by a window, so it should probably be an option as to whether or not to ignore that sidebar. Though in my personal opinion, not covering that sidebar should probably be the default.

**Comment by decodism** [comment]
I have looked a bit into this but there is an annoying issue: when restoring a scene, the windows moved programmatically with Rectangle are first restored to their last "manual" position before adopting their correct position.

Also, I'm not sure how wide the area should be reserved. On my screen:

- It needs to be at least about 47pt, otherwise the area hides itself
- There is a "magnetic edge" at about 129pt
- The area never seems to exceed about 191pt (including a 16pt padding)

Maybe the user should be given the choice. It could also be calculated dynamically by looking for the widest "window" of WindowManager.

**Comment by hankhank10** [comment]
I have the beta installed on my secondary machine. It's very stable and in fact the only reason I wouldn't also install it on my primary machine would be that I rely on rectangle so much!

**Comment by decodism** [comment]
I sent a feedback to Apple regarding the issue I encountered. I hope they take them into account.

**Comment by dklad** [comment]
Not sure if it's because of a change in the latest version of Rectangle or the MacOS beta, but this issue appears to be resolved.
