### ISSUE TITLE
App won't recognize normal screen's full width

### ISSUE THREAD

**Issue by BlakeGiunta** [rxhanson/Rectangle#839]
Using Rectangle (latest version), on M1 Mac single-screen through my monitor.

The issue: My monitor has a normal screen ratio, and I have played with diff resolutions. No matter what resolution I change to, Rectangle will not recognize the last fifth or so of my screen. So when snapping windows to the right (e.g. top-right 4th or right 1/2) it acts as if the first 4/5ths is my whole screen. This happens both with the main hotkey command and that shortcut hotkey. 

I've tried restarting several times to confirm. Curiously, Hookshot works fine.

**Comment by rxhanson** [comment]
Check and make sure that you don't have Todo mode enabled in Rectangle. You can toggle showing Todo mode in the menu via the prefs window, and in the menu uncheck "Enable Todo Mode"

**Comment by rxhanson** [comment]
Closing this one out, but feel free to comment further if there's any updates.
