### ISSUE TITLE
Stage manager under maximized windows 

### ISSUE THREAD

**Issue by 1cedsoda** [rxhanson/Rectangle#840]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 13.0 Beta (22A5266r)
Rectangle version: v0.56 (62)

When I maximize a window with Rectangle by dragging it to the top of the screen, then Stage Manager won't pop over but under the window (when dragging the mouse to left border).

Not sure if this is a bug in Stage Manager or Rectangle. Maybe we should wait until the official Ventura release.

<img width="603" alt="Bildschirmfoto 2022-06-29 um 23 38 53" src="https://user-images.githubusercontent.com/29167146/176549687-7bc30311-6375-47a8-abea-97fe904002a3.png">

**Comment by rxhanson** [comment]
v0.57 was released yesterday with Stage manager support, where the stage manager recent apps area is left uncovered by Rectangle when it's displayed, and you can configure how much space you want to allow for the recent apps area in the settings tab of the prefs window.
