### ISSUE TITLE
Rectangle not launching in macOS High Sierra

### ISSUE THREAD

**Issue by hahnemann** [rxhanson/Rectangle#843]
I installed Rectangle directly from the website and using Homebrew and the app does not launch. I rebooted my system, uninstalled and reinstalled - still doesn't work.

macOS version: 10.13.6
Rectangle version: 0.57

**Comment by rxhanson** [comment]
Thanks for reporting. v0.57 was built using Xcode on Ventura, and is missing a library necessary to run on 10.13. You'll have to revert back to v0.56 until the next release is out.

https://github.com/rxhanson/Rectangle/releases/tag/v0.56

**Comment by hahnemann** [comment]
Thanks for providing a download link - I reverted to v0.56.

**Comment by symsym-1629** [comment]
> Thanks for reporting. v0.57 was built using Xcode on Ventura, and is missing a library necessary to run on 10.13. You'll have to revert back to v0.56 until the next release is out.
> 
> https://github.com/rxhanson/Rectangle/releases/tag/v0.56

yeah the "/usr/lib/swift/libswiftCoreGraphics.dylib" no ?

**Comment by debrunet** [comment]
I'm seeing the same on 10.13.6:
```
$ /Applications/Rectangle.app/Contents/MacOS/Rectangle 
dyld: Library not loaded: /usr/lib/swift/libswiftCoreGraphics.dylib
  Referenced from: /Applications/Rectangle.app/Contents/MacOS/Rectangle
  Reason: image not found
Abort trap: 6
```
Indeed that library @symsym-1629.

**Comment by symsym-1629** [comment]
Thats it.

**Comment by abstarstrong** [comment]
Hi, Love the work! When can we expect a new release with a fix for Rectangle on macOS version: 10.13.6?

**Comment by rxhanson** [comment]
Right now! Let me know if you hit any issues. 

https://github.com/rxhanson/Rectangle/releases/tag/v0.58

**Comment by abstarstrong** [comment]
Wow, that was fast! It is working on macOS version 10.13.6 with Rectangle v0.58.

**Comment by rxhanson** [comment]
Thanks!
