### ISSUE TITLE
Feature Request: move window to next/previous desktop

### ISSUE THREAD

**Issue by in-tension** [rxhanson/Rectangle#85]
I was wondering if it would be possible to have a shortcut for moving a window to a different desktop/workspace. Maybe something like the next/previous display shortcuts, but with desktops/workspaces.

Thanks

**Comment by rxhanson** [comment]
Update from below: 

> It's still not something I have a strong desire to add into Rectangle, but I would be fine merging in a pull request if anyone else wanted to implement it and put it behind a terminal command config (not in the UI).
> 
> This was added into [Rectangle Pro](https://rectangleapp.com/pro) (paid) a while back.

Original:

https://github.com/rxhanson/Rectangle/issues/16
https://github.com/rxhanson/Rectangle/issues/55#issuecomment-569494511

In short, Apple doesn't provide public APIs for spaces. If at some point they do, I'll be glad to to revisit this.

**Comment by in-tension** [comment]
Oh okay, thanks

**Comment by JohanNicander** [comment]
I am also interested in this, and I know that [amethyst](https://github.com/ianyh/Amethyst) has the feature "Throw focused window to space left/right" that does what I think is asked. I might try to implement it myself but I have no experience with swift so it might take a while.

What do you think?

**Comment by rxhanson** [comment]
My current opinion on this is that I would not roll it into Rectangle, even if there was a decent pull request for it. I have looked at what Amethyst did, and doing this would either require adding the library built by the Amethyst author that uses the private framework, or copying/implementing the private framework usage into Rectangle. It's not the most pleasant thing to add in, and I think my time maintaining Rectangle is best spent keeping the rest of the app bug free - not maintaining code using features not publicly supported by Apple.

With that said, here in lies the beauty of open source. There's a lot of people that would love to have this feature, so feel free to fork Rectangle. I don't mind answering a few questions here or there that crop up.

**Comment by nathanredblur** [comment]
raycast can do it, so, should be a way... 

![CleanShot 2024-08-31 at 14 40 33](https://github.com/user-attachments/assets/2d00af8d-4e45-463e-b2f9-75c6fa229619)

https://github.com/raycast/extensions/blob/main/docs/api-reference/window-management.md

**Comment by rxhanson** [comment]
This was added into Rectangle Pro a while back. It's still not something I have a strong desire to add into Rectangle, but I would be fine merging in a pull request if anyone else wanted to implement it and put it behind a terminal command config (not in the UI).

**Comment by joni-** [comment]
> It's still not something I have a strong desire to add into Rectangle, but I would be fine merging in a pull request if anyone else wanted to implement it and put it behind a terminal command config (not in the UI).
> 
> This was added into [Rectangle Pro](https://rectangleapp.com/pro) (paid) a while back.

How can I access the feature in Rectangle Pro?

**Comment by Aaron-Rumpler** [comment]
I don't think it has a shortcut set by default, so you may have to add one:
![Next Display Keyboard Shortcut - Rectangle Pro](https://github.com/user-attachments/assets/21e7a36e-edfd-405d-b04f-146a92ecb1ed)

It's also available through the menu bar item, but I'm not sure if it's shown by default or not:
![Next Display Menu Item - Rectangle Pro](https://github.com/user-attachments/assets/92a4f020-cfd4-425c-bbbe-15ca2977d9b7)

**Comment by joni-** [comment]
Awesome, thanks @Aaron-Rumpler! 🎉 I somehow missed the setting when trying out the pro version and thought that it's hidden behind terminal commands.

**Comment by chrootchad** [comment]
Who else is here with a bandaid on their finger / busted three finger swipe trackpad gesture? 🤠

> I was wondering if it would be possible to have a shortcut for moving a window to a different desktop/workspace. Maybe something like the next/previous display shortcuts, but with desktops/workspaces.

BTW.. future me landing back here next time I have a bandaid, macOS provides native support for that 👆:
https://apple.stackexchange.com/questions/362614/macos-navigating-between-desktops-using-keyboard-shortcuts

**Comment by cyber-nic** [comment]
@chrootchad not quite the same. One is to move your view to the next/previous Space, while the other is to relocate an application window to the next/previous Space.
