### ISSUE TITLE
Miniature windows from Stage Manager cannot be snapped

### ISSUE THREAD

**Issue by leodr** [rxhanson/Rectangle#853]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 13.0 Beta
Rectangle version: 0.57
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): -

Stage Manager shows any windows that are not currently on screen in their miniature form on the left.

To get them onto your current "stage" you can drag these miniatures onto the screen to where you want.

However you cannot directly snap these miniature windows when dragging from stage manager, you have to drag them onto the stage first, then drop them, to then snap them to an edge.

It would be nice if you could directly drag the miniatures from Stage Manager to the right edge for example to make them occupy the right half of the stage.

**Comment by rxhanson** [comment]
Good point. I'll see what I can do in an upcoming release. It's going to take me a while to get to it, so If anyone wants to give it a go in the meantime a PR is welcome.
