### ISSUE TITLE
Snapping window to left half does not work with Stage Manager

### ISSUE THREAD

**Issue by leodr** [rxhanson/Rectangle#854]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 13.0 beta
Rectangle version: 0.57
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): -

Dragging a window to the left edge of the screen puts it into Stage Manager as a minimized window.

AFAIK it is currently not possible on Ventura to snap a window to the left half of the screen without using the keyboard shortcuts.

**Comment by rxhanson** [comment]
If you drag it to an area above or below the Stage Manager area then it's possible. I don't think there's a way to prevent it from putting it into the Stage Manager in its area, so I think the proper path forward would be for Rectangle to not display the footprint if the window is dragged into the Stage Manager area. Unfortunately, I don't think there is a way to get the exact size/location of the Stage Manager.

**Comment by rxhanson** [comment]
(Housekeeping closing)
