### ISSUE TITLE
The key combination ⇧⌘F cannot be used

### ISSUE THREAD

**Issue by ahmetb** [rxhanson/Rectangle#855]
This is not really a bug report, but I think for whatever reason I can't assign this key Cmd+Shift+F key combination to anything in Rectangle.app.

I'm suspecting there's a macOS-builtin shortcut preventing this, as I'm noticing this on a fresh macOS installation as well with Rectangle.app, so I wanted to check if there's anything in code preventing from binding to this key combination (or what could this error be). 

If anyone knows how to debug this (which process is listening to this system-wide shortcut), I appreciate.

![image](https://user-images.githubusercontent.com/159209/179078964-ebc6bd12-d43b-4971-8d74-36ed24792f17.png)

**Comment by ahmetb** [comment]
For the record, Spotlight was assigned to this, and I'm removing it:
![image](https://user-images.githubusercontent.com/159209/179079119-d9bf172f-d6dc-4419-8e33-d3ca9b451d89.png)


![image](https://user-images.githubusercontent.com/159209/179079280-62c307e1-d0f6-4a81-b7ba-a274e05f3b44.png)

Even then, Rectangle doesn't let me bind.

**Comment by rxhanson** [comment]
Thanks for reporting. Did you check the box for "Remove keyboard shortcut restrictions"?

**Comment by ahmetb** [comment]
Thanks, I've definitely missed this setting.

**Comment by paleite** [comment]
Could a hint for this be added to the error-message?

Something along the lines of the following.

> If you still want to use this shortcut, you can check the box for "Remove keyboard shortcut restrictions" in the config.

**Comment by rxhanson** [comment]
It's been a little while since I've dug into this, but if I remember right it's not that simple to add in. I have been wanting to swap out the shortcut recorder for quite some time, so I had been putting off making changes here until that happens. However, if anyone wants to fix what's currently there to do this I'd merge a good PR for it.
