### ISSUE TITLE
Original size restored after dragging with mouse

### ISSUE THREAD

**Issue by pozitron57** [rxhanson/Rectangle#857]
Sorry if I missed it in closed issues or in the Readme.

macOS version: Mojave 10.14.6
Rectangle version: 0.57 (63)

I resize window via `ctrl`+`alt`+`+`. Then I drag window with mouse and the original size is restored. Is it an expected behaviour? I'd prefer window to keep the size I set via Rectangle shortcuts.

**Comment by Aaron-Rumpler** [comment]
This is expected behaviour. Have you tried unchecking the 'Restore window size when unsnapped' checkbox in Rectangle settings?
<img width="602" alt="Screen Shot 2022-07-18 at 9 50 13 PM" src="https://user-images.githubusercontent.com/80610725/179487099-693633dc-2d7f-4bc4-8b7f-9dce387386f3.png">

**Comment by pozitron57** [comment]
> This is expected behaviour. Have you tried unchecking the 'Restore window size when unsnapped' checkbox in Rectangle settings?

Oh, my bad. Thanks, it works. I honestly looked into preferences.
