### ISSUE TITLE
Guideboxes(?) not visible when opened on startup

### ISSUE THREAD

**Issue by mfawc** [rxhanson/Rectangle#870]
Version: 0.57
OS Version: Monterey 12.3
Model: Macbook Air (13-Inch, 2020)

I have Rectangle set to open on startup, and have noticed when dragging a window that the guideboxes (if that’s the correct name, the transparent overlay showing where the window will snap to) are not visible when attempting to snap. The window will still snap to the correct spot.

I’m able to rectify this by closing and re-opening the app, which makes the guideboxes appear again. It appears to only be broken when it’s automatically opened on startup.

**Comment by rxhanson** [comment]
Thanks for reporting this. I'll see if there's an intuitive workaround for this in the next release.

**Comment by MSTRKKRFT** [comment]
Hi! 
First, thank you very much for this great app!!
I'm just here to say I have the exact same issue on my M1 base model Macbook Air.

**Comment by rxhanson** [comment]
I never was able to reproduce this, and I'm thinking that it was a macOS glitch that was since corrected on the macOS side. Feel free to reopen if it's still an issue.
