### ISSUE TITLE
Does not move windows in Jetbrains applications since version 2022.2

### ISSUE THREAD

**Issue by chbndrhnns** [rxhanson/Rectangle#872]
I used to use Rectangle to organize my windows for PyCharm and IDEA and starting with 2022.2, this seems to not work anymore.

If I focus IDEA and left-click the Rectangle icon, I see the "Ignore IntelliJ IDEA" entry but all position entries in the context menu are greyed out.

In case that's rather an IntelliJ bug, I am happy to report there, as well.

- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.4
Rectangle version: 0.53
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

```
2022-07-31T13:10:38+02:00: Unable to obtain the accessibility element with the specified attribute at mouse location
2022-07-31T13:10:38+02:00: Unable to obtain the accessibility element with the specified attribute at mouse location
2022-07-31T13:10:40+02:00: Unable to obtain accessibility element
2022-07-31T13:10:40+02:00: Failed to find frontmost window.
2022-07-31T13:10:46+02:00: Unable to obtain accessibility element
2022-07-31T13:10:46+02:00: Failed to find frontmost window.

```

**Comment by rxhanson** [comment]
Thanks for reporting. Unfortunately this is something that would have to be fixed on Jetbrains’ side. Rectangle uses the macOS accessibility API to move/resize windows and this is a scenario where the other application is not responding to these commands. You can try restarting IDEA, as this fixes the issue for some apps.

**Comment by chbndrhnns** [comment]
In this case, restart Rectangle did the trick.
Any idea what could have caused this?

**Comment by rxhanson** [comment]
This type of scenario is typically seen with cross platform applications. It’s likely that cross platform apps do some windowing behaviors slightly different and can lead to falling out of sync with the accessibility windowing api and Rectangle‘s calls to it. If there were something that made sense to change in Rectangle to fix it, I would, but Rectangle just makes standard calls to the API.
