### ISSUE TITLE
Stage Manager Area is for Rectangle always on the left side, but my Stage Manager is on the right.

### ISSUE THREAD

**Issue by mi-uhu** [rxhanson/Rectangle#885]
When placing the dock on the left side of the screen, Stage Manager is positioned on the right. 
It would be really cool if there was a checkbox in the Stage Manager area that allows me to change the Stage-Manager-Position for Rectangle to the right side. 

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/40274456/185595304-30da4ec3-c4f7-44e6-b4c2-95b4a4ee03d4.png">

macOS version: 13.0 beta
Rectangle version: 0.57
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):

**Comment by rxhanson** [comment]
Thanks for reporting. The fix for this will be in an upcoming release.

**Comment by gabalicious** [comment]
I have the opposite issue.  My stage manager is on the right for external monitors and when maximized, rectangle attempts to clear room for stage manager on the left even though it should be on right. Correctly works for laptop display.

![Screenshot 2022-10-26 at 8 23 52 AM](https://user-images.githubusercontent.com/241617/198025290-e3d42bef-a360-403c-8667-c0d92d0eb539.png)

**Comment by jordangarrison** [comment]
I also have the issue @gabalicious is experiencing. With external monitors the rectangle area is covering the stage manager on the left. Seems to be driven by the arrangement of displays.

**Comment by rkapur-gds** [comment]
It looks like this issue persists in the following circumstances:
- The Dock is positioned to the left
- The Dock is set to auto hide

**Comment by jordangarrison** [comment]
> It looks like this issue persists if the following are true:
> 
> * The Dock is positioned to the left
> * The Dock is set to auto hide

I did have my dock set to auto hide, however, I position it on the bottom. When I disabled the autohide and restarted rectangle the problem still persists. It seems to only come into play on more than 2 screens (perhaps because I position my dock on the bottom?).

**Comment by jordangarrison** [comment]
Update: Just saw the update and it appears to have fixed the issue for me.
