### ISSUE TITLE
Conflict with Aqua Data Studio 22.2.0

### ISSUE THREAD

**Issue by jayotto** [rxhanson/Rectangle#888]
- [X] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.5
Rectangle version: 0.57 (63)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

2022-08-24T12:11:52-07:00: Unable to obtain the accessibility element with the specified attribute at mouse location

When Rectangle is running, contextual menus in AquaDataStudio 22.2.0 (https://www.aquafold.com/) do not work at all. 

I can work around this problem by disabling Rectangle in System Preferences -> Security & Privacy -> Accessibility

The results are the same regardless of whether "Ignore DataStudio" is selected in the Rectangle menu or not.

I have heard that MatLab is having a similar problem:
https://www.mathworks.com/matlabcentral/answers/515780-why-do-i-get-java-exceptions-java-lang-nullpointerexception-when-i-use-matlab-with-window-magnet-or#answer_424342

Thanks!

**Comment by rxhanson** [comment]
Thanks for reporting. There is such a small amount of apps like this that I manually add them to a list to handle them differently. Mat lab is already on that list. Can you provide the bundle I’d for this app and I will add it?

**Comment by jayotto** [comment]
Apologies for slow response here, I just found the notification: The bundle identifier is "com.aquafold.datastudio.DataStudio"
