### ISSUE TITLE
Record hyper (control + opt + shift + cmd) + del doesn't work

### ISSUE THREAD

**Issue by tim-hilde** [rxhanson/Rectangle#900]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.5.1
Rectangle version: 0.58 

It is not possible to set hyper (control + opt + shift + cmd) + delete as a shortcut.

**Comment by AndrewHaglund** [comment]
FYI this does work using Karabiner to map Caplock to control + opt + shift + cmd — but not if you manually type it.

**Comment by tim-hilde** [comment]
> FYI this does work using Karabiner to map Capslock to control + opt + shift + cmd — but not if you manually type all the keys.

Actually, this doesnt work either. I am using Karabiner to create the hyper key you outlined but it doesnt work. Seems to be related to the "delete" key, as other combinations work. e.g. hyper + left-arrow

**Comment by AndrewHaglund** [comment]
My mistake, you are correct 👍

**Comment by rxhanson** [comment]
Interesting, appears to be some sort of bug with the shortcut recorder, MASShortcut.

If I record it using Hyperkey (https://hyperkey.app, written by yours truly), it works fine. If I record it by manually holding the modifiers, it does not work. 

As a workaround, you could try exporting your config, setting almostMaximize to this:

```
    "almostMaximize" : {
      "keyCode" : 51,
      "modifierFlags" : 1966080
    },
```
 
and importing your config back in.

It's enough of an edge case that I probably won't make any immediate adjustments for it. I haven't updated MASShortcut in a little while, so it could be fixed there. If not, my suggestion would be to file an issue there, and I can always pull in the latest MASShortcut.

**Comment by tim-hilde** [comment]
Your workaround still doesnt work. Pressing said keys still doesn't work.

**Comment by rxhanson** [comment]
@tim-hilde Sorry that didn't work! Thanks for trying it out and posting back. Looks like a fix MASShortcut side might be the only solution (outside of using Hyperkey).

**Comment by tim-hilde** [comment]
@rxhanson Would you mind testing this with an updated version of MASShortcut? I have no way of testing it myself, don't I?

**Comment by ankerek** [comment]
I have the same issue.

**Comment by oschrenk** [comment]
I have a smiliar issue but with `Q` .

hyper (control + opt + shift + cmd) + Q doesn't work either.

**Comment by rxhanson** [comment]
I will be changing out the existing shortcut recorder for a different one in an upcoming release, so at that time it will make sense to look back into this.

**Comment by rxhanson** [comment]
Closing this one out, mainly because it boils down to shortcut interception by another app or by macOS. At a certain point I decided to stick with MASShortcut and maintain a fork of it myself that Rectangle uses. If this happens to be a scenario that is indeed fixed by moving to a different shortcut recorder, then I will re-evaluate.
