### ISSUE TITLE
Beware of fraudulent phishing/malware impersonation

### ISSUE THREAD

**Issue by fieu** [rxhanson/Rectangle#908]
I think I got scammed.

I looked up Rectangle Pro and first result was https://www.rectanglemac.com/

I clicked without hesitation and purchased it (5€ PayPal).

After clicking I was redirected to a MEGA download link which I knew was weird so I didn't download it.

I will provide the link if requested but I don't want to potentially infect people.

There is not much to say, but I'm disappointed. Beware.

**Comment by Aaron-Rumpler** [comment]
That's definitely a scam site. The real Rectangle is at https://rectangleapp.com/ (as linked from this repo), uses Paddle for payment processing, and hosts the downloads directly off of their web site directly. See if you can lodge a dispute through PayPal and get your money back.

**Comment by Aaron-Rumpler** [comment]
For me, it's top of page 2 on Google. I've reported the site to Google Safe Browsing and Microsoft Security Intelligence, as well as CloudFlare (which the site's behind) and Namecheap (the registrar for the domain).

**Comment by Aaron-Rumpler** [comment]
![Rectangle Pro Latest App Download For Mac OS](https://user-images.githubusercontent.com/80610725/188364636-89e54ae7-4d04-42ee-a237-ee710e9f1db0.png)
Here's a screenshot of the site if anyone's interested (done using one of those online services that does the screenshotting on their backend).

**Comment by Aaron-Rumpler** [comment]
There's even a fake Twitter account (@Rectanglemac).

**Comment by rxhanson** [comment]
@fieu Sorry to hear about your experience here (and thanks for looking to make the jump to pro in the first place). I've reported against this site in the past, but I think the more users that file against it, the more likely that it will finally be taken down.

@Aaron-Rumpler thanks for promptly and thoroughly reporting it! 

Here are the links to all the places to file:

NameCheap (the registrar)
https://support.namecheap.com/index.php?/Tickets/Submit

Cloudflare
https://abuse.cloudflare.com

Google safe browsing
https://safebrowsing.google.com/safebrowsing/report_phish/

Microsoft Security Intelligence
https://www.microsoft.com/en-us/wdsi/support/report-unsafe-site-guest

Twitter: fraudulent handle is @Rectanglemac
https://help.twitter.com/en/forms/authenticity/impersonation

**Comment by fieu** [comment]
You live and you learn. I appreciate everyone's interest in the matter, I've gone ahead and reported it to the sites listed.

**Comment by rxhanson** [comment]
One thing I didn't mention: for anyone that fell for the scam and paid them via PayPal, please dispute the charge with PayPal. With enough disputes, it's more likely that PayPal will stop processing payments for the scam than the site actually being pulled down.
