### ISSUE TITLE
Not a bug - just a thank you

### ISSUE THREAD

**Issue by FloWi** [rxhanson/Rectangle#909]
Please close after reading :)

I just found Rectangle as a replacement for spectacle and just wanted to thank you for taking care of such a nice quality-of-life app. So many cool features to make nerds like me happy :)

**Comment by rxhanson** [comment]
I'm glad you are enjoying it! Also, a huge thanks to the other devs and translators that have pitched in!

**Comment by SavePointSam** [comment]
Wanted to pile-on a huge thank you from me as well. I _lived_ off using Spectacle for the last few years and recently was forced to move away from it. A few difficult weeks later I stumbled here and WOW! Thank you to the whole team! <3
