### ISSUE TITLE
Show all changelogs after update

### ISSUE THREAD

**Issue by ZetiX** [rxhanson/Rectangle#93]
When updating currently, if the user is upgrading from a much older version, the change log that shows after the update will only show the latest change log.

**Comment by rxhanson** [comment]
Sparkle doesn't currently provide a way to do this, and it doesn't appear that people are asking for it:

https://github.com/sparkle-project/Sparkle/issues/985

I could just cram a ton of the release notes into each release, and you could read as much of it as you want (I've seen other apps do this with Sparkle), but I think I will just start putting a link in the Sparkle release notes to a release notes page hosted on the website.

**Comment by ZetiX** [comment]
That would be great! Thank you so much!
