### ISSUE TITLE
Microsoft Remote Desktop - remote pc resolution is not being changed

### ISSUE THREAD

**Issue by marekmasek** [rxhanson/Rectangle#930]
macOS version: 12.5
Rectangle version: 0.59 (65)

Remote pc resolution in Microsoft Remote Desktop app is not being changed, If I resize the window of the app using Rectangle. Sometimes it's working, but most of the time, it doesn't work.
The resolution of the remote pc is being changed correctly If I change the window size using macOS built-in resize shortcuts.

https://user-images.githubusercontent.com/48589322/192819867-d25f0a59-52d8-4076-b8f7-06a0fe254737.mp4

**Comment by rxhanson** [comment]
Thanks for reporting. Unfortunately, this looks like something that would have to be resolved Remote Desktop side. It has to manage resolution & sizing differently from a typical app window, and they're likely not properly handling the scenario of being resized via the accessibility API in macOS.

**Comment by marekmasek** [comment]
I see, thank you. I'll report the issue to Microsoft.
