### ISSUE TITLE
Authorize Rectangle pop-up every restart

### ISSUE THREAD

**Issue by marekmasek** [rxhanson/Rectangle#931]
macOS version: 12.6
Rectangle version: 0.59 (65)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): log is empty

I have enabled the option: "Launch on login" and Rectangle is authorized to control my mac.
But "Authorize Rectangle" pop-up is showing every time I restart the system.
I have to quit Rectangle and reopen it every restart to make it work.

![image](https://user-images.githubusercontent.com/48589322/192829596-624493bb-751c-44ea-903e-2d7cb54ef579.png)

**Comment by rxhanson** [comment]
MacOS 12.6 included some underlying changes to Accessibility management that have been rather flaky for some users.

I would try deleting the app (cmd+option+delete in Finder), and then reinstall the app. That might clear any caches in macOS that are not properly remembering the authorization.

**Comment by Aaron-Rumpler** [comment]
I'd also remove Rectangle from the Accessibility list (selecting at and clicking the remove button, as opposed to unchecking it) after quitting Rectangle but before deleting it. I've found macOS remembers the accessibility authorization after you remove an app.

**Comment by marekmasek** [comment]
I had this issue also on MacOS 12.5
I tried to remove the app from the "Accessibility list" and reinstall the app, but the problem is still there.

**Comment by rxhanson** [comment]
Closing out old issues. I think there were some macOS changes that fixed this one, but the workaround still remains to quit Rectangle, uncheck it, then remove it in System Settings.
