### ISSUE TITLE
Rectangle get bug on VScode

### ISSUE THREAD

**Issue by Juliantreinta** [rxhanson/Rectangle#936]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.6
Rectangle version: Version 0.59
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

2022-10-05T16:52:27-05:00: Unable to obtain window id
2022-10-05T16:52:58-05:00: Unable to obtain the accessibility element with the specified attribute at mouse location

**Comment by rxhanson** [comment]
Unfortunately, there's not really anything that can be done about this on Rectangle's side. You'll need to restart VSCode, which usually fixes it, and report it to the VSCode team.

**Comment by Juliantreinta** [comment]
Thanks, it worked!
