### ISSUE TITLE
Feature: `Almost Maximize of Stage Manager`

### ISSUE THREAD

**Issue by shindgewongxj** [rxhanson/Rectangle#940]
### Discussed in https://github.com/rxhanson/Rectangle/discussions/935

<div type='discussions-op-text'>

<sup>Originally posted by **shindgewongxj** October  4, 2022</sup>
On macOS Ventura with Stage Manager on, the 'Almost Maximize' will cover Stage Manger preview and desktop items. While reopen the 'Almost Maximized' window, it will be resized to 'Almost Almost Maximize' that won't cover Stage Manger preview or desktop items. So, will there be an option as called 'Almost Almost Maximize'? @rxhanson </div>

**Comment by rxhanson** [comment]
Sorry, I'm not quite sure I understand the desired outcome. Would it be sufficient to just use the existing terminal commands to get what you're looking for?
https://github.com/rxhanson/Rectangle/blob/master/TerminalCommands.md#almost-maximize
and the one below it:
https://github.com/rxhanson/Rectangle/blob/master/TerminalCommands.md#add-an-extra-centering-command-with-custom-size

**Comment by shindgewongxj** [comment]
That't it! Sorry for my poor language expression! And BTW, what is the bundle name of rectangle pro?
