### ISSUE TITLE
Can't turn off

### ISSUE THREAD

**Issue by GNHua** [rxhanson/Rectangle#941]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.6 Monterey M1 Max
Rectangle version: v0.59 (65)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): I closed Rectangle and killed the process in Activity Monitor, but the Rectangle keyboard shortcuts are still active, i.e. I can still move windows with keyboard shortcuts when Rectangle is closed.

**Comment by rxhanson** [comment]
(There is no possibility for Rectangle to function if it's not running :)

**Comment by GNHua** [comment]
Yeah. That makes sense. But I am pretty sure there is no other window manager with the same key bindings on my laptop.
My guess is that I did not turn it off completely. If I force quit, it should be killed, right?

**Comment by rxhanson** [comment]
If it's not in Activity Monitor, then it is not running and there is no way that it could be Rectangle moving or resizing your windows.

**Comment by GNHua** [comment]
I figured out. I have a KVM system which seems to mess up with Rectangle. Close issue.
