### ISSUE TITLE
Rectangleapp.com starts downloading some file?

### ISSUE THREAD

**Issue by karukenert** [rxhanson/Rectangle#945]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

This is not version specific and happens in both chrome and safari. 

Reproduction: 
1. navigate to rectangleapp.com
2. wait few seconds
3. some automatic download starts?

If you open up the console prior to navigating the to domain, you can see that the download starts when an uncaught exception is thrown. 

![image](https://user-images.githubusercontent.com/46687296/195511857-ef115171-9531-4123-b76b-6575c390664a.png)

**Comment by rxhanson** [comment]
Thanks for letting me know. I use Wistia to host the demo video on the page, and it's a bug their side. I'll see if I can put in a workaround my side.

**Comment by rxhanson** [comment]
Until it gets figured out Wistia side, I've just removed the demo video. Thanks again!

**Comment by rxhanson** [comment]
Turned out it was a bug in my javascript, and the Wistia team did some excellent customer support to troubleshoot it for me. I highly recommend Wistia if anyone's looking for video hosting.
