### ISSUE TITLE
Very slow to perform window resizing or repositioning

### ISSUE THREAD

**Issue by krp312** [rxhanson/Rectangle#963]
Greetings,

Rectangle is suddenly taking several seconds to perform window resizing/repositioning.

MacOS: 12.6
Rectangle: 0.60 (66)

[Video](https://imgur.com/u3RYLoN)

Log:

```
2022-10-26T10:50:50-04:00: AX sizing proposed: (840.0, 1025.0), result: (840.0, 1025.0)
2022-10-26T10:50:50-04:00: AX position proposed: (840.0, 25.0), result: (840.0, 25.0)
2022-10-26T10:50:50-04:00: AX sizing proposed: (840.0, 1025.0), result: (840.0, 1025.0)
2022-10-26T10:50:50-04:00: rightHalf | display: (0.0, 0.0, 1680.0, 1025.0), calculatedRect: (840.0, 25.0, 840.0, 1025.0), resultRect: (840.0, 25.0, 840.0, 1025.0), srcScreen: Built-in Retina Display, destScreen: Built-in Retina Display, resultScreen: Built-in Retina Display
```

Many thanks in advance!

**Comment by krp312** [comment]
Thanks for the quick reply! Yeah I've tried a restart.

I've observed the slow behavior after installing Steam. I removed it, but that didn't help. If I figure out what's wrong, I will follow up.

**Comment by krp312** [comment]
@rxhanson, I just upgraded to macOS 13. I've noticed that Rectangle is faster but there is still about a 2 second delay for resizing/repositioning. I would like to try debugging this before taking more drastic actions, but I'm not sure where to start. Could you point me in the right direction?

**Comment by rxhanson** [comment]
Sure, if you get things fired up in Xcode, you can just throw a breakpoint in `WindowManager` in the `execute` function and walk through everything to see where something might get hung up.

My hunch is that this is being caused by something outside of Rectangle. After all, Rectangle is literally just making window size/position calculations and telling macOS's accessibility API to move/resize a window.

**Comment by krp312** [comment]
I hear ya, I'm on the same page — this is probably a problem unique to my computer. I was hoping to get started on debugging  from the macOS side (the accessibility API). Any thoughts on how I can get started with that? If not, it's ok.

**Comment by rxhanson** [comment]
You could try removing all the apps from the Privacy & Security -> Accessibility section in System Prefs, and see if only having Rectangle shows any differences. If it does, try adding back in everything else one by one and see if you can figure out what caused it.

**Comment by KiwiJason** [comment]
I've also started to experience this in the past couple of weeks but only with Chrome - the number of tabs open doesn't seem to affect this.

I tried removing all the apps listed in Privacy & Security -> Accessibility (only had one other) and didn't see any improvement.

**Comment by rxhanson** [comment]
@KiwiJason That's a bug Chrome side, there's a workaround I built in, see the end of the issue: https://github.com/rxhanson/Rectangle/issues/912

**Comment by KiwiJason** [comment]
I missed that. Thanks! That fixed it for me.

**Comment by krp312** [comment]
@rxhanson I'm thrilled to report that Rectangle is back to normal after updating to 0.63 (69). Curious, any idea what might have fixed it? Should I close this thread?

**Comment by rxhanson** [comment]
@krp312 Thanks for following up! The latest changes in 0.63 were specific to Ventura. Multiple parts of the code outside of Ventura specific stuff was changed, but not in ways that would have directly fixed your issue. Unfortunately, in my experience, that means that you might have a scenario where there might be something else affecting the window operations, and that carries the potential that it could be intermittent. Hopefully that's not the case and it's somehow fixed. I'm going to close this just for housekeeping, and we can reopen it if you hit it again.
