### ISSUE TITLE
[MacOS Apple Silicon] Writer+Calc hang frequently

### ISSUE THREAD

**Issue by penalvch** [rxhanson/Rectangle#964]
With Rectangle and LibreOffice Calc and/or Writer open, LibreOffice frequently hangs, requiring one to force close the program.

In case this is something for Rectangle developers to fix, cross post from LibreOffice bug report:
https://bugs.documentfoundation.org/show_bug.cgi?id=151363

macOS version: 13.0
Rectangle version: 0.60
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):
[Rectangle.txt](https://github.com/rxhanson/Rectangle/files/9874979/Rectangle.txt)

**Comment by rxhanson** [comment]
Is this a duplicate of https://github.com/rxhanson/Rectangle/issues/933?

**Comment by penalvch** [comment]
Hi @rxhanson thanks for the quick response!

I didn't click 'maximize' but it could very well be same root cause. If you think it should be dup'd that's fine with me.

Thanks!

**Comment by penalvch** [comment]
It's been discussed [https://bugs.documentfoundation.org/show_bug.cgi?id=148435](here) that a LibreOffice patch has resolved this. While I've not been able to personally confirm, I'm going to close this out.

**Comment by rxhanson** [comment]
Thanks. If it does not actually fix the issue then feel free to reopen.
