### ISSUE TITLE
Rectangle hotkeys conflict after upgrade to Ventura

### ISSUE THREAD

**Issue by braeti** [rxhanson/Rectangle#966]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 13.0 (22A380)
Rectangle version: 0.60 (66)

Hi!

After upgrading to Ventura, the following hotkeys no longer work: Left Half / Right Half / Upper Half / Lower Half.
I'm using the standard Rectangle hotkey preset.
When I try to reassign the hotkeys, it won't let me because it probably conflicts with another system-wide hotkey that I don't know.
Stage manager is not enabled. And no hotkeys have been customized by me since the upgrade to Ventura.

…and thanks so much for this amazing software!

**Comment by rxhanson** [comment]
Thanks for reporting. The system-wide hotkeys haven't changed in Ventura to cause any conflicts. My guess is that you have something running on your Mac that is absorbing the hotkeys (maybe another window manager that was set to launch on login?). Sometimes after an upgrade, you need to do one more restart to get macOS to operate properly with regard to the API that Rectangle relies on for window management - maybe that's worth a shot if you haven't done so already?

**Comment by braeti** [comment]
Many thanks for your prompt reply and the info regarding system-wide hotkeys not having changed in Ventura. I did another restart and also unfortunately can't find another window manager that was set to launch on login.
