### ISSUE TITLE
bring window into focus programmatically

### ISSUE THREAD

**Issue by dbieber** [rxhanson/Rectangle#97]
Forgive me asking this question rather out of place and of course feel free to close the issue.

I'm wondering if you can shed light on how to bring a window into focus programmatically on Mac (like the feature requested in https://github.com/rxhanson/Rectangle/issues/91). Seems like something you might have familiarity with as Rectangle developers.

I found projects that aim to do this such as pyautogui, but nothing that actually achieves this result.

**Comment by rxhanson** [comment]
Here's a quick function in ModMove to look at:
https://github.com/keith/ModMove/blob/c5d7bf3f37db8f834eee8c7e4d93553570162554/ModMove/AccessibilityElement.swift#L64

I think this is the best you can get when you're manipulating windows outside of your own app. If you find a better way, or if you come across any issues with doing it that way, definitely let me know - I'm curious.

**Comment by rxhanson** [comment]
So there is a little more to this that I should mention:

* The approach in ModMove uses the Accessibility API, meaning it works on either the frontmost window or the window underneath the cursor. 
* There's not a direct binding between Accessibility and CGWindow APIs, so you can't take a CGWindow and make it key (as far as I know)
* You can still grab the PID of the CGWindow and bring that app frontmost.

This means that what you are looking to achieve might not be possible, but you might be able to get something working that's close to what you want.

**Comment by dbieber** [comment]
Thanks for the pointers!

> You can still grab the PID of the CGWindow and bring that app frontmost.

That sounds really promising.
Using the snippet at https://github.com/asweigart/pyautogui/issues/363 I can get the PID of the windows I'm interested in.
I think what you're suggesting is to get the PID of the window I want to make front in the way I know how, then use that PID with the Accessibility API to bring that window to the front.

I'll give this a try and see if I can get it working.

**Comment by dbieber** [comment]
Brief update here is that I was unable so far to get the accessibility API working. I tried setting up PyAtom to do so, but no luck yet.

**Comment by crazzle** [comment]
@dbieber @rxhanson I took your comments (and #91) as a motivation to develop a little tool that puts focus to a specific window. This issue is pretty old but maybe you are still interested @dbieber.

You can find the code here:
https://github.com/crazzle/SwitchR

**Comment by rxhanson** [comment]
@crazzle Cool! Thanks for sharing it! There's a couple other people that have asked for this and I'll point them to it.
