### ISSUE TITLE
Chrome is Disabled on Mac

### ISSUE THREAD

**Issue by chaseWillden** [rxhanson/Rectangle#970]
I'm using chrome and for some reason, the menu is disabled. I assume because it can't find this: https://github.com/rxhanson/Rectangle/blob/00b739627abb578ef71a30a751a483f51b1b8ed3/Rectangle/AppDelegate.swift#L290 

- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.6
Rectangle version: Version 0.61 (67)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

2022-10-28T11:37:16-06:00: Unable to obtain accessibility element
2022-10-28T11:37:16-06:00: Failed to find frontmost window.

**Comment by rxhanson** [comment]
Thanks for reporting. Unfortunately, this would be an issue Chrome side, where it's stopped responding to the window (accessibility) API in macOS. Try restarting Chrome (or filing a bug Chrome side if it persists).
