### ISSUE TITLE
Cannot use "option" as a modifier on Logitech Craft Keyboard

### ISSUE THREAD

**Issue by fraander** [rxhanson/Rectangle#99]
When using my Logitech Craft Keyboard I cannot use Option as a modifier key. This keyboard features the ability to change layouts based on the device so it probably has to do with how the key input is being interpreted. Hasn't been a problem with other programs on my device so not sure what's up.

**Comment by rxhanson** [comment]
Sounds like this is an issue with recording the shortcut, as opposed to using the shortcut, right? If that's the case, then we might be looking at why [MASShortcut](https://github.com/shpakovski/MASShortcut) isn't accepting it. MASShortcut doesn't have any issues listed that are specific to Logitech. MASShortcut is basically just a UI wrapper around Apple's built-in hotkey registration, so the problem could be with macOS detecting the option keypress.

The other programs that the keyboard works fine with, do any of them use keyboard shortcut recorders?

**Comment by fraander** [comment]
Yes. The keyboard works fine with other Shortcut recorders. Specifically the one in Magnet which from a user perspective looks the same (I’m not really a developer so not sure if on the backend they’re really different)

**Comment by rxhanson** [comment]
Good to know, thanks. Magnet does use MASShortcut, but it could be an older version or it could be modified since it's open source. 

Troubleshooting this one would take some updates to the logging to find out exactly what's going on. 
In the meantime, is the issue that when you press the option key, it is just not displayed in the shortcut recorder?

**Comment by fraander** [comment]
Yes that is exactly the issue. I cannot use the option key as a modifier, but the other modifier keys work.

Sorry it took so long to respond, this got caught in the junk folder.

**Comment by rxhanson** [comment]
I suspect it's probably an easy fix within MASShortcut, but it would require some back and forth testing out with you since I don't have that keyboard. It might be worthwhile to try it out with MASShortcut's demo app and file a bug there before we go down that path.

**Comment by fraander** [comment]
Okay. I’ll go take a look at the MASShortcut demo app and see where that gets me.

**Comment by georgesnow** [comment]
To confirm the key code that the Logitech is using you could try “Key Codes”. it’s on the Mac App Store. 

Just thinking here does the issue happen with all apps that are focused as opposed to specific apps?
