### ISSUE TITLE
Background login item persists after uninstallation

### ISSUE THREAD

**Issue by gregnavis** [rxhanson/Rectangle#992]
macOS version: 13.0 Ventura
Rectangle version: 0.61

I installed Rectangle long ago before I upgraded to Ventura. I removed it today, but the login item persists. Suggested steps to reproduce:

1. Download and install Rectangle.
2. Enable "Run at login".
3. Disable "Run at login".
4. Uninstall Rectangle.
5. Run `defaults delete com.knollsoft.Rectangle`.
6. Remove related files from `~/Library` that were found by `find ~ -iname '*knollsoft*'`:
  - `./Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.knollsoft.rectanglelauncher.sfl2`
  - `./Library/Preferences/com.knollsoft.Rectangle.plist`
  - `./Library/Application Scripts/com.knollsoft.RectangleLauncher`
  - `./Library/Containers/com.knollsoft.RectangleLauncher`
  - `./Library/Containers/com.knollsoft.RectangleLauncher/Data/Library/Application Scripts/com.knollsoft.RectangleLauncher`
7. Go to System Preferences / General / Login Items.

**Expected Result**. Rectangle.app is absent from login items.

**Actual Result**. Rectangle.app is still present.

I'm not well-versed in the macOS launch daemon and need some guidance. Happy to contribute a documentation update after we figure out where that login item comes from.

**Comment by rxhanson** [comment]
Thanks for reporting, sorry for the delayed response. At some point, I'll be migrating the app over to the Ventura way of doing this, which will remove the need for the additional helper app & login item. This login item should go away next time you log out and log back in or restart your machine.

**Comment by gregnavis** [comment]
No problem, @rxhanson! Appreciate you taking time to look into that.

I'm on Mac Mini and shutdown and boot up my system every day. It seems the item persists, though.

Let me know if there's something I could do to assist debugging.

**Comment by rxhanson** [comment]
Closing this one out, since we are long past the migration away from the helper :)
