### ISSUE TITLE
With Stage Manager active, Windows positioning is compromised by the stage

### ISSUE THREAD

**Issue by thpang** [rxhanson/Rectangle#993]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Ventura 13.0
Rectangle version: 0.16 (67)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): None

With Stage Manager active. The screen size appears to have been chopped by the size of the thumbnail windows of the stage manager when minimized. 

The expected action when I move a window to the left would be that it moves all the way to the left and does not leave the stage manager windows uncovered.

**Comment by rxhanson** [comment]
Thanks for reporting. This is by design. You can make the "Stage Manager recent apps area" set to 0 by adjusting the corresponding slider in the settings tab of the prefs window.
